// lessons/es.js — Spanish translations for all 45 lessons
// Italian lines (line, italian) are IDENTICAL to en.js — do not change them.
// Only: keywords[].english, dialogue[].translation, grammar.title/points/note differ.

export const LESSONS = [
  {
    id: 1, title: "Saludos", subtitle: "Il Saluto", free: true,
    keywords: [
      { italian: "Ciao", english: "Hola / Adiós (informal)" },
      { italian: "Salve", english: "Hola (neutro/formal)" },
      { italian: "Buongiorno", english: "Buenos días / Buen día" },
      { italian: "Buonasera", english: "Buenas noches" },
      { italian: "Arrivederci", english: "Adiós (formal)" },
      { italian: "Tutto bene", english: "Todo bien / ¿Qué tal?" },
    ],
    dialogue: [
      { speaker: "A", line: "Buongiorno! Salve.", translation: "¡Buenos días! Hola." },
      { speaker: "B", line: "Ciao! Come stai?", translation: "¡Hola! ¿Cómo estás?" },
      { speaker: "A", line: "Tutto bene, grazie. E tu?", translation: "Todo bien, gracias. ¿Y tú?" },
      { speaker: "B", line: "Bene, grazie!", translation: "¡Bien, gracias!" },
    ],
    grammar: {
      title: "Come — Cómo / Qué",
      points: [
        { italian: "Come stai?", english: "¿Cómo estás? (informal)" },
        { italian: "Come sta?", english: "¿Cómo está usted? (formal)" },
        { italian: "Come va?", english: "¿Cómo va todo?" },
        { italian: "Come?", english: "¿Cómo? / ¿Perdón?" },
      ],
      note: "\"Come\" significa literalmente \"cómo\" — es tu palabra clave para preguntar sobre estados y situaciones.",
    },
    aiPrompt: "STRICT RULES: Only discuss vocabulary and grammar from this specific lesson. If asked about anything unrelated reply only: 'Let us stick to this lesson!' Never break character. Always reply in Spanish, but use Italian words and phrases from the lesson. Correct the student gently. You are an Italian language tutor. The student just learned Lesson 1: Greetings. Help them practice: Ciao, Salve, Buongiorno, Buonasera, Arrivederci, Tutto bene, Come stai, Come va. Keep responses short and warm.",
  },
  {
    id: 2, title: "Presentarse", subtitle: "Presentarsi", free: false,
    keywords: [
      { italian: "Mi chiamo…", english: "Me llamo…" },
      { italian: "Sono…", english: "Soy…" },
      { italian: "Piacere", english: "Mucho gusto" },
      { italian: "Di dove sei?", english: "¿De dónde eres?" },
      { italian: "Sono di…", english: "Soy de…" },
      { italian: "Quanti anni hai?", english: "¿Cuántos años tienes?" },
    ],
    dialogue: [
      { speaker: "A", line: "Ciao! Sono Paolo.", translation: "¡Hola! Soy Paolo." },
      { speaker: "B", line: "Ciao, Paolo. Sono Monica. Piacere!", translation: "Hola, Paolo. Soy Monica. ¡Mucho gusto!" },
      { speaker: "A", line: "Piacere mio. Di dove sei?", translation: "El gusto es mío. ¿De dónde eres?" },
      { speaker: "B", line: "Sono di Firenze. E tu?", translation: "Soy de Florencia. ¿Y tú?" },
      { speaker: "A", line: "Sono di Milano.", translation: "Soy de Milán." },
    ],
    grammar: {
      title: "Essere — El verbo «Ser/Estar»",
      points: [
        { italian: "Io sono", english: "Yo soy" },
        { italian: "Tu sei", english: "Tú eres (informal)" },
        { italian: "Lei è", english: "Usted es (formal) / Ella es" },
        { italian: "Lui è", english: "Él es" },
        { italian: "Noi siamo", english: "Nosotros somos" },
        { italian: "Voi siete", english: "Vosotros sois" },
        { italian: "Loro sono", english: "Ellos son" },
      ],
      note: "En italiano, raramente hace falta decir \"io\" (yo) — la terminación del verbo indica quién habla.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor. Reply in Spanish. Practice introductions: Mi chiamo, Sono, Piacere, Di dove sei, Sono di. Correct gently, keep it short and warm.",
  },
  {
    id: 3, title: "En el Café", subtitle: "Al Bar", free: false,
    keywords: [
      { italian: "Un caffè, per favore", english: "Un café, por favor" },
      { italian: "Vorrei…", english: "Quisiera…" },
      { italian: "Quanto costa?", english: "¿Cuánto cuesta?" },
      { italian: "Il conto", english: "La cuenta" },
      { italian: "Un cornetto", english: "Un croissant" },
      { italian: "Grazie mille", english: "Muchas gracias" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Un caffè, per favore.", translation: "¡Buenos días! Un café, por favor." },
      { speaker: "Barista", line: "Subito! Vuole anche un cornetto?", translation: "¡Enseguida! ¿Quiere también un croissant?" },
      { speaker: "Cliente", line: "Sì, grazie. Quanto costa?", translation: "Sí, gracias. ¿Cuánto es?" },
      { speaker: "Barista", line: "Un euro e cinquanta, prego.", translation: "Un euro cincuenta, por favor." },
      { speaker: "Cliente", line: "Ecco. Grazie mille!", translation: "Aquí tiene. ¡Muchas gracias!" },
    ],
    grammar: {
      title: "Vorrei — Peticiones corteses",
      points: [
        { italian: "Vorrei un caffè", english: "Quisiera un café" },
        { italian: "Vorrei il conto", english: "Quisiera la cuenta" },
        { italian: "Vorrei prenotare", english: "Quisiera reservar" },
        { italian: "Vorrei un tavolo", english: "Quisiera una mesa" },
      ],
      note: "\"Vorrei\" es el condicional de \"volere\" (querer). Más cortés que \"voglio\" — úsalo siempre en tiendas y restaurantes.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a barista. Reply in Spanish. Use only lesson 3 vocabulary. Be warm, correct gently.",
  },
  {
    id: 4, title: "En la Heladería", subtitle: "In Gelateria", free: false,
    keywords: [
      { italian: "Un gelato", english: "Un helado" },
      { italian: "Che gusti?", english: "¿Qué sabores?" },
      { italian: "Cono o coppetta?", english: "¿Cucurucho o copa?" },
      { italian: "Piccolo / medio / grande", english: "Pequeño / mediano / grande" },
      { italian: "Che buono!", english: "¡Qué rico!" },
      { italian: "Posso assaggiare?", english: "¿Puedo probar?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buonasera! Vorrei un gelato.", translation: "¡Buenas noches! Quisiera un helado." },
      { speaker: "Gelataio", line: "Certo! Cono o coppetta?", translation: "¡Claro! ¿Cucurucho o copa?" },
      { speaker: "Cliente", line: "Cono, grazie. Posso assaggiare il pistacchio?", translation: "Cucurucho, gracias. ¿Puedo probar el pistacho?" },
      { speaker: "Gelataio", line: "Certo, ecco a lei.", translation: "Claro, aquí tiene." },
      { speaker: "Cliente", line: "Mmm, che buono! Pistacchio e cioccolato, per favore.", translation: "Mmm, ¡qué rico! Pistacho y chocolate, por favor." },
      { speaker: "Gelataio", line: "Piccolo, medio o grande?", translation: "¿Pequeño, mediano o grande?" },
      { speaker: "Cliente", line: "Medio. Quanto costa?", translation: "Mediano. ¿Cuánto es?" },
      { speaker: "Gelataio", line: "Due euro e cinquanta.", translation: "Dos euros cincuenta." },
    ],
    grammar: {
      title: "questo / quello — Este / Ese-Aquel",
      points: [
        { italian: "Questo gelato", english: "Este helado (cerca)" },
        { italian: "Quello lì", english: "Ese de allá (lejos)" },
        { italian: "Questo è buono", english: "Este está bueno" },
        { italian: "Qual è il migliore?", english: "¿Cuál es el mejor?" },
      ],
      note: "Usa \"questo\" para cosas cercanas y \"quello\" para cosas más lejanas — la misma lógica que este/ese en español.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a gelateria worker. Reply in Spanish. Use lesson 4 vocabulary. Be playful and warm, correct gently.",
  },
  {
    id: 5, title: "Pedir Indicaciones", subtitle: "Chiedere la Strada", free: false,
    keywords: [
      { italian: "Dov'è…?", english: "¿Dónde está…?" },
      { italian: "A destra", english: "A la derecha" },
      { italian: "A sinistra", english: "A la izquierda" },
      { italian: "Sempre dritto", english: "Todo recto" },
      { italian: "Vicino / lontano", english: "Cerca / lejos" },
      { italian: "Scusi!", english: "¡Perdone! (formal)" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Scusi! Dov'è il Colosseo?", translation: "¡Perdone! ¿Dónde está el Coliseo?" },
      { speaker: "Passante", line: "Allora… vada sempre dritto, poi a destra.", translation: "Vaya todo recto y luego gire a la derecha." },
      { speaker: "Turista", line: "È lontano?", translation: "¿Está lejos?" },
      { speaker: "Passante", line: "No, è vicino. Cinque minuti a piedi.", translation: "No, está cerca. Cinco minutos a pie." },
      { speaker: "Turista", line: "Grazie mille!", translation: "¡Muchas gracias!" },
      { speaker: "Passante", line: "Prego! Buona visita!", translation: "¡De nada! ¡Que disfrute la visita!" },
    ],
    grammar: {
      title: "C'è / Ci sono — Hay",
      points: [
        { italian: "C'è un autobus?", english: "¿Hay un autobús?" },
        { italian: "Ci sono taxi?", english: "¿Hay taxis?" },
        { italian: "C'è una fermata vicino?", english: "¿Hay una parada cerca?" },
        { italian: "Non c'è problema", english: "No hay problema" },
      ],
      note: "\"C'è\" y \"ci sono\" son tus expresiones clave para preguntar si algo existe o está disponible.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a local Roman. Reply in Spanish. Use lesson 5 vocabulary. Correct gently.",
  },
  {
    id: 6, title: "En el Aeropuerto", subtitle: "All'Aeroporto", free: false,
    keywords: [
      { italian: "Il volo", english: "El vuelo" },
      { italian: "Il passaporto", english: "El pasaporte" },
      { italian: "Il bagaglio", english: "El equipaje" },
      { italian: "Quanti bagagli hai?", english: "¿Cuántas maletas tienes?" },
      { italian: "Il gate", english: "La puerta de embarque" },
      { italian: "In ritardo / in orario", english: "Con retraso / a tiempo" },
    ],
    dialogue: [
      { speaker: "Agente", line: "Buongiorno! Il passaporto, per favore.", translation: "¡Buenos días! Su pasaporte, por favor." },
      { speaker: "Passeggero", line: "Eccolo. Ho anche un bagaglio da imbarcare.", translation: "Aquí tiene. También tengo una maleta para facturar." },
      { speaker: "Agente", line: "Quanti bagagli ha?", translation: "¿Cuántas maletas tiene?" },
      { speaker: "Passeggero", line: "Solo uno. Il volo è in orario?", translation: "Solo una. ¿El vuelo sale a tiempo?" },
      { speaker: "Agente", line: "Sì, parte alle undici. Gate B7.", translation: "Sí, sale a las once. Puerta B7." },
      { speaker: "Passeggero", line: "Grazie mille!", translation: "¡Muchas gracias!" },
    ],
    grammar: {
      title: "Avere — El verbo «Tener»",
      points: [
        { italian: "Io ho", english: "Yo tengo" },
        { italian: "Tu hai", english: "Tú tienes (informal)" },
        { italian: "Lei ha", english: "Usted tiene (formal) / Ella tiene" },
        { italian: "Lui ha", english: "Él tiene" },
        { italian: "Noi abbiamo", english: "Nosotros tenemos" },
        { italian: "Voi avete", english: "Vosotros tenéis" },
        { italian: "Loro hanno", english: "Ellos tienen" },
      ],
      note: "\"Avere\" es uno de los dos verbos más importantes del italiano. También se usa para la edad: \"ho trent'anni\" = tengo treinta años.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing an airport check-in agent. Reply in Spanish. Use lesson 6 vocabulary. Correct gently.",
  },
  {
    id: 7, title: "En el Restaurante", subtitle: "Al Ristorante", free: false,
    keywords: [
      { italian: "Un tavolo per due", english: "Una mesa para dos" },
      { italian: "Il menù", english: "La carta" },
      { italian: "Il primo / il secondo", english: "El primer / segundo plato" },
      { italian: "Sono vegetariano/a", english: "Soy vegetariano/a" },
      { italian: "È compreso?", english: "¿Está incluido?" },
      { italian: "Il coperto", english: "El cubierto" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buonasera! Un tavolo per due, per favore.", translation: "¡Buenas noches! Una mesa para dos, por favor." },
      { speaker: "Cameriere", line: "Certo, prego. Ecco il menù.", translation: "Claro. Aquí tiene la carta." },
      { speaker: "Cliente", line: "Grazie. Sono vegetariana — cosa consiglia?", translation: "Gracias. Soy vegetariana — ¿qué recomienda?" },
      { speaker: "Cameriere", line: "Ottime le tagliatelle ai funghi!", translation: "¡Los tallarines con setas están excelentes!" },
      { speaker: "Cliente", line: "Perfetto. E il coperto è compreso?", translation: "Perfecto. ¿El cubierto está incluido?" },
      { speaker: "Cameriere", line: "Sì, è già incluso. Buon appetito!", translation: "Sí, ya está incluido. ¡Buen provecho!" },
    ],
    grammar: {
      title: "Mi piace / Mi piacciono — Me gusta",
      points: [
        { italian: "Mi piace la pasta", english: "Me gusta la pasta" },
        { italian: "Mi piacciono i funghi", english: "Me gustan los champiñones (plural)" },
        { italian: "Non mi piace", english: "No me gusta" },
        { italian: "Mi piace molto", english: "Me gusta mucho" },
      ],
      note: "\"Piacere\" funciona al revés — dices \"a mí me place\". Usa \"piace\" para una cosa, \"piacciono\" para varias.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a restaurant waiter. Reply in Spanish. Use lesson 7 vocabulary. Correct gently.",
  },
  {
    id: 8, title: "De Compras", subtitle: "Fare Shopping", free: false,
    keywords: [
      { italian: "Posso provarlo?", english: "¿Puedo probármelo?" },
      { italian: "Che taglia?", english: "¿Qué talla?" },
      { italian: "È troppo caro", english: "Es demasiado caro" },
      { italian: "C'è lo sconto?", english: "¿Hay descuento?" },
      { italian: "Lo prendo", english: "Me lo llevo" },
      { italian: "Accettate carte di credito?", english: "¿Aceptan tarjetas de crédito?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Posso provare questa giacca?", translation: "¡Buenos días! ¿Puedo probarme esta chaqueta?" },
      { speaker: "Commessa", line: "Certo! Che taglia porta?", translation: "¡Claro! ¿Qué talla usa?" },
      { speaker: "Cliente", line: "La media, grazie.", translation: "La talla media, gracias." },
      { speaker: "Cliente", line: "Hmm… quanto costa?", translation: "Hmm… ¿cuánto cuesta?" },
      { speaker: "Commessa", line: "Centoventi euro. C'è il 20% di sconto oggi!", translation: "Ciento veinte euros. ¡Hay un 20% de descuento hoy!" },
      { speaker: "Cliente", line: "Perfetto, lo prendo! Accettate carte?", translation: "Perfecto, ¡me la llevo! ¿Aceptan tarjetas?" },
      { speaker: "Commessa", line: "Sì, certo.", translation: "Sí, claro." },
    ],
    grammar: {
      title: "Potere — Poder",
      points: [
        { italian: "Posso provarlo?", english: "¿Puedo probármelo?" },
        { italian: "Puoi aiutarmi?", english: "¿Puedes ayudarme?" },
        { italian: "Possiamo pagare con la carta?", english: "¿Podemos pagar con tarjeta?" },
      ],
      note: "\"Potere\" es un verbo modal — se combina con el infinitivo. Es tu clave para pedir permiso y expresar capacidad.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a shop assistant. Reply in Spanish. Use lesson 8 vocabulary. Correct gently.",
  },
  {
    id: 9, title: "En el Hotel", subtitle: "In Albergo", free: false,
    keywords: [
      { italian: "Ho una prenotazione", english: "Tengo una reserva" },
      { italian: "La camera", english: "La habitación" },
      { italian: "A che ora è il check-out?", english: "¿A qué hora es el check-out?" },
      { italian: "La colazione è inclusa?", english: "¿El desayuno está incluido?" },
      { italian: "C'è il wifi?", english: "¿Hay wifi?" },
      { italian: "La chiave", english: "La llave" },
    ],
    dialogue: [
      { speaker: "Ospite", line: "Buonasera! Ho una prenotazione. Mi chiamo Rossi.", translation: "¡Buenas noches! Tengo una reserva. Me llamo Rossi." },
      { speaker: "Receptionist", line: "Benvenuto! Sì, camera doppia per tre notti.", translation: "¡Bienvenido! Sí, habitación doble para tres noches." },
      { speaker: "Ospite", line: "Perfetto. La colazione è inclusa?", translation: "Perfecto. ¿El desayuno está incluido?" },
      { speaker: "Receptionist", line: "Sì, dalle sette alle dieci. C'è anche il wifi gratuito.", translation: "Sí, de siete a diez. También hay wifi gratuito." },
      { speaker: "Ospite", line: "Ottimo. A che ora è il check-out?", translation: "Excelente. ¿A qué hora es el check-out?" },
      { speaker: "Receptionist", line: "Alle undici. Ecco la sua chiave. Buona permanenza!", translation: "A las once. Aquí tiene su llave. ¡Que disfrute su estancia!" },
    ],
    grammar: {
      title: "Preposiciones: a, di, da, in",
      points: [
        { italian: "Sono a Roma", english: "Estoy en Roma (ubicación)" },
        { italian: "Vengo da Londra", english: "Vengo de Londres (origen)" },
        { italian: "Vado in Italia", english: "Voy a Italia (países)" },
        { italian: "La chiave di Maria", english: "La llave de Maria (posesión)" },
      ],
      note: "Las preposiciones italianas no siempre coinciden con las españolas. \"In\" se usa con países, \"a\" con ciudades.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a hotel receptionist. Reply in Spanish. Use lesson 9 vocabulary. Correct gently.",
  },
  {
    id: 10, title: "En el Tren", subtitle: "Sul Treno", free: false,
    keywords: [
      { italian: "Un biglietto per…", english: "Un billete para…" },
      { italian: "Andata e ritorno", english: "Ida y vuelta" },
      { italian: "Il binario", english: "El andén" },
      { italian: "È occupato?", english: "¿Está ocupado este asiento?" },
      { italian: "A che ora arriva?", english: "¿A qué hora llega?" },
      { italian: "Il treno è in ritardo", english: "El tren lleva retraso" },
    ],
    dialogue: [
      { speaker: "Viaggiatore", line: "Buongiorno! Un biglietto per Venezia, per favore.", translation: "¡Buenos días! Un billete para Venecia, por favor." },
      { speaker: "Bigliettaio", line: "Andata e ritorno?", translation: "¿Ida y vuelta?" },
      { speaker: "Viaggiatore", line: "Solo andata. A che ora arriva?", translation: "Solo ida. ¿A qué hora llega?" },
      { speaker: "Bigliettaio", line: "Alle tredici e venti. Binario 4.", translation: "A las trece veinte. Andén 4." },
      { speaker: "Viaggiatore", line: "Grazie. È occupato questo posto?", translation: "Gracias. ¿Está ocupado este asiento?" },
      { speaker: "Passeggero", line: "No, si accomodi!", translation: "No, ¡siéntese por favor!" },
    ],
    grammar: {
      title: "La hora",
      points: [
        { italian: "Sono le tre", english: "Son las tres" },
        { italian: "È mezzogiorno", english: "Es mediodía" },
        { italian: "Alle otto e mezza", english: "A las ocho y media" },
        { italian: "A che ora?", english: "¿A qué hora?" },
      ],
      note: "Los italianos usan el reloj de 24h para el transporte. \"Sono le tredici\" = 1 PM. Se usa \"sono le\" excepto para la 1: \"è l'una\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a train station ticket agent. Reply in Spanish. Use lesson 10 vocabulary. Correct gently.",
  },
  {
    id: 11, title: "En el Mercado", subtitle: "Al Mercato", free: false,
    keywords: [
      { italian: "Quanto pesa?", english: "¿Cuánto pesa?" },
      { italian: "Un chilo di…", english: "Un kilo de…" },
      { italian: "Fresco / di stagione", english: "Fresco / de temporada" },
      { italian: "Me ne dà mezzo chilo", english: "Deme medio kilo" },
      { italian: "Basta così", english: "Es todo / ya está" },
      { italian: "Il resto", english: "El cambio" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Questi pomodori sono freschi?", translation: "¡Buenos días! ¿Están frescos estos tomates?" },
      { speaker: "Venditore", line: "Freschissimi! Di stagione. Quanti ne vuole?", translation: "¡Fresquísimos! De temporada. ¿Cuántos quiere?" },
      { speaker: "Cliente", line: "Me ne dà un chilo, per favore.", translation: "Deme un kilo, por favor." },
      { speaker: "Venditore", line: "Basta così?", translation: "¿Es todo?" },
      { speaker: "Cliente", line: "Sì, grazie. Ecco cinque euro.", translation: "Sí, gracias. Aquí tiene cinco euros." },
      { speaker: "Venditore", line: "Ecco il resto. Grazie, a presto!", translation: "Aquí tiene el cambio. ¡Gracias, hasta pronto!" },
    ],
    grammar: {
      title: "Ne — El pronombre partitivo",
      points: [
        { italian: "Ne voglio un chilo", english: "Quiero un kilo" },
        { italian: "Me ne dà due?", english: "¿Me puede dar dos?" },
        { italian: "Non ne ho", english: "No tengo" },
        { italian: "Quanti ne vuole?", english: "¿Cuántos quiere?" },
      ],
      note: "\"Ne\" reemplaza un nombre con una cantidad — significa algo como \"de ello\". Los italianos lo usan constantemente.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a market vendor. Reply in Spanish. Use lesson 11 vocabulary. Correct gently.",
  },
  {
    id: 12, title: "Emergencias y Salud", subtitle: "Emergenze e Salute", free: false,
    keywords: [
      { italian: "Aiuto!", english: "¡Socorro!" },
      { italian: "Ho bisogno di un medico", english: "Necesito un médico" },
      { italian: "Mi fa male…", english: "… me duele" },
      { italian: "Chiami un'ambulanza!", english: "¡Llame una ambulancia!" },
      { italian: "La farmacia", english: "La farmacia" },
      { italian: "Sono allergico/a a…", english: "Soy alérgico/a a…" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Scusi! Ho bisogno di aiuto.", translation: "¡Perdone! Necesito ayuda." },
      { speaker: "Passante", line: "Cosa succede?", translation: "¿Qué pasa?" },
      { speaker: "Turista", line: "Mi fa molto male la testa. Ho la febbre.", translation: "Me duele mucho la cabeza. Tengo fiebre." },
      { speaker: "Passante", line: "C'è una farmacia qui vicino.", translation: "Hay una farmacia aquí cerca." },
      { speaker: "Turista", line: "Sono allergico alla penicillina.", translation: "Soy alérgico a la penicilina." },
      { speaker: "Passante", line: "Lo dica al farmacista. Venga, l'accompagno.", translation: "Dígaselo al farmacéutico. Venga, le acompaño." },
    ],
    grammar: {
      title: "Mi fa male — Expresar dolor",
      points: [
        { italian: "Mi fa male la testa", english: "Me duele la cabeza" },
        { italian: "Mi fa male lo stomaco", english: "Me duele el estómago" },
        { italian: "Mi fanno male i piedi", english: "Me duelen los pies (plural)" },
        { italian: "Ho la febbre", english: "Tengo fiebre" },
      ],
      note: "\"Mi fa male\" significa \"me duele\". Usa \"fa male\" para una parte del cuerpo, \"fanno male\" para varias.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor helping practice emergency vocabulary. Reply in Spanish. Correct gently.",
  },
  {
    id: 13, title: "En la Farmacia", subtitle: "In Farmacia", free: false,
    keywords: [
      { italian: "Ho bisogno di…", english: "Necesito…" },
      { italian: "Una ricetta", english: "Una receta" },
      { italian: "Il mal di testa", english: "Dolor de cabeza" },
      { italian: "La tosse", english: "Tos" },
      { italian: "Qualcosa per…", english: "Algo para…" },
      { italian: "Quante volte al giorno?", english: "¿Cuántas veces al día?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno. Ho bisogno di qualcosa per il mal di testa.", translation: "Buenos días. Necesito algo para el dolor de cabeza." },
      { speaker: "Farmacista", line: "Ha la ricetta?", translation: "¿Tiene receta?" },
      { speaker: "Cliente", line: "No, è senza ricetta.", translation: "No, es sin receta." },
      { speaker: "Farmacista", line: "Allora le do queste compresse. Due volte al giorno.", translation: "Entonces le doy estos comprimidos. Dos veces al día." },
      { speaker: "Cliente", line: "Grazie. Ho anche la tosse.", translation: "Gracias. También tengo tos." },
      { speaker: "Farmacista", line: "Prenda questo sciroppo, tre volte al giorno dopo i pasti.", translation: "Tome este jarabe, tres veces al día después de las comidas." },
    ],
    grammar: {
      title: "Imperativo — Dar instrucciones",
      points: [
        { italian: "Prenda queste pillole", english: "Tome estas pastillas (orden formal)" },
        { italian: "Beva molta acqua", english: "Beba mucha agua" },
        { italian: "Riposi a casa", english: "Descanse en casa" },
        { italian: "Torni domani", english: "Vuelva mañana" },
      ],
      note: "El imperativo formal (forma Lei) lo usan los profesionales. Suena como la tercera persona del singular — una orden cortés.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a pharmacist. Reply in Spanish. Use lesson 13 vocabulary. Correct gently.",
  },
  {
    id: 14, title: "Hablar por Teléfono", subtitle: "Al Telefono", free: false,
    keywords: [
      { italian: "Pronto!", english: "¡Diga! (al contestar)" },
      { italian: "Con chi parlo?", english: "¿Con quién hablo?" },
      { italian: "Posso parlare con…?", english: "¿Puedo hablar con…?" },
      { italian: "Un momento", english: "Un momento" },
      { italian: "Richiamare", english: "Volver a llamar" },
      { italian: "È occupato", english: "La línea está ocupada" },
    ],
    dialogue: [
      { speaker: "A", line: "Pronto?", translation: "¿Diga?" },
      { speaker: "B", line: "Buongiorno! Posso parlare con la signora Bianchi?", translation: "¡Buenos días! ¿Puedo hablar con la señora Bianchi?" },
      { speaker: "A", line: "Sono io. Con chi parlo?", translation: "Soy yo. ¿Con quién hablo?" },
      { speaker: "B", line: "Sono Marco Rossi, chiamo per la prenotazione.", translation: "Soy Marco Rossi, llamo por la reserva." },
      { speaker: "A", line: "Mi dispiace, la linea è occupata. Può richiamare?", translation: "Lo siento, la línea está ocupada. ¿Puede volver a llamar?" },
      { speaker: "B", line: "Certo, richiamo più tardi. Grazie!", translation: "Claro, volveré a llamar más tarde. ¡Gracias!" },
    ],
    grammar: {
      title: "Potere + Infinitivo — Pedir permiso",
      points: [
        { italian: "Posso richiamare?", english: "¿Puedo volver a llamar?" },
        { italian: "Può aspettare?", english: "¿Puede esperar? (formal)" },
        { italian: "Non posso sentire", english: "No puedo oír" },
      ],
      note: "En el teléfono, los italianos siempre dicen \"Pronto!\" al contestar — significa literalmente \"listo\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing phone calls. Reply in Spanish. Use lesson 14 vocabulary. Correct gently.",
  },
  {
    id: 15, title: "En la Oficina de Correos", subtitle: "All'Ufficio Postale", free: false,
    keywords: [
      { italian: "Spedire un pacco", english: "Enviar un paquete" },
      { italian: "Una lettera / una busta", english: "Una carta / un sobre" },
      { italian: "Per via aerea", english: "Por correo aéreo" },
      { italian: "Quanto ci vuole?", english: "¿Cuánto tarda?" },
      { italian: "Il francobollo", english: "El sello" },
      { italian: "Raccomandata", english: "Correo certificado" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Vorrei spedire questo pacco in Inghilterra.", translation: "¡Buenos días! Quisiera enviar este paquete a Inglaterra." },
      { speaker: "Impiegato", line: "Per via aerea o normale?", translation: "¿Por correo aéreo o normal?" },
      { speaker: "Cliente", line: "Aerea. Quanto ci vuole?", translation: "Aéreo. ¿Cuánto tarda?" },
      { speaker: "Impiegato", line: "Circa cinque giorni lavorativi.", translation: "Unos cinco días laborables." },
      { speaker: "Cliente", line: "Va bene. E vorrei anche tre francobolli.", translation: "Muy bien. Y también quisiera tres sellos." },
    ],
    grammar: {
      title: "Ci vuole / Ci vogliono — Tardarse / Necesitar",
      points: [
        { italian: "Ci vuole un'ora", english: "Tarda una hora" },
        { italian: "Ci vogliono tre giorni", english: "Tarda tres días" },
        { italian: "Quanto ci vuole?", english: "¿Cuánto tarda?" },
        { italian: "Ci vuole pazienza!", english: "¡Hace falta paciencia!" },
      ],
      note: "\"Ci vuole\" es perfectamente práctico — úsalo siempre que quieras decir cuánto tiempo tarda algo.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a post office clerk. Reply in Spanish. Use lesson 15 vocabulary. Correct gently.",
  },
  {
    id: 16, title: "Alquilar un Coche", subtitle: "Noleggiare un'Auto", free: false,
    keywords: [
      { italian: "Noleggiare un'auto", english: "Alquilar un coche" },
      { italian: "La patente", english: "El carné de conducir" },
      { italian: "Il pieno", english: "Depósito lleno" },
      { italian: "L'assicurazione", english: "El seguro" },
      { italian: "Quanti chilometri?", english: "¿Cuántos kilómetros?" },
      { italian: "Riconsegnare", english: "Devolver (el coche)" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Vorrei noleggiare un'auto per tre giorni.", translation: "¡Buenos días! Quisiera alquilar un coche por tres días." },
      { speaker: "Agente", line: "Certo. Ha la patente con sé?", translation: "Claro. ¿Tiene el carné consigo?" },
      { speaker: "Cliente", line: "Sì, eccola. L'assicurazione è inclusa?", translation: "Sí, aquí está. ¿El seguro está incluido?" },
      { speaker: "Agente", line: "Sì, quella base è inclusa. Vuole quella completa?", translation: "Sí, el básico está incluido. ¿Quiere el completo?" },
      { speaker: "Cliente", line: "Sì, meglio. I chilometri sono illimitati?", translation: "Sí, mejor. ¿Los kilómetros son ilimitados?" },
      { speaker: "Agente", line: "Sì, nessun limite.", translation: "Sí, sin límite." },
    ],
    grammar: {
      title: "Dovere — Deber / Tener que",
      points: [
        { italian: "Devo riconsegnare l'auto", english: "Debo devolver el coche" },
        { italian: "Deve avere la patente", english: "Debe tener carné (formal)" },
        { italian: "Dobbiamo fare il pieno", english: "Tenemos que llenar el depósito" },
      ],
      note: "\"Dovere\" expresa obligación — combínalo con un infinitivo. Uno de los tres verbos modales clave: potere, volere, dovere.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a car rental agent. Reply in Spanish. Use lesson 16 vocabulary. Correct gently.",
  },
  {
    id: 17, title: "En la Playa", subtitle: "In Spiaggia", free: false,
    keywords: [
      { italian: "Un ombrellone", english: "Una sombrilla de playa" },
      { italian: "Una sdraio", english: "Una tumbona" },
      { italian: "La crema solare", english: "La crema solar" },
      { italian: "Il mare è mosso", english: "El mar está agitado" },
      { italian: "Fare il bagno", english: "Bañarse" },
      { italian: "Che caldo!", english: "¡Qué calor!" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Buongiorno! Vorrei un ombrellone e due sdraio.", translation: "¡Buenos días! Quisiera una sombrilla y dos tumbonas." },
      { speaker: "Bagnino", line: "Certo! Prima fila o seconda?", translation: "¡Claro! ¿Primera fila o segunda?" },
      { speaker: "Turista", line: "Seconda va bene. Si può fare il bagno?", translation: "La segunda está bien. ¿Se puede bañar?" },
      { speaker: "Bagnino", line: "Sì, il mare è calmo oggi. Che caldo!", translation: "Sí, el mar está tranquilo hoy. ¡Qué calor!" },
    ],
    grammar: {
      title: "Fare — El verbo «Hacer»",
      points: [
        { italian: "Faccio una passeggiata", english: "Doy un paseo" },
        { italian: "Fa caldo / fa freddo", english: "Hace calor / hace frío (tiempo)" },
        { italian: "Fai il bagno?", english: "¿Te estás bañando?" },
        { italian: "Fanno un castello di sabbia", english: "Hacen un castillo de arena" },
      ],
      note: "\"Fare\" es uno de los verbos italianos más versátiles — aparece en docenas de expresiones fijas.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a beach attendant. Reply in Spanish. Use lesson 17 vocabulary. Correct gently.",
  },
  {
    id: 18, title: "Hablar de la Familia", subtitle: "La Famiglia", free: false,
    keywords: [
      { italian: "Il marito / la moglie", english: "Marido / mujer" },
      { italian: "I figli", english: "Los hijos" },
      { italian: "Il fratello / la sorella", english: "Hermano / hermana" },
      { italian: "I genitori", english: "Los padres" },
      { italian: "Sei sposato/a?", english: "¿Estás casado/a?" },
      { italian: "Hai figli?", english: "¿Tienes hijos?" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei sposato?", translation: "¿Estás casado?" },
      { speaker: "B", line: "Sì, ho una moglie e due figli. E tu?", translation: "Sí, tengo una mujer y dos hijos. ¿Y tú?" },
      { speaker: "A", line: "Sono fidanzata. Ci sposiamo l'anno prossimo!", translation: "Estoy prometida. ¡Nos casamos el año que viene!" },
      { speaker: "B", line: "Congratulazioni! Hai fratelli o sorelle?", translation: "¡Enhorabuena! ¿Tienes hermanos o hermanas?" },
      { speaker: "A", line: "Ho una sorella. I miei genitori vivono a Napoli.", translation: "Tengo una hermana. Mis padres viven en Nápoles." },
    ],
    grammar: {
      title: "Posesivos — Mi, tu, su",
      points: [
        { italian: "Il mio gatto", english: "Mi gato" },
        { italian: "Il tuo gelato", english: "Tu helado" },
        { italian: "La sua mamma", english: "Su mamá" },
        { italian: "I nostri vicini", english: "Nuestros vecinos" },
      ],
      note: "Los posesivos italianos concuerdan en género y número con el sustantivo, no con el poseedor.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a conversation about family. Reply in Spanish. Use lesson 18 vocabulary. Correct gently.",
  },
  {
    id: 19, title: "En el Médico", subtitle: "Dal Medico", free: false,
    keywords: [
      { italian: "Ho un appuntamento", english: "Tengo una cita" },
      { italian: "Da quanto tempo?", english: "¿Desde cuándo / cuánto tiempo?" },
      { italian: "Ho la nausea", english: "Tengo náuseas" },
      { italian: "La pressione", english: "La presión arterial" },
      { italian: "Fare una visita", english: "Hacer una consulta" },
      { italian: "La diagnosi", english: "El diagnóstico" },
    ],
    dialogue: [
      { speaker: "Paziente", line: "Buongiorno, ho un appuntamento con il dottor Marini.", translation: "Buenos días, tengo una cita con el doctor Marini." },
      { speaker: "Dottore", line: "Da quanto tempo ha questi sintomi?", translation: "¿Cuánto tiempo lleva con estos síntomas?" },
      { speaker: "Paziente", line: "Da due giorni. Ho anche un po' di febbre.", translation: "Dos días. También tengo un poco de fiebre." },
      { speaker: "Dottore", line: "Le misuro la pressione. Respiri profondamente.", translation: "Le voy a tomar la presión. Respire hondo." },
      { speaker: "Dottore", line: "Non è grave. Le scrivo una ricetta.", translation: "No es grave. Le voy a recetar algo." },
    ],
    grammar: {
      title: "Da — Desde / Hace (tiempo)",
      points: [
        { italian: "Da due giorni", english: "Desde hace dos días (en curso)" },
        { italian: "Vivo qui da un anno", english: "Vivo aquí desde hace un año" },
        { italian: "Da stamattina", english: "Desde esta mañana" },
        { italian: "Da quanto tempo?", english: "¿Desde cuándo?" },
      ],
      note: "En italiano, \"da\" + presente describe algo que lleva ocurriendo desde el pasado. En español usamos \"llevar + gerundio\" o \"desde hace\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a doctor. Reply in Spanish. Use lesson 19 vocabulary. Correct gently.",
  },
  {
    id: 20, title: "Salir de Noche", subtitle: "Uscire la Sera", free: false,
    keywords: [
      { italian: "Andiamo a ballare?", english: "¿Vamos a bailar?" },
      { italian: "Un locale", english: "Un local / una discoteca / un bar" },
      { italian: "C'è la fila", english: "Hay cola" },
      { italian: "Offro io", english: "Invito yo" },
      { italian: "Fare tardi", english: "Quedarse hasta tarde" },
      { italian: "Che serata!", english: "¡Qué noche!" },
    ],
    dialogue: [
      { speaker: "A", line: "Allora, andiamo a ballare stasera?", translation: "Entonces, ¿vamos a bailar esta noche?" },
      { speaker: "B", line: "Sì! Conosco un bel locale in centro.", translation: "¡Sí! Conozco un buen local en el centro." },
      { speaker: "A", line: "C'è la fila di solito?", translation: "¿Suele haber cola?" },
      { speaker: "B", line: "A volte sì, ma entriamo con la lista.", translation: "A veces sí, pero entramos con la lista." },
      { speaker: "B", line: "Un aperitivo — offro io!", translation: "¡Un aperitivo — invito yo!" },
    ],
    grammar: {
      title: "Andare — Ir (+ lugares)",
      points: [
        { italian: "Vado al bar", english: "Voy al bar" },
        { italian: "Va bene!", english: "¡Está bien! / ¡De acuerdo!" },
        { italian: "Andiamo a ballare", english: "Vamos a bailar" },
        { italian: "Vai a casa?", english: "¿Te vas a casa?" },
      ],
      note: "\"Andiamo\" (vamos) es una de las palabras más útiles de la vida social italiana. \"Va bene\" se usa constantemente.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend planning a night out. Reply in Spanish. Use lesson 20 vocabulary. Correct gently.",
  },
  {
    id: 21, title: "Comida y Cocina", subtitle: "Cibo e Cucina", free: false,
    keywords: [
      { italian: "La ricetta", english: "La receta" },
      { italian: "Gli ingredienti", english: "Los ingredientes" },
      { italian: "Cuocere / cucinare", english: "Cocinar" },
      { italian: "Aggiungere", english: "Añadir" },
      { italian: "Mescolare", english: "Mezclar" },
      { italian: "È pronto!", english: "¡Está listo!" },
    ],
    dialogue: [
      { speaker: "A", line: "Stai cucinando? Che profumo!", translation: "¿Estás cocinando? ¡Qué buena pinta!" },
      { speaker: "B", line: "Sto facendo la pasta al pomodoro. Vuoi la ricetta?", translation: "Estoy haciendo pasta con tomate. ¿Quieres la receta?" },
      { speaker: "A", line: "Sì! Quali ingredienti usi?", translation: "¡Sí! ¿Qué ingredientes usas?" },
      { speaker: "B", line: "Pomodori freschi, aglio, basilico e olio d'oliva.", translation: "Tomates frescos, ajo, albahaca y aceite de oliva." },
      { speaker: "A", line: "Aggiungi il sale, mescola e aspetta.", translation: "Añade la sal, mezcla y espera." },
    ],
    grammar: {
      title: "Stare + Gerundio — Presente continuo",
      points: [
        { italian: "Sto cucinando", english: "Estoy cocinando (ahora mismo)" },
        { italian: "Sta mangiando", english: "Él/Ella está comiendo" },
        { italian: "Stiamo aspettando", english: "Estamos esperando" },
        { italian: "Cosa state facendo?", english: "¿Qué estáis haciendo?" },
      ],
      note: "El italiano tiene un presente continuo formado con \"stare\" + gerundio (-ando/-endo).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend cooking. Reply in Spanish. Use lesson 21 vocabulary. Correct gently.",
  },
  {
    id: 22, title: "En el Banco", subtitle: "In Banca", free: false,
    keywords: [
      { italian: "Aprire un conto", english: "Abrir una cuenta" },
      { italian: "Il bancomat", english: "El cajero automático / la tarjeta de débito" },
      { italian: "Prelevare", english: "Sacar dinero" },
      { italian: "Il tasso di cambio", english: "El tipo de cambio" },
      { italian: "Fare un bonifico", english: "Hacer una transferencia" },
      { italian: "Lo sportello", english: "La ventanilla" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno. Vorrei prelevare dei contanti.", translation: "Buenos días. Quisiera sacar efectivo." },
      { speaker: "Impiegato", line: "Si accomodi allo sportello tre.", translation: "Por favor, diríjase a la ventanilla tres." },
      { speaker: "Cliente", line: "Qual è il tasso di cambio oggi?", translation: "¿Cuál es el tipo de cambio hoy?" },
      { speaker: "Cliente", line: "Posso anche fare un bonifico?", translation: "¿También puedo hacer una transferencia?" },
      { speaker: "Impiegato", line: "Certo. Ha il codice IBAN del destinatario?", translation: "Claro. ¿Tiene el código IBAN del destinatario?" },
    ],
    grammar: {
      title: "Los números",
      points: [
        { italian: "Uno…dieci", english: "1–10" },
        { italian: "Undici…venti", english: "11–20" },
        { italian: "Cento / mille / un milione", english: "100 / 1.000 / 1.000.000" },
        { italian: "Virgola", english: "Punto decimal (coma en italiano)" },
      ],
      note: "En italiano, los decimales usan coma: \"1,17\" = uno virgola diciassette. Los miles usan punto. ¡Lo contrario que en muchos países!",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a bank teller. Reply in Spanish. Use lesson 22 vocabulary. Correct gently.",
  },
  {
    id: 23, title: "Hacer Planes", subtitle: "Fare Programmi", free: false,
    keywords: [
      { italian: "Sei libero/a?", english: "¿Estás libre?" },
      { italian: "Che ne dici di…?", english: "¿Qué te parece…?" },
      { italian: "Mi va!", english: "¡Me apetece! / ¡Me parece bien!" },
      { italian: "Ci vediamo", english: "Nos vemos" },
      { italian: "Rimandare", english: "Aplazar" },
      { italian: "Non vedo l'ora!", english: "¡Tengo muchas ganas!" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei libera sabato?", translation: "¿Estás libre el sábado?" },
      { speaker: "B", line: "Sì! Che ne dici di andare al museo?", translation: "¡Sí! ¿Qué te parece ir al museo?" },
      { speaker: "A", line: "Mi va! A che ora ci vediamo?", translation: "¡Me parece bien! ¿A qué hora quedamos?" },
      { speaker: "B", line: "Alle dieci davanti all'ingresso?", translation: "¿A las diez delante de la entrada?" },
      { speaker: "A", line: "Perfetto. Non vedo l'ora!", translation: "Perfecto. ¡Tengo muchas ganas!" },
    ],
    grammar: {
      title: "Futuro — Rápido y fácil",
      points: [
        { italian: "Andrò al museo", english: "Iré al museo" },
        { italian: "Sarà divertente", english: "Será divertido" },
        { italian: "Cosa farai?", english: "¿Qué harás?" },
        { italian: "Ci vediamo domani", english: "Nos vemos mañana (presente para futuro próximo)" },
      ],
      note: "Los italianos suelen usar el presente para planes cercanos. \"Domani vado al cinema\" es más natural que el futuro en el habla cotidiana.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend making plans. Reply in Spanish. Use lesson 23 vocabulary. Correct gently.",
  },
  {
    id: 24, title: "Hablar del Tiempo", subtitle: "Il Tempo", free: false,
    keywords: [
      { italian: "Che tempo fa?", english: "¿Qué tiempo hace?" },
      { italian: "Piove / nevica", english: "Llueve / nieva" },
      { italian: "C'è il sole", english: "Hay sol" },
      { italian: "Afoso", english: "Húmedo / bochornoso" },
      { italian: "Le previsioni", english: "La previsión" },
      { italian: "Portare un ombrello", english: "Llevar un paraguas" },
    ],
    dialogue: [
      { speaker: "A", line: "Che tempo fa oggi?", translation: "¿Qué tiempo hace hoy?" },
      { speaker: "B", line: "È nuvoloso stamattina, ma nel pomeriggio c'è il sole.", translation: "Esta mañana está nublado, pero por la tarde hay sol." },
      { speaker: "A", line: "E domani? Hai visto le previsioni?", translation: "¿Y mañana? ¿Has visto la previsión?" },
      { speaker: "B", line: "Sì, piove di mattina. Porta l'ombrello!", translation: "Sí, llueve por la mañana. ¡Lleva un paraguas!" },
    ],
    grammar: {
      title: "Imperfecto — El pasado (hábitos y descripciones)",
      points: [
        { italian: "Volevo andare al mare", english: "Quería ir a la playa" },
        { italian: "Faceva caldo", english: "Hacía calor (descripción en el pasado)" },
        { italian: "Quando ero piccolo…", english: "Cuando era joven…" },
        { italian: "Di solito prendevo…", english: "Solía coger…" },
      ],
      note: "El imperfecto se usa para hábitos pasados, descripciones y estados prolongados.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor talking about the weather. Reply in Spanish. Use lesson 24 vocabulary. Correct gently.",
  },
  {
    id: 25, title: "En el Parque", subtitle: "Al Parco", free: false,
    keywords: [
      { italian: "Il fiore", english: "La flor" },
      { italian: "L'albero", english: "El árbol" },
      { italian: "Il cane", english: "El perro" },
      { italian: "La panchina", english: "El banco" },
      { italian: "Bello / bella", english: "Bonito/a" },
      { italian: "Guarda!", english: "¡Mira!" },
    ],
    dialogue: [
      { speaker: "A", line: "Guarda quel cane!", translation: "¡Mira ese perro!" },
      { speaker: "B", line: "Che bello! È tuo?", translation: "¡Qué bonito! ¿Es tuyo?" },
      { speaker: "A", line: "No, ma vorrei averne uno.", translation: "No, pero me encantaría tener uno." },
      { speaker: "B", line: "Mi piace quel fiore rosso là.", translation: "Me gusta esa flor roja de allí." },
      { speaker: "A", line: "Sediamoci sulla panchina?", translation: "¿Nos sentamos en el banco?" },
    ],
    grammar: {
      title: "I Colori — Los colores",
      points: [
        { italian: "Rosso / rossa", english: "Rojo / roja (m/f)" },
        { italian: "Verde", english: "Verde" },
        { italian: "Blu", english: "Azul (invariable)" },
        { italian: "Giallo / gialla", english: "Amarillo / amarilla (m/f)" },
        { italian: "Un fiore rosso", english: "Una flor roja (el adjetivo sigue al nombre)" },
      ],
      note: "En italiano, los colores son adjetivos y concuerdan con el sustantivo: una rosa rossa. Blu y rosa nunca cambian.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor taking a walk in an Italian park. Reply in Spanish. Practice colours and park vocabulary. Correct gently.",
  },
  {
    id: 26, title: "Hablar de las Personas", subtitle: "Parlare delle Persone", free: false,
    keywords: [
      { italian: "Alto / basso", english: "Alto / bajo" },
      { italian: "Magro / robusto", english: "Delgado / robusto" },
      { italian: "Simpatico / antipatico", english: "Simpático / antipático" },
      { italian: "Timido / estroverso", english: "Tímido / extrovertido" },
      { italian: "I capelli", english: "El pelo" },
      { italian: "Gli occhi", english: "Los ojos" },
    ],
    dialogue: [
      { speaker: "A", line: "Conosci Marco?", translation: "¿Conoces a Marco?" },
      { speaker: "B", line: "Sì! È alto e molto simpatico.", translation: "¡Sí! Es alto y muy simpático." },
      { speaker: "A", line: "Ha i capelli scuri, vero?", translation: "Tiene el pelo oscuro, ¿verdad?" },
      { speaker: "B", line: "Sì, e gli occhi verdi.", translation: "Sí, y los ojos verdes." },
    ],
    grammar: {
      title: "Essere + Adjetivos para descripciones",
      points: [
        { italian: "È alto e magro", english: "Es alto y delgado" },
        { italian: "È simpatica", english: "Ella es simpática" },
        { italian: "Ha i capelli biondi", english: "Tiene el pelo rubio" },
        { italian: "Ha gli occhi azzurri", english: "Tiene los ojos azules" },
      ],
      note: "Las descripciones físicas usan essere (ser/estar) para cualidades y avere (tener) para características como el pelo y los ojos.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor helping describe people. Reply in Spanish. Use lesson 26 vocabulary. Correct gently.",
  },
  {
    id: 27, title: "Con los Vecinos", subtitle: "Con i Vicini", free: false,
    keywords: [
      { italian: "Come va?", english: "¿Cómo va todo?" },
      { italian: "Stanco / stanca", english: "Cansado/a" },
      { italian: "Come mai?", english: "¿Cómo es que…? / ¿Por qué?" },
      { italian: "Ho dormito poco", english: "He dormido poco" },
      { italian: "Tutto bene?", english: "¿Todo bien?" },
      { italian: "La settimana", english: "La semana" },
    ],
    dialogue: [
      { speaker: "A", line: "Buongiorno! Come va?", translation: "¡Buenos días! ¿Cómo va todo?" },
      { speaker: "B", line: "Un po' stanca oggi.", translation: "Un poco cansada hoy." },
      { speaker: "A", line: "Come mai?", translation: "¿Cómo es que…?" },
      { speaker: "B", line: "Ho dormito poco stanotte.", translation: "He dormido poco esta noche." },
      { speaker: "A", line: "Meno male! Buona giornata!", translation: "¡Menos mal! ¡Que tengas un buen día!" },
    ],
    grammar: {
      title: "Expresiones de conversación cotidiana",
      points: [
        { italian: "Come mai?", english: "¿Cómo es que…? / ¿Por qué eso?" },
        { italian: "Meno male!", english: "¡Menos mal! / ¡Qué alivio!" },
        { italian: "Abbastanza", english: "Bastante / suficientemente" },
        { italian: "Mi dispiace", english: "Lo siento" },
      ],
      note: "Come mai es más suave que perché — expresa sorpresa leve. Meno male significa literalmente \"menos malo\" — una expresión italiana muy querida.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friendly neighbour. Reply in Spanish. Practice polite small talk. Correct gently.",
  },
  {
    id: 28, title: "Hablar del Día", subtitle: "Parlare della Giornata", free: false,
    keywords: [
      { italian: "Ieri / oggi / domani", english: "Ayer / hoy / mañana" },
      { italian: "Stamattina / stasera", english: "Esta mañana / esta noche" },
      { italian: "Ho lavorato", english: "He trabajado (pasado)" },
      { italian: "Sono partito/a", english: "He salido / me he ido (pasado)" },
      { italian: "Cosa hai fatto?", english: "¿Qué has hecho?" },
      { italian: "Tutto il giorno", english: "Todo el día" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa hai fatto ieri?", translation: "¿Qué hiciste ayer?" },
      { speaker: "B", line: "Ho lavorato tutto il giorno.", translation: "Trabajé todo el día." },
      { speaker: "B", line: "Sono andato al cinema con Marco.", translation: "Fui al cine con Marco." },
      { speaker: "A", line: "Bello! E domani?", translation: "¡Qué bien! ¿Y mañana?" },
      { speaker: "B", line: "Domani partiamo per Roma.", translation: "Mañana nos vamos a Roma." },
    ],
    grammar: {
      title: "Passato Prossimo — El pasado reciente",
      points: [
        { italian: "Ho lavorato", english: "He trabajado (avere + participio pasado)" },
        { italian: "Sono andato/a", english: "He ido (essere + participio pasado)" },
        { italian: "Abbiamo fatto", english: "Hemos hecho" },
        { italian: "Sei partito/a?", english: "¿Te fuiste?" },
      ],
      note: "El passato prossimo usa avere o essere + participio pasado. Los verbos de movimiento llevan essere, y el participio concuerda con el sujeto.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about the student's recent day. Reply in Spanish. Practice passato prossimo. Correct gently.",
  },
  {
    id: 29, title: "Pedir Explicaciones", subtitle: "Chiedere Spiegazioni", free: false,
    keywords: [
      { italian: "Perché?", english: "¿Por qué?" },
      { italian: "Come mai?", english: "¿Cómo es que…?" },
      { italian: "Allora", english: "Entonces / pues / bueno" },
      { italian: "Quindi", english: "Por lo tanto / así que" },
      { italian: "Non capisco", english: "No entiendo" },
      { italian: "Uno sciopero", english: "Una huelga" },
    ],
    dialogue: [
      { speaker: "A", line: "Perché il treno è in ritardo?", translation: "¿Por qué el tren lleva retraso?" },
      { speaker: "B", line: "Perché c'è uno sciopero.", translation: "Porque hay una huelga." },
      { speaker: "A", line: "Non capisco — c'è un altro treno?", translation: "No entiendo — ¿hay otro tren?" },
      { speaker: "B", line: "Allora, provi l'autobus.", translation: "Pues prueba el autobús." },
    ],
    grammar: {
      title: "Perché — Por qué y Porque",
      points: [
        { italian: "Perché sei in ritardo?", english: "¿Por qué llegas tarde? (pregunta)" },
        { italian: "Perché c'è traffico", english: "Porque hay tráfico (respuesta)" },
        { italian: "Non lo so", english: "No sé" },
        { italian: "Forse", english: "Quizás" },
      ],
      note: "Perché significa tanto \"por qué\" como \"porque\" en italiano. Allora se escucha constantemente en las conversaciones italianas.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing situations where things go wrong. Reply in Spanish. Use lesson 29 vocabulary. Correct gently.",
  },
  {
    id: 30, title: "Sueños y Deseos", subtitle: "Sogni e Desideri", free: false,
    keywords: [
      { italian: "Vorrei...", english: "Quisiera… / Me gustaría…" },
      { italian: "Mi piacerebbe", english: "Me gustaría (lit. me agradaría)" },
      { italian: "Magari", english: "Quizás / ojalá / me gustaría" },
      { italian: "Forse", english: "Quizás" },
      { italian: "Un giorno", english: "Un día" },
      { italian: "Davvero?", english: "¿De verdad?" },
    ],
    dialogue: [
      { speaker: "A", line: "Vorrei vivere in Italia.", translation: "Me gustaría vivir en Italia." },
      { speaker: "B", line: "Davvero? In quale città?", translation: "¿De verdad? ¿En qué ciudad?" },
      { speaker: "A", line: "Firenze. Mi piacerebbe molto.", translation: "Florencia. Me gustaría mucho." },
      { speaker: "B", line: "Magari vengo anch'io!", translation: "¡Quizás vaya yo también!" },
      { speaker: "A", line: "Forse un giorno si può.", translation: "Quizás un día sea posible." },
    ],
    grammar: {
      title: "Condicional — Vorrei y Mi piacerebbe",
      points: [
        { italian: "Vorrei andare a Roma", english: "Me gustaría ir a Roma" },
        { italian: "Mi piacerebbe molto", english: "Me gustaría mucho" },
        { italian: "Magari!", english: "¡Ojalá! / ¡Cómo me gustaría!" },
        { italian: "Sarebbe bello", english: "Sería precioso" },
      ],
      note: "Magari puede significar quizás, ojalá o me gustaría, según el tono. ¡A los italianos les encanta!",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a conversation about wishes. Reply in Spanish. Use lesson 30 vocabulary. Correct gently.",
  },
  {
    id: 31, title: "En Casa", subtitle: "A Casa", free: false,
    keywords: [
      { italian: "Il soggiorno", english: "El salón" },
      { italian: "La cucina", english: "La cocina" },
      { italian: "Il divano", english: "El sofá" },
      { italian: "Cucinare", english: "Cocinar" },
      { italian: "Pulire", english: "Limpiar" },
      { italian: "Rilassarsi", english: "Relajarse" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei a casa?", translation: "¿Estás en casa?" },
      { speaker: "B", line: "Sì, sto cucinando in cucina.", translation: "Sí, estoy cocinando en la cocina." },
      { speaker: "A", line: "Dopo ti rilassi un po'?", translation: "¿Te relajarás un poco después?" },
      { speaker: "B", line: "Spero! Mi butto sul divano.", translation: "¡Espero que sí! Me voy a tirar en el sofá." },
    ],
    grammar: {
      title: "Verbos reflexivos — Verbi Riflessivi",
      points: [
        { italian: "Mi rilasso", english: "Me relajo" },
        { italian: "Ti svegli?", english: "¿Te despiertas?" },
        { italian: "Si chiama", english: "Se llama" },
        { italian: "Mi butto sul divano", english: "Me tiro en el sofá" },
      ],
      note: "Los verbos reflexivos usan un pronombre (mi, ti, si, ci, vi, si) que se refiere al sujeto — para acciones que uno hace sobre sí mismo.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a cosy conversation about home. Reply in Spanish. Use lesson 31 vocabulary. Correct gently.",
  },
  {
    id: 32, title: "Rutina Diaria", subtitle: "La Routine Quotidiana", free: false,
    keywords: [
      { italian: "Mi sveglio", english: "Me despierto" },
      { italian: "Faccio colazione", english: "Desayuno" },
      { italian: "Mi vesto", english: "Me visto" },
      { italian: "Torno a casa", english: "Vuelvo a casa" },
      { italian: "Di solito", english: "Normalmente" },
      { italian: "Mi addormento", english: "Me duermo" },
    ],
    dialogue: [
      { speaker: "A", line: "A che ora ti svegli di solito?", translation: "¿A qué hora te sueles despertar?" },
      { speaker: "B", line: "Mi sveglio alle sette. Faccio colazione e poi mi vesto.", translation: "Me despierto a las siete. Desayuno y luego me visto." },
      { speaker: "A", line: "E vai a letto tardi?", translation: "¿Y te acuestas tarde?" },
      { speaker: "B", line: "No, mi addormento verso le undici.", translation: "No, me duermo hacia las once." },
    ],
    grammar: {
      title: "Verbos reflexivos — La vida cotidiana",
      points: [
        { italian: "Mi sveglio alle 7", english: "Me despierto a las 7" },
        { italian: "Mi lavo", english: "Me lavo" },
        { italian: "Mi vesto", english: "Me visto" },
        { italian: "Mi addormento", english: "Me duermo" },
      ],
      note: "La rutina diaria en italiano está llena de verbos reflexivos. El pronombre siempre va antes del verbo conjugado.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about the student's daily routine. Reply in Spanish. Use reflexive verbs. Correct gently.",
  },
  {
    id: 33, title: "En el Supermercado", subtitle: "Al Supermercato", free: false,
    keywords: [
      { italian: "Il carrello", english: "El carrito" },
      { italian: "Il reparto", english: "El pasillo / sección" },
      { italian: "La cassa", english: "La caja" },
      { italian: "Mezzo chilo", english: "Medio kilo" },
      { italian: "In offerta", english: "En oferta" },
      { italian: "Dov'è il reparto...?", english: "¿Dónde está la sección…?" },
    ],
    dialogue: [
      { speaker: "A", line: "Scusi, dov'è il reparto latticini?", translation: "Perdone, ¿dónde está la sección de lácteos?" },
      { speaker: "B", line: "È in fondo a destra.", translation: "Está al fondo a la derecha." },
      { speaker: "A", line: "Questo formaggio è in offerta?", translation: "¿Este queso está en oferta?" },
      { speaker: "B", line: "Sì, prenda due e risparmia il 20%.", translation: "Sí, lleve dos y ahorre el 20%." },
    ],
    grammar: {
      title: "Partitivos — Expresar «algo de»",
      points: [
        { italian: "Del pane", english: "Un poco de pan (partitivo)" },
        { italian: "Delle mele", english: "Unas manzanas (partitivo)" },
        { italian: "Un chilo di pasta", english: "Un kilo de pasta" },
        { italian: "Mezzo litro di latte", english: "Medio litro de leche" },
      ],
      note: "El italiano usa del/della/dei/delle para decir \"algo de\". Vorrei del pane = Quisiera un poco de pan.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a supermarket assistant. Reply in Spanish. Use lesson 33 vocabulary. Correct gently.",
  },
  {
    id: 34, title: "En el Autobús", subtitle: "Sull'Autobus", free: false,
    keywords: [
      { italian: "Il biglietto", english: "El billete" },
      { italian: "La fermata", english: "La parada" },
      { italian: "Scendere", english: "Bajarse" },
      { italian: "Salire", english: "Subirse" },
      { italian: "Quante fermate?", english: "¿Cuántas paradas?" },
      { italian: "Devo cambiare?", english: "¿Tengo que hacer transbordo?" },
    ],
    dialogue: [
      { speaker: "A", line: "Scusi, questo autobus va al centro?", translation: "Perdone, ¿este autobús va al centro?" },
      { speaker: "B", line: "Sì, ma deve cambiare alla fermata San Marco.", translation: "Sí, pero tiene que hacer transbordo en la parada San Marco." },
      { speaker: "A", line: "Quante fermate sono?", translation: "¿Cuántas paradas son?" },
      { speaker: "B", line: "Quattro fermate. Poi scende e aspetta il 14.", translation: "Cuatro paradas. Luego bájese y espere el 14." },
    ],
    grammar: {
      title: "Dovere + Infinitivo en el transporte público",
      points: [
        { italian: "Devo scendere qui", english: "Tengo que bajarme aquí" },
        { italian: "Deve cambiare", english: "Tiene que hacer transbordo (formal)" },
        { italian: "Devi comprare il biglietto", english: "Tienes que comprar el billete" },
      ],
      note: "En el transporte público, dovere (deber) y potere (poder) son esenciales. Siempre van con un infinitivo.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a fellow passenger on an Italian bus. Reply in Spanish. Use lesson 34 vocabulary. Correct gently.",
  },
  {
    id: 35, title: "Tiempo Libre", subtitle: "Il Tempo Libero", free: false,
    keywords: [
      { italian: "Leggere", english: "Leer" },
      { italian: "Guardare un film", english: "Ver una película" },
      { italian: "Passeggiare", english: "Pasear" },
      { italian: "Ascoltare musica", english: "Escuchar música" },
      { italian: "Nel tempo libero", english: "En mi tiempo libre" },
      { italian: "Mi annoio", english: "Me aburro" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa fai nel tempo libero?", translation: "¿Qué haces en tu tiempo libre?" },
      { speaker: "B", line: "Mi piace leggere e ascoltare musica.", translation: "Me gusta leer y escuchar música." },
      { speaker: "A", line: "Guardi film italiani?", translation: "¿Ves películas italianas?" },
      { speaker: "B", line: "Sì! È il modo migliore per imparare.", translation: "¡Sí! Es la mejor manera de aprender." },
    ],
    grammar: {
      title: "Infinitivos como sustantivos",
      points: [
        { italian: "Mi piace leggere", english: "Me gusta leer" },
        { italian: "Adoro cucinare", english: "Me encanta cocinar" },
        { italian: "Odio aspettare", english: "Odio esperar" },
        { italian: "Ho voglia di uscire", english: "Me apetece salir" },
      ],
      note: "Cuando hablas de actividades que te gustan o no, usa el infinitivo directamente después de mi piace, preferisco, adoro etc.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a relaxed chat about hobbies. Reply in Spanish. Use lesson 35 vocabulary. Correct gently.",
  },
  {
    id: 36, title: "Invitaciones y Rechazos", subtitle: "Inviti e Rifiuti", free: false,
    keywords: [
      { italian: "Ti va di...?", english: "¿Te apetece…?" },
      { italian: "Volentieri!", english: "¡Con mucho gusto!" },
      { italian: "Non posso", english: "No puedo" },
      { italian: "Peccato", english: "Qué pena" },
      { italian: "Un'altra volta", english: "Otra vez será" },
      { italian: "Magari la prossima", english: "Quizás la próxima" },
    ],
    dialogue: [
      { speaker: "A", line: "Ti va di venire a cena stasera?", translation: "¿Te apetece venir a cenar esta noche?" },
      { speaker: "B", line: "Volentieri! A che ora?", translation: "¡Con mucho gusto! ¿A qué hora?" },
      { speaker: "A", line: "Alle otto.", translation: "A las ocho." },
      { speaker: "B", line: "Se non può, peccato — un'altra volta.", translation: "Si no puede, qué pena — otra vez será." },
    ],
    grammar: {
      title: "Verbos modales — Invitaciones y rechazos",
      points: [
        { italian: "Non posso venire", english: "No puedo venir" },
        { italian: "Dovrei restare", english: "Debería quedarme" },
        { italian: "Potremmo andare", english: "Podríamos ir" },
        { italian: "Ti va di...?", english: "¿Te apetece…? (expresión fija)" },
      ],
      note: "Ti va di...? es una de las expresiones de invitación italianas más útiles. Peccato suaviza un rechazo magníficamente.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing invitations. Reply in Spanish. Use lesson 36 vocabulary. Correct gently.",
  },
  {
    id: 37, title: "Mi Ciudad", subtitle: "La Mia Città", free: false,
    keywords: [
      { italian: "Ciò che mi piace di più", english: "Lo que más me gusta" },
      { italian: "La cosa più interessante", english: "La cosa más interesante" },
      { italian: "Quello che non mi piace tanto", english: "Lo que no me gusta tanto" },
      { italian: "Il quartiere", english: "El barrio" },
      { italian: "Vivace / tranquillo", english: "Animado / tranquilo" },
      { italian: "Mi manca", english: "Lo/La echo de menos" },
    ],
    dialogue: [
      { speaker: "A", line: "Di dove sei?", translation: "¿De dónde eres?" },
      { speaker: "B", line: "Sono di Napoli.", translation: "Soy de Nápoles." },
      { speaker: "A", line: "Cosa ti piace di più?", translation: "¿Qué es lo que más te gusta de allí?" },
      { speaker: "B", line: "Ciò che mi piace di più è il mare e il cibo.", translation: "Lo que más me gusta es el mar y la comida." },
      { speaker: "B", line: "Quello che non sopporto è il caos del traffico.", translation: "Lo que no soporto es el caos del tráfico." },
    ],
    grammar: {
      title: "Oraciones relativas — Ciò che / Quello che",
      points: [
        { italian: "Ciò che mi piace", english: "Lo que me gusta (lo que me place)" },
        { italian: "Quello che voglio", english: "Lo que quiero" },
        { italian: "Non è quello che pensavo", english: "No es lo que pensaba" },
        { italian: "Tutto ciò che sai", english: "Todo lo que sabes" },
      ],
      note: "Ciò che y quello che significan ambos \"lo que\". Son intercambiables. Úsalos para expresar preferencias y opiniones con elegancia.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor talking about Italian cities. Reply in Spanish. Use lesson 37 vocabulary. Correct gently.",
  },
  {
    id: 38, title: "Con Prisa", subtitle: "Di Fretta", free: false,
    keywords: [
      { italian: "Siamo in ritardo!", english: "¡Llegamos tarde!" },
      { italian: "Aspettami!", english: "¡Espérame!" },
      { italian: "Forza!", english: "¡Vamos!" },
      { italian: "Sbrigati!", english: "¡Date prisa!" },
      { italian: "Prendo la valigia", english: "Cojo la maleta" },
      { italian: "Corri!", english: "¡Corre!" },
    ],
    dialogue: [
      { speaker: "A", line: "Sbrigati! Siamo in ritardo!", translation: "¡Date prisa! ¡Llegamos tarde!" },
      { speaker: "B", line: "Aspettami, prendo la valigia.", translation: "Espérame, cojo la maleta." },
      { speaker: "A", line: "Prendila e vieni, forza!", translation: "¡Cógela y ven, venga!" },
      { speaker: "A", line: "Dai, corri! Il treno parte tra cinque minuti.", translation: "¡Vamos, corre! El tren sale en cinco minutos." },
    ],
    grammar: {
      title: "Imperativo informal — Órdenes con pronombres",
      points: [
        { italian: "Aspetta! / Aspettami!", english: "¡Espera! / ¡Espérame!" },
        { italian: "Sbrigati!", english: "¡Date prisa! (imperativo reflexivo)" },
        { italian: "Prendila!", english: "¡Cógelo! (pronombre unido al verbo)" },
        { italian: "Aiutami!", english: "¡Ayúdame!" },
      ],
      note: "En las órdenes informales, los pronombres se unen al final del verbo: prendila (cógelo), aspettami (espérame).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing a rushed situation. Reply in Spanish. Practice urgent commands. Correct gently.",
  },
  {
    id: 39, title: "Domingo con Amigos", subtitle: "Domenica con gli Amici", free: false,
    keywords: [
      { italian: "Vi va di...?", english: "¿Os apetece…?" },
      { italian: "Preferirei", english: "Preferiría" },
      { italian: "L'agriturismo", english: "Restaurante rural / agroturismo" },
      { italian: "È affollato", english: "Está lleno" },
      { italian: "Non si trova parcheggio", english: "No se encuentra aparcamiento" },
      { italian: "Che ne dite?", english: "¿Qué os parece?" },
    ],
    dialogue: [
      { speaker: "A", line: "Vi va di andare al mare domenica?", translation: "¿Os apetece ir a la playa el domingo?" },
      { speaker: "B", line: "Preferirei andare a mangiare in un agriturismo.", translation: "Preferiría ir a comer a un agroturismo." },
      { speaker: "C", line: "Anch'io — la spiaggia è sempre affollata.", translation: "Yo también — la playa siempre está llena." },
      { speaker: "B", line: "Conosco un posto bellissimo in collina. Che ne dite?", translation: "Conozco un sitio precioso en las colinas. ¿Qué os parece?" },
    ],
    grammar: {
      title: "Si Impersonale — El si impersonal",
      points: [
        { italian: "Non si trova parcheggio", english: "No se encuentra aparcamiento" },
        { italian: "Si mangia bene qui", english: "Aquí se come bien" },
        { italian: "Come si dice?", english: "¿Cómo se dice?" },
        { italian: "Non si sa mai", english: "Nunca se sabe" },
      ],
      note: "El si impersonal no tiene sujeto específico — como \"se\" en español. ¿Come si dice? es una de las expresiones más útiles para los estudiantes.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing a group of friends planning a Sunday outing. Reply in Spanish. Correct gently.",
  },
  {
    id: 40, title: "Parece y Recuerdo", subtitle: "Mi Sembra e Mi Ricordo", free: false,
    keywords: [
      { italian: "Mi sembra che", english: "Me parece que" },
      { italian: "Mi pare", english: "Me parece / me da la impresión" },
      { italian: "Ti ricordi?", english: "¿Te acuerdas?" },
      { italian: "Mi ricordo", english: "Me acuerdo" },
      { italian: "Non mi ricordo", english: "No me acuerdo" },
      { italian: "Mi sembra ieri", english: "Parece que fue ayer" },
    ],
    dialogue: [
      { speaker: "A", line: "Ti ricordi di quella vacanza a Capri?", translation: "¿Te acuerdas de esas vacaciones en Capri?" },
      { speaker: "B", line: "Certo! Mi sembra ieri.", translation: "¡Claro! Parece que fue ayer." },
      { speaker: "A", line: "Ti ricordi quel ristorante sul mare?", translation: "¿Te acuerdas de ese restaurante junto al mar?" },
      { speaker: "B", line: "Mi pare di sì, ma non mi ricordo il nome.", translation: "Creo que sí, pero no me acuerdo del nombre." },
    ],
    grammar: {
      title: "Verbos reflexivos — Memoria y percepción",
      points: [
        { italian: "Mi ricordo", english: "Me acuerdo" },
        { italian: "Ti ricordi?", english: "¿Te acuerdas?" },
        { italian: "Si ricorda", english: "Él/Ella se acuerda (también usted formal)" },
        { italian: "Mi sembra / mi pare", english: "Me parece (intercambiable)" },
      ],
      note: "Ricordarsi es reflexivo: mi ricordo, ti ricordi, si ricorda etc. Mi sembra y mi pare son intercambiables — úsalos para suavizar tus afirmaciones.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a nostalgic conversation about shared memories. Reply in Spanish. Correct gently.",
  },
  {
    id: 41, title: "Hablar del Pasado", subtitle: "Parlare del Passato", free: false,
    keywords: [
      { italian: "Ho fatto", english: "He hecho" },
      { italian: "Ho mangiato", english: "He comido" },
      { italian: "Sono andato/a", english: "He ido / Fui" },
      { italian: "Siamo arrivati", english: "Hemos llegado" },
      { italian: "L'anno scorso", english: "El año pasado" },
      { italian: "La settimana scorsa", english: "La semana pasada" },
    ],
    dialogue: [
      { speaker: "A", line: "Come hai passato il weekend?", translation: "¿Cómo pasaste el fin de semana?" },
      { speaker: "B", line: "Sono andato a Venezia con mia moglie.", translation: "Fui a Venecia con mi mujer." },
      { speaker: "A", line: "Avete mangiato bene?", translation: "¿Comisteis bien?" },
      { speaker: "B", line: "Benissimo! Ho mangiato il miglior risotto della mia vita.", translation: "¡Genial! Comí el mejor risotto de mi vida." },
    ],
    grammar: {
      title: "Passato Prossimo — Avere vs Essere",
      points: [
        { italian: "Ho mangiato (avere)", english: "He comido — la mayoría de verbos usan avere" },
        { italian: "Sono andato/a (essere)", english: "He ido — los verbos de movimiento usan essere" },
        { italian: "Siamo arrivati (essere)", english: "Hemos llegado — el participio concuerda" },
        { italian: "Non ho capito", english: "No entendí" },
      ],
      note: "Los verbos de movimiento y los reflexivos usan essere. Todos los demás usan avere. Con essere, el participio concuerda en género y número.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about recent activities. Reply in Spanish. Practice passato prossimo. Correct gently.",
  },
  {
    id: 42, title: "Recuerdos de Infancia", subtitle: "Ricordi d'Infanzia", free: false,
    keywords: [
      { italian: "Quando ero piccolo/a", english: "Cuando era joven" },
      { italian: "Giocavo", english: "Jugaba" },
      { italian: "La scuola", english: "El colegio" },
      { italian: "D'estate", english: "En verano" },
      { italian: "Ogni giorno", english: "Todos los días" },
      { italian: "Mi piaceva", english: "Me gustaba" },
    ],
    dialogue: [
      { speaker: "A", line: "Com'era la tua infanzia?", translation: "¿Cómo era tu infancia?" },
      { speaker: "B", line: "Bellissima! D'estate giocavo sempre fuori.", translation: "¡Genial! En verano siempre jugaba fuera." },
      { speaker: "A", line: "E la scuola? Ti piaceva?", translation: "¿Y el colegio? ¿Te gustaba?" },
      { speaker: "B", line: "Mi piaceva la matematica.", translation: "Me gustaban las matemáticas." },
      { speaker: "A", line: "Quando ero piccola, volevo fare la ballerina.", translation: "Cuando era pequeña, quería ser bailarina." },
    ],
    grammar: {
      title: "Imperfecto — Hábitos y estados en el pasado",
      points: [
        { italian: "Giocavo ogni giorno", english: "Jugaba todos los días" },
        { italian: "Quando ero piccolo...", english: "Cuando era joven..." },
        { italian: "Mi piaceva la scuola", english: "Me gustaba el colegio" },
        { italian: "Era bellissimo", english: "Era maravilloso" },
      ],
      note: "El imperfecto describe estados, hábitos y emociones pasados prolongados. Ho mangiato la pizza (una vez) vs Mangiavo la pizza ogni venerdì (cada viernes).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a nostalgic conversation about childhood. Reply in Spanish. Practice the imperfetto. Correct gently.",
  },
  {
    id: 43, title: "Expresar Opiniones", subtitle: "Esprimere Opinioni", free: false,
    keywords: [
      { italian: "Secondo me", english: "En mi opinión" },
      { italian: "Penso che", english: "Creo que" },
      { italian: "Mi sembra", english: "Me parece" },
      { italian: "Mi pare", english: "Me parece (igual que mi sembra)" },
      { italian: "Sono d'accordo", english: "Estoy de acuerdo" },
      { italian: "Hai ragione", english: "Tienes razón" },
    ],
    dialogue: [
      { speaker: "A", line: "Secondo te, qual è la città più bella d'Italia?", translation: "En tu opinión, ¿cuál es la ciudad más bonita de Italia?" },
      { speaker: "B", line: "Secondo me, Firenze. Mi sembra unica.", translation: "En mi opinión, Florencia. Me parece única." },
      { speaker: "A", line: "Penso che Roma sia più interessante.", translation: "Creo que Roma es más interesante." },
      { speaker: "B", line: "Hai ragione, Roma è straordinaria.", translation: "Tienes razón, Roma es extraordinaria." },
    ],
    grammar: {
      title: "Estructuras para dar opiniones",
      points: [
        { italian: "Secondo me...", english: "En mi opinión… (lit. según yo)" },
        { italian: "Mi sembra che", english: "Me parece que" },
        { italian: "Sono / non sono d'accordo", english: "Estoy / no estoy de acuerdo" },
        { italian: "Hai ragione", english: "Tienes razón" },
      ],
      note: "Secondo me es la forma más sencilla de dar una opinión. Mi sembra y mi pare son intercambiables y muy comunes.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a discussion about Italian cities. Reply in Spanish. Practice opinion structures. Correct gently.",
  },
  {
    id: 44, title: "Dar Consejos", subtitle: "Dare Consigli", free: false,
    keywords: [
      { italian: "Dovresti", english: "Deberías" },
      { italian: "Ti consiglio di", english: "Te aconsejo que" },
      { italian: "È meglio che", english: "Es mejor que" },
      { italian: "Al posto tuo", english: "En tu lugar" },
      { italian: "Perché non...?", english: "¿Por qué no…?" },
      { italian: "Prova a", english: "Intenta" },
    ],
    dialogue: [
      { speaker: "A", line: "Non riesco a dormire bene.", translation: "No consigo dormir bien." },
      { speaker: "B", line: "Dovresti andare a letto prima.", translation: "Deberías acostarte más temprano." },
      { speaker: "B", line: "Ti consiglio di evitare il caffè la sera.", translation: "Te aconsejo evitar el café por la noche." },
      { speaker: "A", line: "Al posto tuo, cosa faresti?", translation: "Si fueras tú, ¿qué harías?" },
      { speaker: "B", line: "Perché non provi una camomilla prima di dormire?", translation: "¿Por qué no pruebas una manzanilla antes de dormir?" },
    ],
    grammar: {
      title: "Condicional para dar consejos",
      points: [
        { italian: "Dovresti riposare", english: "Deberías descansar" },
        { italian: "Potresti provare", english: "Podrías intentarlo" },
        { italian: "Al posto tuo, andrei", english: "En tu lugar, yo iría" },
        { italian: "Ti consiglio di aspettare", english: "Te aconsejo que esperes" },
      ],
      note: "Dovresti (deberías) y potresti (podrías) son formas condicionales — perfectas para dar consejos sin ser demasiado directo.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a wise friend giving advice. Reply in Spanish. Practice conditional for advice. Correct gently.",
  },
  {
    id: 45, title: "Real e Hipotético", subtitle: "Reale e Ipotetico", free: false,
    keywords: [
      { italian: "Se ho i soldi, vado", english: "Si tengo dinero, voy (posibilidad real)" },
      { italian: "Se avessi i soldi, andrei", english: "Si tuviera dinero, iría (hipotético)" },
      { italian: "Magari potessi!", english: "¡Ojalá pudiera!" },
      { italian: "Nel caso in cui", english: "En el caso de que" },
      { italian: "Dipende da", english: "Depende de" },
      { italian: "Chissà", english: "Quién sabe / quizás algún día" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa fai a luglio?", translation: "¿Qué haces en julio?" },
      { speaker: "B", line: "Se ho i soldi, vado in Sicilia.", translation: "Si tengo dinero, voy a Sicilia." },
      { speaker: "A", line: "Io sogno in grande — se avessi i soldi, andrei in Giappone!", translation: "¡Yo sueño a lo grande — si tuviera dinero, iría a Japón!" },
      { speaker: "B", line: "Magari potessi anch'io! Chissà, un giorno.", translation: "¡Ojalá pudiera yo también! Quién sabe, algún día." },
      { speaker: "A", line: "Se vincessi alla lotteria, ci andremmo insieme!", translation: "¡Si ganara la lotería, iríamos juntos!" },
    ],
    grammar: {
      title: "Condicionales — Real vs Hipotético",
      points: [
        { italian: "Se ho tempo, vengo", english: "Si tengo tiempo, vengo (real)" },
        { italian: "Se avessi tempo, verrei", english: "Si tuviera tiempo, vendría (hipotético)" },
        { italian: "Se fosse possibile", english: "Si fuera posible" },
        { italian: "Chissà", english: "Quién sabe (expresa incertidumbre sobre el futuro)" },
      ],
      note: "Real: se + presente = algo que podría pasar de verdad. Hipotético: se + subjuntivo imperfecto + condicional = algo improbable o imaginario.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor exploring real and hypothetical situations. Reply in Spanish. Practice conditionals. Correct gently.",
  },
];
