// lessons/fr.js — French translations for all 45 lessons
// Italian lines (line, italian) are IDENTICAL to en.js — do not change them.
// Only: keywords[].english, dialogue[].translation, grammar.title/points/note differ.

export const LESSONS = [
  {
    id: 1, title: "Salutations", subtitle: "Il Saluto", free: true,
    keywords: [
      { italian: "Ciao", english: "Salut / Au revoir (informel)" },
      { italian: "Salve", english: "Bonjour (neutre/formel)" },
      { italian: "Buongiorno", english: "Bonjour / Bonne journée" },
      { italian: "Buonasera", english: "Bonsoir" },
      { italian: "Arrivederci", english: "Au revoir (formel)" },
      { italian: "Tutto bene", english: "Tout va bien / Ça va" },
    ],
    dialogue: [
      { speaker: "A", line: "Buongiorno! Salve.", translation: "Bonjour ! Salut." },
      { speaker: "B", line: "Ciao! Come stai?", translation: "Salut ! Comment tu vas ?" },
      { speaker: "A", line: "Tutto bene, grazie. E tu?", translation: "Tout va bien, merci. Et toi ?" },
      { speaker: "B", line: "Bene, grazie!", translation: "Bien, merci !" },
    ],
    grammar: {
      title: "Come — Comment / Quoi",
      points: [
        { italian: "Come stai?", english: "Comment tu vas ? (informel)" },
        { italian: "Come sta?", english: "Comment allez-vous ? (formel)" },
        { italian: "Come va?", english: "Comment ça va ?" },
        { italian: "Come?", english: "Quoi ? / Pardon ?" },
      ],
      note: "\"Come\" signifie littéralement \"comment\" — c'est votre mot clé pour poser des questions sur les états et les situations.",
    },
    aiPrompt: "STRICT RULES: Only discuss vocabulary and grammar from this specific lesson. If asked about anything unrelated reply only: 'Let us stick to this lesson!' Never break character. Always reply in French, but use Italian words and phrases from the lesson. Correct the student gently. You are an Italian language tutor. The student just learned Lesson 1: Greetings. Help them practice: Ciao, Salve, Buongiorno, Buonasera, Arrivederci, Tutto bene, Come stai, Come va. Keep responses short and warm.",
  },
  {
    id: 2, title: "Se Présenter", subtitle: "Presentarsi", free: false,
    keywords: [
      { italian: "Mi chiamo…", english: "Je m'appelle…" },
      { italian: "Sono…", english: "Je suis…" },
      { italian: "Piacere", english: "Enchanté(e)" },
      { italian: "Di dove sei?", english: "D'où viens-tu ?" },
      { italian: "Sono di…", english: "Je viens de…" },
      { italian: "Quanti anni hai?", english: "Quel âge as-tu ?" },
    ],
    dialogue: [
      { speaker: "A", line: "Ciao! Sono Paolo.", translation: "Salut ! Je suis Paolo." },
      { speaker: "B", line: "Ciao, Paolo. Sono Monica. Piacere!", translation: "Salut, Paolo. Je suis Monica. Enchanté(e) !" },
      { speaker: "A", line: "Piacere mio. Di dove sei?", translation: "Enchanté(e) également. D'où viens-tu ?" },
      { speaker: "B", line: "Sono di Firenze. E tu?", translation: "Je viens de Florence. Et toi ?" },
      { speaker: "A", line: "Sono di Milano.", translation: "Je viens de Milan." },
    ],
    grammar: {
      title: "Essere — Le verbe « Être »",
      points: [
        { italian: "Io sono", english: "Je suis" },
        { italian: "Tu sei", english: "Tu es (informel)" },
        { italian: "Lei è", english: "Vous êtes (formel) / Elle est" },
        { italian: "Lui è", english: "Il est" },
        { italian: "Noi siamo", english: "Nous sommes" },
        { italian: "Voi siete", english: "Vous êtes" },
        { italian: "Loro sono", english: "Ils/Elles sont" },
      ],
      note: "En italien, il est rarement nécessaire de dire \"io\" (je) — la terminaison du verbe indique qui parle.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor. Reply in French. Practice introductions: Mi chiamo, Sono, Piacere, Di dove sei, Sono di. Correct gently, keep it short and warm.",
  },
  {
    id: 3, title: "Au Café", subtitle: "Al Bar", free: false,
    keywords: [
      { italian: "Un caffè, per favore", english: "Un café, s'il vous plaît" },
      { italian: "Vorrei…", english: "Je voudrais…" },
      { italian: "Quanto costa?", english: "Combien ça coûte ?" },
      { italian: "Il conto", english: "L'addition" },
      { italian: "Un cornetto", english: "Un croissant" },
      { italian: "Grazie mille", english: "Merci beaucoup" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Un caffè, per favore.", translation: "Bonjour ! Un café, s'il vous plaît." },
      { speaker: "Barista", line: "Subito! Vuole anche un cornetto?", translation: "Tout de suite ! Voulez-vous aussi un croissant ?" },
      { speaker: "Cliente", line: "Sì, grazie. Quanto costa?", translation: "Oui, merci. Combien ça coûte ?" },
      { speaker: "Barista", line: "Un euro e cinquanta, prego.", translation: "Un euro cinquante, s'il vous plaît." },
      { speaker: "Cliente", line: "Ecco. Grazie mille!", translation: "Voilà. Merci beaucoup !" },
    ],
    grammar: {
      title: "Vorrei — Demandes polies",
      points: [
        { italian: "Vorrei un caffè", english: "Je voudrais un café" },
        { italian: "Vorrei il conto", english: "Je voudrais l'addition" },
        { italian: "Vorrei prenotare", english: "Je voudrais réserver" },
        { italian: "Vorrei un tavolo", english: "Je voudrais une table" },
      ],
      note: "\"Vorrei\" est le conditionnel de \"volere\" (vouloir). Plus poli que \"voglio\" — à utiliser toujours dans les commerces et restaurants.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a barista. Reply in French. Use only lesson 3 vocabulary. Correct gently.",
  },
  {
    id: 4, title: "À la Gelateria", subtitle: "In Gelateria", free: false,
    keywords: [
      { italian: "Un gelato", english: "Une glace" },
      { italian: "Che gusti?", english: "Quels parfums ?" },
      { italian: "Cono o coppetta?", english: "Cornet ou coupe ?" },
      { italian: "Piccolo / medio / grande", english: "Petit / moyen / grand" },
      { italian: "Che buono!", english: "Comme c'est bon !" },
      { italian: "Posso assaggiare?", english: "Je peux goûter ?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buonasera! Vorrei un gelato.", translation: "Bonsoir ! Je voudrais une glace." },
      { speaker: "Gelataio", line: "Certo! Cono o coppetta?", translation: "Bien sûr ! Cornet ou coupe ?" },
      { speaker: "Cliente", line: "Cono, grazie. Posso assaggiare il pistacchio?", translation: "Cornet, s'il vous plaît. Je peux goûter la pistache ?" },
      { speaker: "Gelataio", line: "Certo, ecco a lei.", translation: "Bien sûr, voilà." },
      { speaker: "Cliente", line: "Mmm, che buono! Pistacchio e cioccolato, per favore.", translation: "Mmm, comme c'est bon ! Pistache et chocolat, s'il vous plaît." },
      { speaker: "Gelataio", line: "Piccolo, medio o grande?", translation: "Petit, moyen ou grand ?" },
      { speaker: "Cliente", line: "Medio. Quanto costa?", translation: "Moyen. Combien ça coûte ?" },
      { speaker: "Gelataio", line: "Due euro e cinquanta.", translation: "Deux euros cinquante." },
    ],
    grammar: {
      title: "questo / quello — Celui-ci / Celui-là",
      points: [
        { italian: "Questo gelato", english: "Cette glace (à proximité)" },
        { italian: "Quello lì", english: "Celui-là (là-bas)" },
        { italian: "Questo è buono", english: "Celui-ci est bon" },
        { italian: "Qual è il migliore?", english: "Lequel est le meilleur ?" },
      ],
      note: "Utilisez \"questo\" pour les choses proches et \"quello\" pour les choses éloignées — même logique que this/that en anglais.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a gelateria worker. Reply in French. Use lesson 4 vocabulary. Correct gently.",
  },
  {
    id: 5, title: "Demander son Chemin", subtitle: "Chiedere la Strada", free: false,
    keywords: [
      { italian: "Dov'è…?", english: "Où est… ?" },
      { italian: "A destra", english: "À droite" },
      { italian: "A sinistra", english: "À gauche" },
      { italian: "Sempre dritto", english: "Tout droit" },
      { italian: "Vicino / lontano", english: "Près / loin" },
      { italian: "Scusi!", english: "Excusez-moi ! (formel)" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Scusi! Dov'è il Colosseo?", translation: "Excusez-moi ! Où est le Colisée ?" },
      { speaker: "Passante", line: "Allora… vada sempre dritto, poi a destra.", translation: "Allez tout droit, puis tournez à droite." },
      { speaker: "Turista", line: "È lontano?", translation: "C'est loin ?" },
      { speaker: "Passante", line: "No, è vicino. Cinque minuti a piedi.", translation: "Non, c'est près. Cinq minutes à pied." },
      { speaker: "Turista", line: "Grazie mille!", translation: "Merci beaucoup !" },
      { speaker: "Passante", line: "Prego! Buona visita!", translation: "De rien ! Bonne visite !" },
    ],
    grammar: {
      title: "C'è / Ci sono — Il y a",
      points: [
        { italian: "C'è un autobus?", english: "Il y a un bus ?" },
        { italian: "Ci sono taxi?", english: "Il y a des taxis ?" },
        { italian: "C'è una fermata vicino?", english: "Il y a un arrêt près d'ici ?" },
        { italian: "Non c'è problema", english: "Il n'y a pas de problème" },
      ],
      note: "\"C'è\" et \"ci sono\" sont vos expressions clés pour demander si quelque chose existe ou est disponible.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a local Roman. Reply in French. Use lesson 5 vocabulary. Correct gently.",
  },
  {
    id: 6, title: "À l'Aéroport", subtitle: "All'Aeroporto", free: false,
    keywords: [
      { italian: "Il volo", english: "Le vol" },
      { italian: "Il passaporto", english: "Le passeport" },
      { italian: "Il bagaglio", english: "Les bagages" },
      { italian: "Quanti bagagli hai?", english: "Combien de bagages as-tu ?" },
      { italian: "Il gate", english: "La porte d'embarquement" },
      { italian: "In ritardo / in orario", english: "En retard / à l'heure" },
    ],
    dialogue: [
      { speaker: "Agente", line: "Buongiorno! Il passaporto, per favore.", translation: "Bonjour ! Votre passeport, s'il vous plaît." },
      { speaker: "Passeggero", line: "Eccolo. Ho anche un bagaglio da imbarcare.", translation: "Le voilà. J'ai aussi un bagage à enregistrer." },
      { speaker: "Agente", line: "Quanti bagagli ha?", translation: "Combien de bagages avez-vous ?" },
      { speaker: "Passeggero", line: "Solo uno. Il volo è in orario?", translation: "Un seul. Le vol est à l'heure ?" },
      { speaker: "Agente", line: "Sì, parte alle undici. Gate B7.", translation: "Oui, il part à onze heures. Porte B7." },
      { speaker: "Passeggero", line: "Grazie mille!", translation: "Merci beaucoup !" },
    ],
    grammar: {
      title: "Avere — Le verbe « Avoir »",
      points: [
        { italian: "Io ho", english: "J'ai" },
        { italian: "Tu hai", english: "Tu as (informel)" },
        { italian: "Lei ha", english: "Vous avez (formel) / Elle a" },
        { italian: "Lui ha", english: "Il a" },
        { italian: "Noi abbiamo", english: "Nous avons" },
        { italian: "Voi avete", english: "Vous avez" },
        { italian: "Loro hanno", english: "Ils/Elles ont" },
      ],
      note: "\"Avere\" est l'un des deux verbes les plus importants en italien. Aussi utilisé pour l'âge : \"ho trent'anni\" = j'ai trente ans.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing an airport agent. Reply in French. Use lesson 6 vocabulary. Correct gently.",
  },
  {
    id: 7, title: "Au Restaurant", subtitle: "Al Ristorante", free: false,
    keywords: [
      { italian: "Un tavolo per due", english: "Une table pour deux" },
      { italian: "Il menù", english: "Le menu" },
      { italian: "Il primo / il secondo", english: "Le premier / deuxième plat" },
      { italian: "Sono vegetariano/a", english: "Je suis végétarien(ne)" },
      { italian: "È compreso?", english: "C'est compris ?" },
      { italian: "Il coperto", english: "Le couvert" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buonasera! Un tavolo per due, per favore.", translation: "Bonsoir ! Une table pour deux, s'il vous plaît." },
      { speaker: "Cameriere", line: "Certo, prego. Ecco il menù.", translation: "Bien sûr. Voici le menu." },
      { speaker: "Cliente", line: "Grazie. Sono vegetariana — cosa consiglia?", translation: "Merci. Je suis végétarienne — que recommandez-vous ?" },
      { speaker: "Cameriere", line: "Ottime le tagliatelle ai funghi!", translation: "Les tagliatelles aux champignons sont excellentes !" },
      { speaker: "Cliente", line: "Perfetto. E il coperto è compreso?", translation: "Parfait. Le couvert est-il compris ?" },
      { speaker: "Cameriere", line: "Sì, è già incluso. Buon appetito!", translation: "Oui, c'est inclus. Bon appétit !" },
    ],
    grammar: {
      title: "Mi piace / Mi piacciono — J'aime",
      points: [
        { italian: "Mi piace la pasta", english: "J'aime les pâtes" },
        { italian: "Mi piacciono i funghi", english: "J'aime les champignons (pluriel)" },
        { italian: "Non mi piace", english: "Je n'aime pas ça" },
        { italian: "Mi piace molto", english: "J'aime beaucoup ça" },
      ],
      note: "\"Piacere\" fonctionne à l'envers — on dit \"cela me plaît\". Utilisez \"piace\" pour une chose, \"piacciono\" pour plusieurs.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a restaurant waiter. Reply in French. Use lesson 7 vocabulary. Correct gently.",
  },
  {
    id: 8, title: "Faire du Shopping", subtitle: "Fare Shopping", free: false,
    keywords: [
      { italian: "Posso provarlo?", english: "Puis-je l'essayer ?" },
      { italian: "Che taglia?", english: "Quelle taille ?" },
      { italian: "È troppo caro", english: "C'est trop cher" },
      { italian: "C'è lo sconto?", english: "Il y a une réduction ?" },
      { italian: "Lo prendo", english: "Je le prends" },
      { italian: "Accettate carte di credito?", english: "Acceptez-vous les cartes de crédit ?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Posso provare questa giacca?", translation: "Bonjour ! Puis-je essayer cette veste ?" },
      { speaker: "Commessa", line: "Certo! Che taglia porta?", translation: "Bien sûr ! Quelle taille faites-vous ?" },
      { speaker: "Cliente", line: "La media, grazie.", translation: "Taille moyenne, merci." },
      { speaker: "Cliente", line: "Hmm… quanto costa?", translation: "Hmm… combien ça coûte ?" },
      { speaker: "Commessa", line: "Centoventi euro. C'è il 20% di sconto oggi!", translation: "Cent vingt euros. Il y a 20 % de réduction aujourd'hui !" },
      { speaker: "Cliente", line: "Perfetto, lo prendo! Accettate carte?", translation: "Parfait, je la prends ! Vous acceptez les cartes ?" },
      { speaker: "Commessa", line: "Sì, certo.", translation: "Oui, bien sûr." },
    ],
    grammar: {
      title: "Potere — Pouvoir",
      points: [
        { italian: "Posso provarlo?", english: "Puis-je l'essayer ?" },
        { italian: "Puoi aiutarmi?", english: "Peux-tu m'aider ?" },
        { italian: "Possiamo pagare con la carta?", english: "Pouvons-nous payer par carte ?" },
      ],
      note: "\"Potere\" est un verbe modal — il se combine avec l'infinitif. C'est votre clé pour demander la permission et exprimer la capacité.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a shop assistant. Reply in French. Use lesson 8 vocabulary. Correct gently.",
  },
  {
    id: 9, title: "À l'Hôtel", subtitle: "In Albergo", free: false,
    keywords: [
      { italian: "Ho una prenotazione", english: "J'ai une réservation" },
      { italian: "La camera", english: "La chambre" },
      { italian: "A che ora è il check-out?", english: "À quelle heure est le check-out ?" },
      { italian: "La colazione è inclusa?", english: "Le petit-déjeuner est inclus ?" },
      { italian: "C'è il wifi?", english: "Il y a le wifi ?" },
      { italian: "La chiave", english: "La clé" },
    ],
    dialogue: [
      { speaker: "Ospite", line: "Buonasera! Ho una prenotazione. Mi chiamo Rossi.", translation: "Bonsoir ! J'ai une réservation. Je m'appelle Rossi." },
      { speaker: "Receptionist", line: "Benvenuto! Sì, camera doppia per tre notti.", translation: "Bienvenue ! Oui, chambre double pour trois nuits." },
      { speaker: "Ospite", line: "Perfetto. La colazione è inclusa?", translation: "Parfait. Le petit-déjeuner est-il inclus ?" },
      { speaker: "Receptionist", line: "Sì, dalle sette alle dieci. C'è anche il wifi gratuito.", translation: "Oui, de sept à dix heures. Il y a aussi le wifi gratuit." },
      { speaker: "Ospite", line: "Ottimo. A che ora è il check-out?", translation: "Excellent. À quelle heure est le check-out ?" },
      { speaker: "Receptionist", line: "Alle undici. Ecco la sua chiave. Buona permanenza!", translation: "À onze heures. Voici votre clé. Bon séjour !" },
    ],
    grammar: {
      title: "Prépositions : a, di, da, in",
      points: [
        { italian: "Sono a Roma", english: "Je suis à Rome (lieu)" },
        { italian: "Vengo da Londra", english: "Je viens de Londres (origine)" },
        { italian: "Vado in Italia", english: "Je vais en Italie (pays)" },
        { italian: "La chiave di Maria", english: "La clé de Maria (possession)" },
      ],
      note: "Les prépositions italiennes ne correspondent pas toujours au français. \"In\" s'utilise avec les pays, \"a\" avec les villes.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a hotel receptionist. Reply in French. Use lesson 9 vocabulary. Correct gently.",
  },
  {
    id: 10, title: "Dans le Train", subtitle: "Sul Treno", free: false,
    keywords: [
      { italian: "Un biglietto per…", english: "Un billet pour…" },
      { italian: "Andata e ritorno", english: "Aller-retour" },
      { italian: "Il binario", english: "Le quai" },
      { italian: "È occupato?", english: "Cette place est-elle prise ?" },
      { italian: "A che ora arriva?", english: "À quelle heure arrive-t-il ?" },
      { italian: "Il treno è in ritardo", english: "Le train est en retard" },
    ],
    dialogue: [
      { speaker: "Viaggiatore", line: "Buongiorno! Un biglietto per Venezia, per favore.", translation: "Bonjour ! Un billet pour Venise, s'il vous plaît." },
      { speaker: "Bigliettaio", line: "Andata e ritorno?", translation: "Aller-retour ?" },
      { speaker: "Viaggiatore", line: "Solo andata. A che ora arriva?", translation: "Aller simple. À quelle heure arrive-t-il ?" },
      { speaker: "Bigliettaio", line: "Alle tredici e venti. Binario 4.", translation: "À treize heures vingt. Quai 4." },
      { speaker: "Viaggiatore", line: "Grazie. È occupato questo posto?", translation: "Merci. Cette place est-elle prise ?" },
      { speaker: "Passeggero", line: "No, si accomodi!", translation: "Non, je vous en prie, asseyez-vous !" },
    ],
    grammar: {
      title: "L'heure",
      points: [
        { italian: "Sono le tre", english: "Il est trois heures" },
        { italian: "È mezzogiorno", english: "Il est midi" },
        { italian: "Alle otto e mezza", english: "À huit heures et demie" },
        { italian: "A che ora?", english: "À quelle heure ?" },
      ],
      note: "Les Italiens utilisent l'horloge 24h pour les transports. \"Sono le tredici\" = 13h. On utilise \"sono le\" sauf pour 1h : \"è l'una\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a train station agent. Reply in French. Use lesson 10 vocabulary. Correct gently.",
  },
  {
    id: 11, title: "Au Marché", subtitle: "Al Mercato", free: false,
    keywords: [
      { italian: "Quanto pesa?", english: "Combien ça pèse ?" },
      { italian: "Un chilo di…", english: "Un kilo de…" },
      { italian: "Fresco / di stagione", english: "Frais / de saison" },
      { italian: "Me ne dà mezzo chilo", english: "Donnez-m'en un demi-kilo" },
      { italian: "Basta così", english: "C'est tout" },
      { italian: "Il resto", english: "La monnaie" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Questi pomodori sono freschi?", translation: "Bonjour ! Ces tomates sont-elles fraîches ?" },
      { speaker: "Venditore", line: "Freschissimi! Di stagione. Quanti ne vuole?", translation: "Très fraîches ! De saison. Combien en voulez-vous ?" },
      { speaker: "Cliente", line: "Me ne dà un chilo, per favore.", translation: "Donnez-m'en un kilo, s'il vous plaît." },
      { speaker: "Venditore", line: "Basta così?", translation: "C'est tout ?" },
      { speaker: "Cliente", line: "Sì, grazie. Ecco cinque euro.", translation: "Oui, merci. Voilà cinq euros." },
      { speaker: "Venditore", line: "Ecco il resto. Grazie, a presto!", translation: "Voici la monnaie. Merci, à bientôt !" },
    ],
    grammar: {
      title: "Ne — Le pronom partitif",
      points: [
        { italian: "Ne voglio un chilo", english: "J'en veux un kilo" },
        { italian: "Me ne dà due?", english: "Vous pouvez m'en donner deux ?" },
        { italian: "Non ne ho", english: "Je n'en ai pas" },
        { italian: "Quanti ne vuole?", english: "Combien en voulez-vous ?" },
      ],
      note: "\"Ne\" remplace un nom avec une quantité. Signifie grosso modo \"en\". Les Italiens l'utilisent constamment.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a market vendor. Reply in French. Use lesson 11 vocabulary. Correct gently.",
  },
  {
    id: 12, title: "Urgences et Santé", subtitle: "Emergenze e Salute", free: false,
    keywords: [
      { italian: "Aiuto!", english: "Au secours !" },
      { italian: "Ho bisogno di un medico", english: "J'ai besoin d'un médecin" },
      { italian: "Mi fa male…", english: "… me fait mal" },
      { italian: "Chiami un'ambulanza!", english: "Appelez une ambulance !" },
      { italian: "La farmacia", english: "La pharmacie" },
      { italian: "Sono allergico/a a…", english: "Je suis allergique à…" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Scusi! Ho bisogno di aiuto.", translation: "Excusez-moi ! J'ai besoin d'aide." },
      { speaker: "Passante", line: "Cosa succede?", translation: "Qu'est-ce qui se passe ?" },
      { speaker: "Turista", line: "Mi fa molto male la testa. Ho la febbre.", translation: "J'ai très mal à la tête. J'ai de la fièvre." },
      { speaker: "Passante", line: "C'è una farmacia qui vicino.", translation: "Il y a une pharmacie près d'ici." },
      { speaker: "Turista", line: "Sono allergico alla penicillina.", translation: "Je suis allergique à la pénicilline." },
      { speaker: "Passante", line: "Lo dica al farmacista. Venga, l'accompagno.", translation: "Dites-le au pharmacien. Venez, je vous accompagne." },
    ],
    grammar: {
      title: "Mi fa male — Exprimer la douleur",
      points: [
        { italian: "Mi fa male la testa", english: "J'ai mal à la tête" },
        { italian: "Mi fa male lo stomaco", english: "J'ai mal à l'estomac" },
        { italian: "Mi fanno male i piedi", english: "J'ai mal aux pieds (pluriel)" },
        { italian: "Ho la febbre", english: "J'ai de la fièvre" },
      ],
      note: "\"Mi fa male\" signifie \"cela me fait mal\". Utilisez \"fa male\" pour une partie du corps, \"fanno male\" pour plusieurs.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor helping practice emergency vocabulary. Reply in French. Correct gently.",
  },
  {
    id: 13, title: "À la Pharmacie", subtitle: "In Farmacia", free: false,
    keywords: [
      { italian: "Ho bisogno di…", english: "J'ai besoin de…" },
      { italian: "Una ricetta", english: "Une ordonnance" },
      { italian: "Il mal di testa", english: "Mal de tête" },
      { italian: "La tosse", english: "Une toux" },
      { italian: "Qualcosa per…", english: "Quelque chose pour…" },
      { italian: "Quante volte al giorno?", english: "Combien de fois par jour ?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno. Ho bisogno di qualcosa per il mal di testa.", translation: "Bonjour. J'ai besoin de quelque chose pour le mal de tête." },
      { speaker: "Farmacista", line: "Ha la ricetta?", translation: "Avez-vous une ordonnance ?" },
      { speaker: "Cliente", line: "No, è senza ricetta.", translation: "Non, c'est sans ordonnance." },
      { speaker: "Farmacista", line: "Allora le do queste compresse. Due volte al giorno.", translation: "Je vous donne ces comprimés. Deux fois par jour." },
      { speaker: "Cliente", line: "Grazie. Ho anche la tosse.", translation: "Merci. J'ai aussi la toux." },
      { speaker: "Farmacista", line: "Prenda questo sciroppo, tre volte al giorno dopo i pasti.", translation: "Prenez ce sirop, trois fois par jour après les repas." },
    ],
    grammar: {
      title: "Impératif — Donner des instructions",
      points: [
        { italian: "Prenda queste pillole", english: "Prenez ces pilules (ordre formel)" },
        { italian: "Beva molta acqua", english: "Buvez beaucoup d'eau" },
        { italian: "Riposi a casa", english: "Reposez-vous à la maison" },
        { italian: "Torni domani", english: "Revenez demain" },
      ],
      note: "L'impératif formel (forme Lei) est utilisé par les professionnels. Il ressemble à la troisième personne du singulier — un ordre poli.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a pharmacist. Reply in French. Use lesson 13 vocabulary. Correct gently.",
  },
  {
    id: 14, title: "Au Téléphone", subtitle: "Al Telefono", free: false,
    keywords: [
      { italian: "Pronto!", english: "Allô ! (en répondant)" },
      { italian: "Con chi parlo?", english: "Qui est à l'appareil ?" },
      { italian: "Posso parlare con…?", english: "Puis-je parler à… ?" },
      { italian: "Un momento", english: "Un moment" },
      { italian: "Richiamare", english: "Rappeler" },
      { italian: "È occupato", english: "La ligne est occupée" },
    ],
    dialogue: [
      { speaker: "A", line: "Pronto?", translation: "Allô ?" },
      { speaker: "B", line: "Buongiorno! Posso parlare con la signora Bianchi?", translation: "Bonjour ! Puis-je parler à Mme Bianchi ?" },
      { speaker: "A", line: "Sono io. Con chi parlo?", translation: "C'est elle-même. Qui est à l'appareil ?" },
      { speaker: "B", line: "Sono Marco Rossi, chiamo per la prenotazione.", translation: "Je suis Marco Rossi, j'appelle pour la réservation." },
      { speaker: "A", line: "Mi dispiace, la linea è occupata. Può richiamare?", translation: "Je suis désolé, la ligne est occupée. Pouvez-vous rappeler ?" },
      { speaker: "B", line: "Certo, richiamo più tardi. Grazie!", translation: "Bien sûr, je rappellerai plus tard. Merci !" },
    ],
    grammar: {
      title: "Potere + Infinitif — Demander la permission",
      points: [
        { italian: "Posso richiamare?", english: "Puis-je rappeler ?" },
        { italian: "Può aspettare?", english: "Pouvez-vous attendre ? (formel)" },
        { italian: "Non posso sentire", english: "Je ne peux pas entendre" },
      ],
      note: "Au téléphone, les Italiens disent toujours \"Pronto !\" en répondant — cela signifie \"prêt\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing phone calls. Reply in French. Use lesson 14 vocabulary. Correct gently.",
  },
  {
    id: 15, title: "À la Poste", subtitle: "All'Ufficio Postale", free: false,
    keywords: [
      { italian: "Spedire un pacco", english: "Envoyer un colis" },
      { italian: "Una lettera / una busta", english: "Une lettre / une enveloppe" },
      { italian: "Per via aerea", english: "Par voie aérienne" },
      { italian: "Quanto ci vuole?", english: "Combien de temps faut-il ?" },
      { italian: "Il francobollo", english: "Le timbre" },
      { italian: "Raccomandata", english: "Courrier recommandé" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Vorrei spedire questo pacco in Inghilterra.", translation: "Bonjour ! Je voudrais envoyer ce colis en Angleterre." },
      { speaker: "Impiegato", line: "Per via aerea o normale?", translation: "Par voie aérienne ou normale ?" },
      { speaker: "Cliente", line: "Aerea. Quanto ci vuole?", translation: "Aérienne. Combien de temps faut-il ?" },
      { speaker: "Impiegato", line: "Circa cinque giorni lavorativi.", translation: "Environ cinq jours ouvrables." },
      { speaker: "Cliente", line: "Va bene. E vorrei anche tre francobolli.", translation: "Très bien. Je voudrais aussi trois timbres." },
    ],
    grammar: {
      title: "Ci vuole / Ci vogliono — Il faut / Ça prend",
      points: [
        { italian: "Ci vuole un'ora", english: "Ça prend une heure" },
        { italian: "Ci vogliono tre giorni", english: "Ça prend trois jours" },
        { italian: "Quanto ci vuole?", english: "Combien de temps faut-il ?" },
        { italian: "Ci vuole pazienza!", english: "Il faut de la patience !" },
      ],
      note: "\"Ci vuole\" est parfaitement pratique — utilisez-le pour dire combien de temps quelque chose prend.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a post office clerk. Reply in French. Use lesson 15 vocabulary. Correct gently.",
  },
  {
    id: 16, title: "Louer une Voiture", subtitle: "Noleggiare un'Auto", free: false,
    keywords: [
      { italian: "Noleggiare un'auto", english: "Louer une voiture" },
      { italian: "La patente", english: "Le permis de conduire" },
      { italian: "Il pieno", english: "Plein d'essence" },
      { italian: "L'assicurazione", english: "L'assurance" },
      { italian: "Quanti chilometri?", english: "Combien de kilomètres ?" },
      { italian: "Riconsegnare", english: "Rendre (la voiture)" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Vorrei noleggiare un'auto per tre giorni.", translation: "Bonjour ! Je voudrais louer une voiture pour trois jours." },
      { speaker: "Agente", line: "Certo. Ha la patente con sé?", translation: "Bien sûr. Avez-vous votre permis avec vous ?" },
      { speaker: "Cliente", line: "Sì, eccola. L'assicurazione è inclusa?", translation: "Oui, le voilà. L'assurance est-elle incluse ?" },
      { speaker: "Agente", line: "Sì, quella base è inclusa. Vuole quella completa?", translation: "Oui, l'assurance de base est incluse. Voulez-vous la complète ?" },
      { speaker: "Cliente", line: "Sì, meglio. I chilometri sono illimitati?", translation: "Oui, c'est mieux. Les kilomètres sont-ils illimités ?" },
      { speaker: "Agente", line: "Sì, nessun limite.", translation: "Oui, aucune limite." },
    ],
    grammar: {
      title: "Dovere — Devoir",
      points: [
        { italian: "Devo riconsegnare l'auto", english: "Je dois rendre la voiture" },
        { italian: "Deve avere la patente", english: "Vous devez avoir un permis (formel)" },
        { italian: "Dobbiamo fare il pieno", english: "Nous devons faire le plein" },
      ],
      note: "\"Dovere\" exprime l'obligation — associez-le à un infinitif. L'un des trois verbes modaux clés : potere, volere, dovere.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a car rental agent. Reply in French. Use lesson 16 vocabulary. Correct gently.",
  },
  {
    id: 17, title: "À la Plage", subtitle: "In Spiaggia", free: false,
    keywords: [
      { italian: "Un ombrellone", english: "Un parasol de plage" },
      { italian: "Una sdraio", english: "Un transat" },
      { italian: "La crema solare", english: "La crème solaire" },
      { italian: "Il mare è mosso", english: "La mer est agitée" },
      { italian: "Fare il bagno", english: "Se baigner" },
      { italian: "Che caldo!", english: "Quelle chaleur !" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Buongiorno! Vorrei un ombrellone e due sdraio.", translation: "Bonjour ! Je voudrais un parasol et deux transats." },
      { speaker: "Bagnino", line: "Certo! Prima fila o seconda?", translation: "Bien sûr ! Premier rang ou deuxième ?" },
      { speaker: "Turista", line: "Seconda va bene. Si può fare il bagno?", translation: "Le deuxième, c'est bien. On peut se baigner ?" },
      { speaker: "Bagnino", line: "Sì, il mare è calmo oggi. Che caldo!", translation: "Oui, la mer est calme aujourd'hui. Quelle chaleur !" },
    ],
    grammar: {
      title: "Fare — Le verbe « Faire »",
      points: [
        { italian: "Faccio una passeggiata", english: "Je me promène" },
        { italian: "Fa caldo / fa freddo", english: "Il fait chaud / il fait froid (météo)" },
        { italian: "Fai il bagno?", english: "Tu te baignes ?" },
        { italian: "Fanno un castello di sabbia", english: "Ils font un château de sable" },
      ],
      note: "\"Fare\" est l'un des verbes italiens les plus polyvalents — météo, activités, actions.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a beach attendant. Reply in French. Use lesson 17 vocabulary. Correct gently.",
  },
  {
    id: 18, title: "Parler de la Famille", subtitle: "La Famiglia", free: false,
    keywords: [
      { italian: "Il marito / la moglie", english: "Mari / femme" },
      { italian: "I figli", english: "Les enfants" },
      { italian: "Il fratello / la sorella", english: "Frère / sœur" },
      { italian: "I genitori", english: "Les parents" },
      { italian: "Sei sposato/a?", english: "Tu es marié(e) ?" },
      { italian: "Hai figli?", english: "Tu as des enfants ?" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei sposato?", translation: "Tu es marié ?" },
      { speaker: "B", line: "Sì, ho una moglie e due figli. E tu?", translation: "Oui, j'ai une femme et deux enfants. Et toi ?" },
      { speaker: "A", line: "Sono fidanzata. Ci sposiamo l'anno prossimo!", translation: "Je suis fiancée. Nous nous marions l'année prochaine !" },
      { speaker: "B", line: "Congratulazioni! Hai fratelli o sorelle?", translation: "Félicitations ! Tu as des frères ou sœurs ?" },
      { speaker: "A", line: "Ho una sorella. I miei genitori vivono a Napoli.", translation: "J'ai une sœur. Mes parents vivent à Naples." },
    ],
    grammar: {
      title: "Possessifs — Mon, ton, son/sa",
      points: [
        { italian: "Il mio gatto", english: "Mon chat" },
        { italian: "Il tuo gelato", english: "Ta glace" },
        { italian: "La sua mamma", english: "Sa maman" },
        { italian: "I nostri vicini", english: "Nos voisins" },
      ],
      note: "Les possessifs italiens s'accordent en genre et en nombre avec le nom, pas avec le possesseur.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a conversation about family. Reply in French. Use lesson 18 vocabulary. Correct gently.",
  },
  {
    id: 19, title: "Chez le Médecin", subtitle: "Dal Medico", free: false,
    keywords: [
      { italian: "Ho un appuntamento", english: "J'ai un rendez-vous" },
      { italian: "Da quanto tempo?", english: "Depuis quand / combien de temps ?" },
      { italian: "Ho la nausea", english: "J'ai la nausée" },
      { italian: "La pressione", english: "La tension artérielle" },
      { italian: "Fare una visita", english: "Faire une consultation" },
      { italian: "La diagnosi", english: "Le diagnostic" },
    ],
    dialogue: [
      { speaker: "Paziente", line: "Buongiorno, ho un appuntamento con il dottor Marini.", translation: "Bonjour, j'ai un rendez-vous avec le docteur Marini." },
      { speaker: "Dottore", line: "Da quanto tempo ha questi sintomi?", translation: "Depuis combien de temps avez-vous ces symptômes ?" },
      { speaker: "Paziente", line: "Da due giorni. Ho anche un po' di febbre.", translation: "Depuis deux jours. J'ai aussi un peu de fièvre." },
      { speaker: "Dottore", line: "Le misuro la pressione. Respiri profondamente.", translation: "Je vais prendre votre tension. Respirez profondément." },
      { speaker: "Dottore", line: "Non è grave. Le scrivo una ricetta.", translation: "Ce n'est pas grave. Je vais vous faire une ordonnance." },
    ],
    grammar: {
      title: "Da — Depuis / Pendant (temps)",
      points: [
        { italian: "Da due giorni", english: "Depuis deux jours (en cours)" },
        { italian: "Vivo qui da un anno", english: "Je vis ici depuis un an" },
        { italian: "Da stamattina", english: "Depuis ce matin" },
        { italian: "Da quanto tempo?", english: "Depuis quand ?" },
      ],
      note: "En italien, \"da\" + présent décrit quelque chose d'en cours depuis le passé — une logique similaire au français avec \"depuis\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a doctor. Reply in French. Use lesson 19 vocabulary. Correct gently.",
  },
  {
    id: 20, title: "Sortir le Soir", subtitle: "Uscire la Sera", free: false,
    keywords: [
      { italian: "Andiamo a ballare?", english: "On va danser ?" },
      { italian: "Un locale", english: "Un lieu / une boîte / un bar" },
      { italian: "C'è la fila", english: "Il y a la queue" },
      { italian: "Offro io", english: "C'est ma tournée" },
      { italian: "Fare tardi", english: "Rentrer tard" },
      { italian: "Che serata!", english: "Quelle soirée !" },
    ],
    dialogue: [
      { speaker: "A", line: "Allora, andiamo a ballare stasera?", translation: "Alors, on va danser ce soir ?" },
      { speaker: "B", line: "Sì! Conosco un bel locale in centro.", translation: "Oui ! Je connais un super endroit en centre-ville." },
      { speaker: "A", line: "C'è la fila di solito?", translation: "Il y a souvent la queue ?" },
      { speaker: "B", line: "A volte sì, ma entriamo con la lista.", translation: "Parfois oui, mais on est sur la liste." },
      { speaker: "B", line: "Un aperitivo — offro io!", translation: "Un apéritif — c'est ma tournée !" },
    ],
    grammar: {
      title: "Andare — Aller (+ lieux)",
      points: [
        { italian: "Vado al bar", english: "Je vais au bar" },
        { italian: "Va bene!", english: "Ça va ! / D'accord !" },
        { italian: "Andiamo a ballare", english: "Allons danser" },
        { italian: "Vai a casa?", english: "Tu rentres chez toi ?" },
      ],
      note: "\"Andiamo\" (allons-y) est l'un des mots les plus utiles de la vie sociale italienne. \"Va bene\" est utilisé constamment.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend planning a night out. Reply in French. Use lesson 20 vocabulary. Correct gently.",
  },
  {
    id: 21, title: "Cuisine et Recettes", subtitle: "Cibo e Cucina", free: false,
    keywords: [
      { italian: "La ricetta", english: "La recette" },
      { italian: "Gli ingredienti", english: "Les ingrédients" },
      { italian: "Cuocere / cucinare", english: "Cuisiner / cuire" },
      { italian: "Aggiungere", english: "Ajouter" },
      { italian: "Mescolare", english: "Mélanger" },
      { italian: "È pronto!", english: "C'est prêt !" },
    ],
    dialogue: [
      { speaker: "A", line: "Stai cucinando? Che profumo!", translation: "Tu cuisines ? Quelle bonne odeur !" },
      { speaker: "B", line: "Sto facendo la pasta al pomodoro. Vuoi la ricetta?", translation: "Je fais des pâtes à la tomate. Tu veux la recette ?" },
      { speaker: "A", line: "Sì! Quali ingredienti usi?", translation: "Oui ! Quels ingrédients tu utilises ?" },
      { speaker: "B", line: "Pomodori freschi, aglio, basilico e olio d'oliva.", translation: "Des tomates fraîches, de l'ail, du basilic et de l'huile d'olive." },
      { speaker: "A", line: "Aggiungi il sale, mescola e aspetta.", translation: "Ajoute le sel, mélange et attends." },
    ],
    grammar: {
      title: "Stare + Gérondif — Présent continu",
      points: [
        { italian: "Sto cucinando", english: "Je suis en train de cuisiner" },
        { italian: "Sta mangiando", english: "Il/Elle est en train de manger" },
        { italian: "Stiamo aspettando", english: "Nous sommes en train d'attendre" },
        { italian: "Cosa state facendo?", english: "Qu'est-ce que vous êtes en train de faire ?" },
      ],
      note: "L'italien a un présent continu formé avec \"stare\" + gérondif (-ando/-endo) pour ce qui se passe en ce moment.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend cooking. Reply in French. Use lesson 21 vocabulary. Correct gently.",
  },
  {
    id: 22, title: "À la Banque", subtitle: "In Banca", free: false,
    keywords: [
      { italian: "Aprire un conto", english: "Ouvrir un compte" },
      { italian: "Il bancomat", english: "Le distributeur / la carte de débit" },
      { italian: "Prelevare", english: "Retirer de l'argent" },
      { italian: "Il tasso di cambio", english: "Le taux de change" },
      { italian: "Fare un bonifico", english: "Faire un virement" },
      { italian: "Lo sportello", english: "Le guichet" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno. Vorrei prelevare dei contanti.", translation: "Bonjour. Je voudrais retirer de l'argent liquide." },
      { speaker: "Impiegato", line: "Si accomodi allo sportello tre.", translation: "Veuillez vous rendre au guichet trois." },
      { speaker: "Cliente", line: "Qual è il tasso di cambio oggi?", translation: "Quel est le taux de change aujourd'hui ?" },
      { speaker: "Cliente", line: "Posso anche fare un bonifico?", translation: "Puis-je aussi faire un virement ?" },
      { speaker: "Impiegato", line: "Certo. Ha il codice IBAN del destinatario?", translation: "Bien sûr. Avez-vous le code IBAN du destinataire ?" },
    ],
    grammar: {
      title: "Les chiffres",
      points: [
        { italian: "Uno…dieci", english: "1–10" },
        { italian: "Undici…venti", english: "11–20" },
        { italian: "Cento / mille / un milione", english: "100 / 1 000 / 1 000 000" },
        { italian: "Virgola", english: "Point décimal (virgule en italien)" },
      ],
      note: "En italien, les décimales utilisent une virgule : \"1,17\" = uno virgola diciassette. Les milliers utilisent un point. L'inverse du français !",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a bank teller. Reply in French. Use lesson 22 vocabulary. Correct gently.",
  },
  {
    id: 23, title: "Faire des Projets", subtitle: "Fare Programmi", free: false,
    keywords: [
      { italian: "Sei libero/a?", english: "Tu es libre ?" },
      { italian: "Che ne dici di…?", english: "Qu'est-ce que tu penses de… ?" },
      { italian: "Mi va!", english: "Ça me va ! / Super !" },
      { italian: "Ci vediamo", english: "On se voit" },
      { italian: "Rimandare", english: "Reporter" },
      { italian: "Non vedo l'ora!", english: "J'ai hâte !" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei libera sabato?", translation: "Tu es libre samedi ?" },
      { speaker: "B", line: "Sì! Che ne dici di andare al museo?", translation: "Oui ! Qu'est-ce que tu penses d'aller au musée ?" },
      { speaker: "A", line: "Mi va! A che ora ci vediamo?", translation: "Ça me va ! On se retrouve à quelle heure ?" },
      { speaker: "B", line: "Alle dieci davanti all'ingresso?", translation: "À dix heures devant l'entrée ?" },
      { speaker: "A", line: "Perfetto. Non vedo l'ora!", translation: "Parfait. J'ai tellement hâte !" },
    ],
    grammar: {
      title: "Futur — Rapide et facile",
      points: [
        { italian: "Andrò al museo", english: "J'irai au musée" },
        { italian: "Sarà divertente", english: "Ce sera amusant" },
        { italian: "Cosa farai?", english: "Qu'est-ce que tu feras ?" },
        { italian: "Ci vediamo domani", english: "On se voit demain (présent pour futur proche)" },
      ],
      note: "Les Italiens utilisent souvent le présent pour les projets proches. \"Domani vado al cinema\" est plus naturel que le futur.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend making plans. Reply in French. Use lesson 23 vocabulary. Correct gently.",
  },
  {
    id: 24, title: "Parler de la Météo", subtitle: "Il Tempo", free: false,
    keywords: [
      { italian: "Che tempo fa?", english: "Quel temps fait-il ?" },
      { italian: "Piove / nevica", english: "Il pleut / il neige" },
      { italian: "C'è il sole", english: "Il y a du soleil" },
      { italian: "Afoso", english: "Humide / lourd" },
      { italian: "Le previsioni", english: "Les prévisions" },
      { italian: "Portare un ombrello", english: "Prendre un parapluie" },
    ],
    dialogue: [
      { speaker: "A", line: "Che tempo fa oggi?", translation: "Quel temps fait-il aujourd'hui ?" },
      { speaker: "B", line: "È nuvoloso stamattina, ma nel pomeriggio c'è il sole.", translation: "C'est nuageux ce matin, mais ensoleillé cet après-midi." },
      { speaker: "A", line: "E domani? Hai visto le previsioni?", translation: "Et demain ? Tu as vu les prévisions ?" },
      { speaker: "B", line: "Sì, piove di mattina. Porta l'ombrello!", translation: "Oui, il pleut le matin. Prends un parapluie !" },
    ],
    grammar: {
      title: "Imparfait — Le passé (habitudes & descriptions)",
      points: [
        { italian: "Volevo andare al mare", english: "Je voulais aller à la mer" },
        { italian: "Faceva caldo", english: "Il faisait chaud (description dans le passé)" },
        { italian: "Quando ero piccolo…", english: "Quand j'étais jeune…" },
        { italian: "Di solito prendevo…", english: "J'avais l'habitude de prendre…" },
      ],
      note: "L'imparfait sert aux habitudes passées, aux descriptions et aux états prolongés.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor talking about the weather. Reply in French. Use lesson 24 vocabulary. Correct gently.",
  },
  {
    id: 25, title: "Au Parc", subtitle: "Al Parco", free: false,
    keywords: [
      { italian: "Il fiore", english: "La fleur" },
      { italian: "L'albero", english: "L'arbre" },
      { italian: "Il cane", english: "Le chien" },
      { italian: "La panchina", english: "Le banc" },
      { italian: "Bello / bella", english: "Beau / belle" },
      { italian: "Guarda!", english: "Regarde !" },
    ],
    dialogue: [
      { speaker: "A", line: "Guarda quel cane!", translation: "Regarde ce chien !" },
      { speaker: "B", line: "Che bello! È tuo?", translation: "Comme il est beau ! C'est le tien ?" },
      { speaker: "A", line: "No, ma vorrei averne uno.", translation: "Non, mais j'aimerais en avoir un." },
      { speaker: "B", line: "Mi piace quel fiore rosso là.", translation: "J'aime cette fleur rouge là-bas." },
      { speaker: "A", line: "Sediamoci sulla panchina?", translation: "On s'assoit sur le banc ?" },
    ],
    grammar: {
      title: "I Colori — Les couleurs",
      points: [
        { italian: "Rosso / rossa", english: "Rouge (m/f)" },
        { italian: "Verde", english: "Vert" },
        { italian: "Blu", english: "Bleu (invariable)" },
        { italian: "Giallo / gialla", english: "Jaune (m/f)" },
        { italian: "Un fiore rosso", english: "Une fleur rouge (l'adjectif suit le nom)" },
      ],
      note: "En italien, les couleurs sont des adjectifs qui s'accordent avec le nom. Blu et rosa ne changent jamais.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor taking a walk in an Italian park. Reply in French. Correct gently.",
  },
  {
    id: 26, title: "Décrire les Personnes", subtitle: "Parlare delle Persone", free: false,
    keywords: [
      { italian: "Alto / basso", english: "Grand / petit" },
      { italian: "Magro / robusto", english: "Mince / robuste" },
      { italian: "Simpatico / antipatico", english: "Sympathique / antipathique" },
      { italian: "Timido / estroverso", english: "Timide / extraverti(e)" },
      { italian: "I capelli", english: "Les cheveux" },
      { italian: "Gli occhi", english: "Les yeux" },
    ],
    dialogue: [
      { speaker: "A", line: "Conosci Marco?", translation: "Tu connais Marco ?" },
      { speaker: "B", line: "Sì! È alto e molto simpatico.", translation: "Oui ! Il est grand et très sympathique." },
      { speaker: "A", line: "Ha i capelli scuri, vero?", translation: "Il a les cheveux foncés, n'est-ce pas ?" },
      { speaker: "B", line: "Sì, e gli occhi verdi.", translation: "Oui, et les yeux verts." },
    ],
    grammar: {
      title: "Essere + Adjectifs pour les descriptions",
      points: [
        { italian: "È alto e magro", english: "Il est grand et mince" },
        { italian: "È simpatica", english: "Elle est sympathique" },
        { italian: "Ha i capelli biondi", english: "Il/Elle a les cheveux blonds" },
        { italian: "Ha gli occhi azzurri", english: "Il/Elle a les yeux bleus" },
      ],
      note: "Les descriptions physiques utilisent essere pour les qualités et avere pour les caractéristiques comme les cheveux et les yeux.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor helping describe people. Reply in French. Use lesson 26 vocabulary. Correct gently.",
  },
  {
    id: 27, title: "Avec les Voisins", subtitle: "Con i Vicini", free: false,
    keywords: [
      { italian: "Come va?", english: "Comment ça va ?" },
      { italian: "Stanco / stanca", english: "Fatigué(e)" },
      { italian: "Come mai?", english: "Comment ça se fait ? / Pourquoi ?" },
      { italian: "Ho dormito poco", english: "J'ai peu dormi" },
      { italian: "Tutto bene?", english: "Tout va bien ?" },
      { italian: "La settimana", english: "La semaine" },
    ],
    dialogue: [
      { speaker: "A", line: "Buongiorno! Come va?", translation: "Bonjour ! Comment ça va ?" },
      { speaker: "B", line: "Un po' stanca oggi.", translation: "Un peu fatiguée aujourd'hui." },
      { speaker: "A", line: "Come mai?", translation: "Comment ça se fait ?" },
      { speaker: "B", line: "Ho dormito poco stanotte.", translation: "J'ai peu dormi cette nuit." },
      { speaker: "A", line: "Meno male! Buona giornata!", translation: "Tant mieux ! Bonne journée !" },
    ],
    grammar: {
      title: "Expressions de conversation quotidienne",
      points: [
        { italian: "Come mai?", english: "Comment ça se fait ? / Pourquoi ça ?" },
        { italian: "Meno male!", english: "Dieu merci ! / Quel soulagement !" },
        { italian: "Abbastanza", english: "Assez / plutôt / suffisamment" },
        { italian: "Mi dispiace", english: "Je suis désolé(e)" },
      ],
      note: "Come mai est plus doux que perché — surprise légère. Meno male signifie littéralement \"moins mauvais\" — une expression italienne très appréciée.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friendly neighbour. Reply in French. Correct gently.",
  },
  {
    id: 28, title: "Parler de sa Journée", subtitle: "Parlare della Giornata", free: false,
    keywords: [
      { italian: "Ieri / oggi / domani", english: "Hier / aujourd'hui / demain" },
      { italian: "Stamattina / stasera", english: "Ce matin / ce soir" },
      { italian: "Ho lavorato", english: "J'ai travaillé (passé)" },
      { italian: "Sono partito/a", english: "Je suis parti(e) (passé)" },
      { italian: "Cosa hai fatto?", english: "Qu'est-ce que tu as fait ?" },
      { italian: "Tutto il giorno", english: "Toute la journée" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa hai fatto ieri?", translation: "Qu'est-ce que tu as fait hier ?" },
      { speaker: "B", line: "Ho lavorato tutto il giorno.", translation: "J'ai travaillé toute la journée." },
      { speaker: "B", line: "Sono andato al cinema con Marco.", translation: "Je suis allé au cinéma avec Marco." },
      { speaker: "A", line: "Bello! E domani?", translation: "Sympa ! Et demain ?" },
      { speaker: "B", line: "Domani partiamo per Roma.", translation: "Demain, on part pour Rome." },
    ],
    grammar: {
      title: "Passato Prossimo — Le passé récent",
      points: [
        { italian: "Ho lavorato", english: "J'ai travaillé (avere + participe passé)" },
        { italian: "Sono andato/a", english: "Je suis allé(e) (essere + participe passé)" },
        { italian: "Abbiamo fatto", english: "Nous avons fait" },
        { italian: "Sei partito/a?", english: "Tu es parti(e) ?" },
      ],
      note: "Le passato prossimo utilise avere ou essere + participe passé. Les verbes de mouvement prennent essere.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about the student's recent day. Reply in French. Correct gently.",
  },
  {
    id: 29, title: "Demander des Explications", subtitle: "Chiedere Spiegazioni", free: false,
    keywords: [
      { italian: "Perché?", english: "Pourquoi ?" },
      { italian: "Come mai?", english: "Comment ça se fait ?" },
      { italian: "Allora", english: "Donc / alors / eh bien" },
      { italian: "Quindi", english: "Par conséquent / donc" },
      { italian: "Non capisco", english: "Je ne comprends pas" },
      { italian: "Uno sciopero", english: "Une grève" },
    ],
    dialogue: [
      { speaker: "A", line: "Perché il treno è in ritardo?", translation: "Pourquoi le train est-il en retard ?" },
      { speaker: "B", line: "Perché c'è uno sciopero.", translation: "Parce qu'il y a une grève." },
      { speaker: "A", line: "Non capisco — c'è un altro treno?", translation: "Je ne comprends pas — il y a un autre train ?" },
      { speaker: "B", line: "Allora, provi l'autobus.", translation: "Eh bien, essayez le bus." },
    ],
    grammar: {
      title: "Perché — Pourquoi et Parce que",
      points: [
        { italian: "Perché sei in ritardo?", english: "Pourquoi es-tu en retard ? (question)" },
        { italian: "Perché c'è traffico", english: "Parce qu'il y a des embouteillages (réponse)" },
        { italian: "Non lo so", english: "Je ne sais pas" },
        { italian: "Forse", english: "Peut-être" },
      ],
      note: "Perché signifie à la fois \"pourquoi\" et \"parce que\" en italien. Allora s'entend constamment dans les conversations italiennes.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing situations where things go wrong. Reply in French. Correct gently.",
  },
  {
    id: 30, title: "Rêves et Désirs", subtitle: "Sogni e Desideri", free: false,
    keywords: [
      { italian: "Vorrei...", english: "Je voudrais… / J'aimerais…" },
      { italian: "Mi piacerebbe", english: "Cela me plairait" },
      { italian: "Magari", english: "Peut-être / si seulement" },
      { italian: "Forse", english: "Peut-être" },
      { italian: "Un giorno", english: "Un jour" },
      { italian: "Davvero?", english: "Vraiment ?" },
    ],
    dialogue: [
      { speaker: "A", line: "Vorrei vivere in Italia.", translation: "J'aimerais vivre en Italie." },
      { speaker: "B", line: "Davvero? In quale città?", translation: "Vraiment ? Dans quelle ville ?" },
      { speaker: "A", line: "Firenze. Mi piacerebbe molto.", translation: "Florence. Cela me plairait vraiment." },
      { speaker: "B", line: "Magari vengo anch'io!", translation: "Peut-être que je viendrai aussi !" },
      { speaker: "A", line: "Forse un giorno si può.", translation: "Peut-être qu'un jour c'est possible." },
    ],
    grammar: {
      title: "Conditionnel — Vorrei et Mi piacerebbe",
      points: [
        { italian: "Vorrei andare a Roma", english: "J'aimerais aller à Rome" },
        { italian: "Mi piacerebbe molto", english: "Cela me plairait beaucoup" },
        { italian: "Magari!", english: "Si seulement ! / J'aimerais tellement !" },
        { italian: "Sarebbe bello", english: "Ce serait beau" },
      ],
      note: "Magari peut signifier peut-être, si seulement, ou j'aimerais, selon le ton. Les Italiens adorent ce mot.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a conversation about wishes. Reply in French. Use lesson 30 vocabulary. Correct gently.",
  },
  {
    id: 31, title: "À la Maison", subtitle: "A Casa", free: false,
    keywords: [
      { italian: "Il soggiorno", english: "Le salon" },
      { italian: "La cucina", english: "La cuisine" },
      { italian: "Il divano", english: "Le canapé" },
      { italian: "Cucinare", english: "Cuisiner" },
      { italian: "Pulire", english: "Nettoyer" },
      { italian: "Rilassarsi", english: "Se détendre" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei a casa?", translation: "Tu es à la maison ?" },
      { speaker: "B", line: "Sì, sto cucinando in cucina.", translation: "Oui, je cuisine dans la cuisine." },
      { speaker: "A", line: "Dopo ti rilassi un po'?", translation: "Tu vas te détendre un peu après ?" },
      { speaker: "B", line: "Spero! Mi butto sul divano.", translation: "J'espère ! Je vais m'effondrer sur le canapé." },
    ],
    grammar: {
      title: "Verbes réfléchis — Verbi Riflessivi",
      points: [
        { italian: "Mi rilasso", english: "Je me détends" },
        { italian: "Ti svegli?", english: "Tu te réveilles ?" },
        { italian: "Si chiama", english: "Il/Elle s'appelle" },
        { italian: "Mi butto sul divano", english: "Je m'effondre sur le canapé" },
      ],
      note: "Les verbes réfléchis utilisent un pronom (mi, ti, si, ci, vi, si) renvoyant au sujet — pour les actions faites sur soi-même.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a cosy conversation about home. Reply in French. Use lesson 31 vocabulary. Correct gently.",
  },
  {
    id: 32, title: "La Routine Quotidienne", subtitle: "La Routine Quotidiana", free: false,
    keywords: [
      { italian: "Mi sveglio", english: "Je me réveille" },
      { italian: "Faccio colazione", english: "Je prends le petit-déjeuner" },
      { italian: "Mi vesto", english: "Je m'habille" },
      { italian: "Torno a casa", english: "Je rentre à la maison" },
      { italian: "Di solito", english: "D'habitude" },
      { italian: "Mi addormento", english: "Je m'endors" },
    ],
    dialogue: [
      { speaker: "A", line: "A che ora ti svegli di solito?", translation: "À quelle heure tu te réveilles d'habitude ?" },
      { speaker: "B", line: "Mi sveglio alle sette. Faccio colazione e poi mi vesto.", translation: "Je me réveille à sept heures. Je prends le petit-déjeuner et je m'habille." },
      { speaker: "A", line: "E vai a letto tardi?", translation: "Et tu te couches tard ?" },
      { speaker: "B", line: "No, mi addormento verso le undici.", translation: "Non, je m'endors vers onze heures." },
    ],
    grammar: {
      title: "Verbes réfléchis — La vie quotidienne",
      points: [
        { italian: "Mi sveglio alle 7", english: "Je me réveille à 7h" },
        { italian: "Mi lavo", english: "Je me lave" },
        { italian: "Mi vesto", english: "Je m'habille" },
        { italian: "Mi addormento", english: "Je m'endors" },
      ],
      note: "La routine quotidienne en italien est pleine de verbes réfléchis. Le pronom précède toujours le verbe conjugué.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about the student's daily routine. Reply in French. Correct gently.",
  },
  {
    id: 33, title: "Au Supermarché", subtitle: "Al Supermercato", free: false,
    keywords: [
      { italian: "Il carrello", english: "Le caddie / chariot" },
      { italian: "Il reparto", english: "Le rayon" },
      { italian: "La cassa", english: "La caisse" },
      { italian: "Mezzo chilo", english: "Un demi-kilo" },
      { italian: "In offerta", english: "En promotion" },
      { italian: "Dov'è il reparto...?", english: "Où est le rayon… ?" },
    ],
    dialogue: [
      { speaker: "A", line: "Scusi, dov'è il reparto latticini?", translation: "Excusez-moi, où est le rayon produits laitiers ?" },
      { speaker: "B", line: "È in fondo a destra.", translation: "C'est au fond à droite." },
      { speaker: "A", line: "Questo formaggio è in offerta?", translation: "Ce fromage est-il en promotion ?" },
      { speaker: "B", line: "Sì, prenda due e risparmia il 20%.", translation: "Oui, prenez-en deux et économisez 20 %." },
    ],
    grammar: {
      title: "Partitifs — Exprimer « du, de la, des »",
      points: [
        { italian: "Del pane", english: "Du pain (partitif)" },
        { italian: "Delle mele", english: "Des pommes (partitif)" },
        { italian: "Un chilo di pasta", english: "Un kilo de pâtes" },
        { italian: "Mezzo litro di latte", english: "Un demi-litre de lait" },
      ],
      note: "L'italien utilise del/della/dei/delle pour dire \"du/de la/des\". Vorrei del pane = Je voudrais du pain.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a supermarket assistant. Reply in French. Use lesson 33 vocabulary. Correct gently.",
  },
  {
    id: 34, title: "Dans le Bus", subtitle: "Sull'Autobus", free: false,
    keywords: [
      { italian: "Il biglietto", english: "Le billet" },
      { italian: "La fermata", english: "L'arrêt" },
      { italian: "Scendere", english: "Descendre" },
      { italian: "Salire", english: "Monter" },
      { italian: "Quante fermate?", english: "Combien d'arrêts ?" },
      { italian: "Devo cambiare?", english: "Je dois changer ?" },
    ],
    dialogue: [
      { speaker: "A", line: "Scusi, questo autobus va al centro?", translation: "Excusez-moi, ce bus va-t-il au centre ?" },
      { speaker: "B", line: "Sì, ma deve cambiare alla fermata San Marco.", translation: "Oui, mais vous devez changer à l'arrêt San Marco." },
      { speaker: "A", line: "Quante fermate sono?", translation: "C'est combien d'arrêts ?" },
      { speaker: "B", line: "Quattro fermate. Poi scende e aspetta il 14.", translation: "Quatre arrêts. Ensuite descendez et attendez le 14." },
    ],
    grammar: {
      title: "Dovere + Infinitif dans les transports en commun",
      points: [
        { italian: "Devo scendere qui", english: "Je dois descendre ici" },
        { italian: "Deve cambiare", english: "Vous devez changer (formel)" },
        { italian: "Devi comprare il biglietto", english: "Tu dois acheter un billet" },
      ],
      note: "Dans les transports, dovere (devoir) et potere (pouvoir) sont essentiels. Toujours associés à un infinitif.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a fellow passenger on an Italian bus. Reply in French. Correct gently.",
  },
  {
    id: 35, title: "Le Temps Libre", subtitle: "Il Tempo Libero", free: false,
    keywords: [
      { italian: "Leggere", english: "Lire" },
      { italian: "Guardare un film", english: "Regarder un film" },
      { italian: "Passeggiare", english: "Se promener" },
      { italian: "Ascoltare musica", english: "Écouter de la musique" },
      { italian: "Nel tempo libero", english: "Pendant mon temps libre" },
      { italian: "Mi annoio", english: "Je m'ennuie" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa fai nel tempo libero?", translation: "Qu'est-ce que tu fais pendant ton temps libre ?" },
      { speaker: "B", line: "Mi piace leggere e ascoltare musica.", translation: "J'aime lire et écouter de la musique." },
      { speaker: "A", line: "Guardi film italiani?", translation: "Tu regardes des films italiens ?" },
      { speaker: "B", line: "Sì! È il modo migliore per imparare.", translation: "Oui ! C'est la meilleure façon d'apprendre." },
    ],
    grammar: {
      title: "Les infinitifs comme noms",
      points: [
        { italian: "Mi piace leggere", english: "J'aime lire" },
        { italian: "Adoro cucinare", english: "J'adore cuisiner" },
        { italian: "Odio aspettare", english: "Je déteste attendre" },
        { italian: "Ho voglia di uscire", english: "J'ai envie de sortir" },
      ],
      note: "On utilise l'infinitif directement après mi piace, preferisco, adoro etc. pour parler d'activités qu'on aime.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a relaxed chat about hobbies. Reply in French. Correct gently.",
  },
  {
    id: 36, title: "Invitations et Refus", subtitle: "Inviti e Rifiuti", free: false,
    keywords: [
      { italian: "Ti va di...?", english: "Ça te dit de… ?" },
      { italian: "Volentieri!", english: "Avec plaisir !" },
      { italian: "Non posso", english: "Je ne peux pas" },
      { italian: "Peccato", english: "Quel dommage" },
      { italian: "Un'altra volta", english: "Une autre fois" },
      { italian: "Magari la prossima", english: "Peut-être la prochaine fois" },
    ],
    dialogue: [
      { speaker: "A", line: "Ti va di venire a cena stasera?", translation: "Ça te dit de venir dîner ce soir ?" },
      { speaker: "B", line: "Volentieri! A che ora?", translation: "Avec plaisir ! À quelle heure ?" },
      { speaker: "A", line: "Alle otto.", translation: "À huit heures." },
      { speaker: "B", line: "Se non può, peccato — un'altra volta.", translation: "S'il ne peut pas, quel dommage — une autre fois." },
    ],
    grammar: {
      title: "Verbes modaux — Invitations et refus",
      points: [
        { italian: "Non posso venire", english: "Je ne peux pas venir" },
        { italian: "Dovrei restare", english: "Je devrais rester" },
        { italian: "Potremmo andare", english: "Nous pourrions y aller" },
        { italian: "Ti va di...?", english: "Ça te dit de… ? (expression figée)" },
      ],
      note: "Ti va di...? est l'une des expressions d'invitation les plus utiles — décontractée et chaleureuse. Peccato adoucit un refus magnifiquement.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing invitations. Reply in French. Use lesson 36 vocabulary. Correct gently.",
  },
  {
    id: 37, title: "Ma Ville", subtitle: "La Mia Città", free: false,
    keywords: [
      { italian: "Ciò che mi piace di più", english: "Ce que j'aime le plus" },
      { italian: "La cosa più interessante", english: "La chose la plus intéressante" },
      { italian: "Quello che non mi piace tanto", english: "Ce que je n'aime pas trop" },
      { italian: "Il quartiere", english: "Le quartier" },
      { italian: "Vivace / tranquillo", english: "Animé / calme" },
      { italian: "Mi manca", english: "Il/Elle me manque" },
    ],
    dialogue: [
      { speaker: "A", line: "Di dove sei?", translation: "D'où es-tu ?" },
      { speaker: "B", line: "Sono di Napoli.", translation: "Je suis de Naples." },
      { speaker: "A", line: "Cosa ti piace di più?", translation: "Qu'est-ce que tu aimes le plus là-bas ?" },
      { speaker: "B", line: "Ciò che mi piace di più è il mare e il cibo.", translation: "Ce que j'aime le plus, c'est la mer et la nourriture." },
      { speaker: "B", line: "Quello che non sopporto è il caos del traffico.", translation: "Ce que je ne supporte pas, c'est le chaos de la circulation." },
    ],
    grammar: {
      title: "Propositions relatives — Ciò che / Quello che",
      points: [
        { italian: "Ciò che mi piace", english: "Ce que j'aime (ce qui me plaît)" },
        { italian: "Quello che voglio", english: "Ce que je veux" },
        { italian: "Non è quello che pensavo", english: "Ce n'est pas ce que je pensais" },
        { italian: "Tutto ciò che sai", english: "Tout ce que tu sais" },
      ],
      note: "Ciò che et quello che signifient tous les deux \"ce que\". Interchangeables pour exprimer des préférences avec élégance.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor talking about Italian cities. Reply in French. Correct gently.",
  },
  {
    id: 38, title: "Pressé !", subtitle: "Di Fretta", free: false,
    keywords: [
      { italian: "Siamo in ritardo!", english: "On est en retard !" },
      { italian: "Aspettami!", english: "Attends-moi !" },
      { italian: "Forza!", english: "Allez !" },
      { italian: "Sbrigati!", english: "Dépêche-toi !" },
      { italian: "Prendo la valigia", english: "Je prends la valise" },
      { italian: "Corri!", english: "Cours !" },
    ],
    dialogue: [
      { speaker: "A", line: "Sbrigati! Siamo in ritardo!", translation: "Dépêche-toi ! On est en retard !" },
      { speaker: "B", line: "Aspettami, prendo la valigia.", translation: "Attends-moi, je prends la valise." },
      { speaker: "A", line: "Prendila e vieni, forza!", translation: "Prends-la et viens, allez !" },
      { speaker: "A", line: "Dai, corri! Il treno parte tra cinque minuti.", translation: "Allez, cours ! Le train part dans cinq minutes." },
    ],
    grammar: {
      title: "Impératif informel — Ordres avec pronoms",
      points: [
        { italian: "Aspetta! / Aspettami!", english: "Attends ! / Attends-moi !" },
        { italian: "Sbrigati!", english: "Dépêche-toi ! (impératif réfléchi)" },
        { italian: "Prendila!", english: "Prends-le ! (pronom attaché au verbe)" },
        { italian: "Aiutami!", english: "Aide-moi !" },
      ],
      note: "Dans les ordres informels, les pronoms s'attachent à la fin du verbe : prendila, aspettami, aiutami.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing a rushed situation. Reply in French. Correct gently.",
  },
  {
    id: 39, title: "Dimanche entre Amis", subtitle: "Domenica con gli Amici", free: false,
    keywords: [
      { italian: "Vi va di...?", english: "Ça vous dit de… ?" },
      { italian: "Preferirei", english: "Je préférerais" },
      { italian: "L'agriturismo", english: "Restaurant de campagne / ferme-auberge" },
      { italian: "È affollato", english: "C'est bondé" },
      { italian: "Non si trova parcheggio", english: "On ne trouve pas de parking" },
      { italian: "Che ne dite?", english: "Qu'est-ce que vous en pensez ?" },
    ],
    dialogue: [
      { speaker: "A", line: "Vi va di andare al mare domenica?", translation: "Ça vous dit d'aller à la mer dimanche ?" },
      { speaker: "B", line: "Preferirei andare a mangiare in un agriturismo.", translation: "Je préférerais aller manger dans une ferme-auberge." },
      { speaker: "C", line: "Anch'io — la spiaggia è sempre affollata.", translation: "Moi aussi — la plage est toujours bondée." },
      { speaker: "B", line: "Conosco un posto bellissimo in collina. Che ne dite?", translation: "Je connais un endroit magnifique dans les collines. Qu'est-ce que vous en pensez ?" },
    ],
    grammar: {
      title: "Si Impersonale — Le si impersonnel",
      points: [
        { italian: "Non si trova parcheggio", english: "On ne trouve pas de parking" },
        { italian: "Si mangia bene qui", english: "On mange bien ici" },
        { italian: "Come si dice?", english: "Comment dit-on ?" },
        { italian: "Non si sa mai", english: "On ne sait jamais" },
      ],
      note: "Le si impersonnel n'a pas de sujet spécifique — comme \"on\" en français. Come si dice? est essentiel pour les apprenants !",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing friends planning a Sunday outing. Reply in French. Correct gently.",
  },
  {
    id: 40, title: "Il me semble / Je me souviens", subtitle: "Mi Sembra e Mi Ricordo", free: false,
    keywords: [
      { italian: "Mi sembra che", english: "Il me semble que" },
      { italian: "Mi pare", english: "Il me semble / il paraît" },
      { italian: "Ti ricordi?", english: "Tu te souviens ?" },
      { italian: "Mi ricordo", english: "Je me souviens" },
      { italian: "Non mi ricordo", english: "Je ne me souviens pas" },
      { italian: "Mi sembra ieri", english: "C'est comme si c'était hier" },
    ],
    dialogue: [
      { speaker: "A", line: "Ti ricordi di quella vacanza a Capri?", translation: "Tu te souviens de ces vacances à Capri ?" },
      { speaker: "B", line: "Certo! Mi sembra ieri.", translation: "Bien sûr ! C'est comme si c'était hier." },
      { speaker: "A", line: "Ti ricordi quel ristorante sul mare?", translation: "Tu te souviens de ce restaurant au bord de la mer ?" },
      { speaker: "B", line: "Mi pare di sì, ma non mi ricordo il nome.", translation: "Je crois que oui, mais je ne me souviens pas du nom." },
    ],
    grammar: {
      title: "Verbes réfléchis — Mémoire et perception",
      points: [
        { italian: "Mi ricordo", english: "Je me souviens" },
        { italian: "Ti ricordi?", english: "Tu te souviens ?" },
        { italian: "Si ricorda", english: "Il/Elle se souvient (aussi vous formel)" },
        { italian: "Mi sembra / mi pare", english: "Il me semble (interchangeable)" },
      ],
      note: "Ricordarsi est réfléchi : mi ricordo, ti ricordi, si ricorda etc. Mi sembra et mi pare sont interchangeables.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a nostalgic conversation. Reply in French. Correct gently.",
  },
  {
    id: 41, title: "Parler du Passé", subtitle: "Parlare del Passato", free: false,
    keywords: [
      { italian: "Ho fatto", english: "J'ai fait" },
      { italian: "Ho mangiato", english: "J'ai mangé" },
      { italian: "Sono andato/a", english: "Je suis allé(e)" },
      { italian: "Siamo arrivati", english: "Nous sommes arrivés" },
      { italian: "L'anno scorso", english: "L'année dernière" },
      { italian: "La settimana scorsa", english: "La semaine dernière" },
    ],
    dialogue: [
      { speaker: "A", line: "Come hai passato il weekend?", translation: "Comment tu as passé le week-end ?" },
      { speaker: "B", line: "Sono andato a Venezia con mia moglie.", translation: "Je suis allé à Venise avec ma femme." },
      { speaker: "A", line: "Avete mangiato bene?", translation: "Vous avez bien mangé ?" },
      { speaker: "B", line: "Benissimo! Ho mangiato il miglior risotto della mia vita.", translation: "À merveille ! J'ai mangé le meilleur risotto de ma vie." },
    ],
    grammar: {
      title: "Passato Prossimo — Avere ou Essere",
      points: [
        { italian: "Ho mangiato (avere)", english: "J'ai mangé — la plupart des verbes utilisent avere" },
        { italian: "Sono andato/a (essere)", english: "Je suis allé(e) — les verbes de mouvement utilisent essere" },
        { italian: "Siamo arrivati (essere)", english: "Nous sommes arrivés — le participe s'accorde" },
        { italian: "Non ho capito", english: "Je n'ai pas compris" },
      ],
      note: "Les verbes de mouvement et réfléchis utilisent essere. Tous les autres utilisent avere. Avec essere, le participe s'accorde.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about recent activities. Reply in French. Correct gently.",
  },
  {
    id: 42, title: "Souvenirs d'Enfance", subtitle: "Ricordi d'Infanzia", free: false,
    keywords: [
      { italian: "Quando ero piccolo/a", english: "Quand j'étais jeune" },
      { italian: "Giocavo", english: "Je jouais" },
      { italian: "La scuola", english: "L'école" },
      { italian: "D'estate", english: "En été" },
      { italian: "Ogni giorno", english: "Tous les jours" },
      { italian: "Mi piaceva", english: "J'aimais" },
    ],
    dialogue: [
      { speaker: "A", line: "Com'era la tua infanzia?", translation: "Comment était ton enfance ?" },
      { speaker: "B", line: "Bellissima! D'estate giocavo sempre fuori.", translation: "Magnifique ! En été, je jouais toujours dehors." },
      { speaker: "A", line: "E la scuola? Ti piaceva?", translation: "Et l'école ? Tu aimais ça ?" },
      { speaker: "B", line: "Mi piaceva la matematica.", translation: "J'aimais les maths." },
      { speaker: "A", line: "Quando ero piccola, volevo fare la ballerina.", translation: "Quand j'étais petite, je voulais être danseuse." },
    ],
    grammar: {
      title: "Imparfait — Habitudes et états dans le passé",
      points: [
        { italian: "Giocavo ogni giorno", english: "Je jouais tous les jours" },
        { italian: "Quando ero piccolo...", english: "Quand j'étais jeune..." },
        { italian: "Mi piaceva la scuola", english: "J'aimais l'école" },
        { italian: "Era bellissimo", english: "C'était merveilleux" },
      ],
      note: "L'imparfait décrit les états, habitudes et émotions passés. Ho mangiato la pizza (une fois) vs Mangiavo la pizza ogni venerdì (chaque vendredi).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a nostalgic conversation about childhood. Reply in French. Correct gently.",
  },
  {
    id: 43, title: "Exprimer ses Opinions", subtitle: "Esprimere Opinioni", free: false,
    keywords: [
      { italian: "Secondo me", english: "À mon avis" },
      { italian: "Penso che", english: "Je pense que" },
      { italian: "Mi sembra", english: "Il me semble" },
      { italian: "Mi pare", english: "Il me semble (même sens)" },
      { italian: "Sono d'accordo", english: "Je suis d'accord" },
      { italian: "Hai ragione", english: "Tu as raison" },
    ],
    dialogue: [
      { speaker: "A", line: "Secondo te, qual è la città più bella d'Italia?", translation: "À ton avis, quelle est la plus belle ville d'Italie ?" },
      { speaker: "B", line: "Secondo me, Firenze. Mi sembra unica.", translation: "À mon avis, Florence. Elle me semble unique." },
      { speaker: "A", line: "Penso che Roma sia più interessante.", translation: "Je pense que Rome est plus intéressante." },
      { speaker: "B", line: "Hai ragione, Roma è straordinaria.", translation: "Tu as raison, Rome est extraordinaire." },
    ],
    grammar: {
      title: "Structures pour donner son avis",
      points: [
        { italian: "Secondo me...", english: "À mon avis… (lit. selon moi)" },
        { italian: "Mi sembra che", english: "Il me semble que" },
        { italian: "Sono / non sono d'accordo", english: "Je suis / je ne suis pas d'accord" },
        { italian: "Hai ragione", english: "Tu as raison" },
      ],
      note: "Secondo me est la façon la plus simple de donner son avis. Mi sembra et mi pare sont interchangeables et très courants.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a discussion about Italian cities. Reply in French. Correct gently.",
  },
  {
    id: 44, title: "Donner des Conseils", subtitle: "Dare Consigli", free: false,
    keywords: [
      { italian: "Dovresti", english: "Tu devrais" },
      { italian: "Ti consiglio di", english: "Je te conseille de" },
      { italian: "È meglio che", english: "Il vaut mieux que" },
      { italian: "Al posto tuo", english: "À ta place" },
      { italian: "Perché non...?", english: "Pourquoi tu ne… pas ?" },
      { italian: "Prova a", english: "Essaie de" },
    ],
    dialogue: [
      { speaker: "A", line: "Non riesco a dormire bene.", translation: "Je n'arrive pas à bien dormir." },
      { speaker: "B", line: "Dovresti andare a letto prima.", translation: "Tu devrais aller te coucher plus tôt." },
      { speaker: "B", line: "Ti consiglio di evitare il caffè la sera.", translation: "Je te conseille d'éviter le café le soir." },
      { speaker: "A", line: "Al posto tuo, cosa faresti?", translation: "Si tu étais moi, qu'est-ce que tu ferais ?" },
      { speaker: "B", line: "Perché non provi una camomilla prima di dormire?", translation: "Pourquoi tu n'essaies pas une camomille avant de dormir ?" },
    ],
    grammar: {
      title: "Conditionnel pour les conseils",
      points: [
        { italian: "Dovresti riposare", english: "Tu devrais te reposer" },
        { italian: "Potresti provare", english: "Tu pourrais essayer" },
        { italian: "Al posto tuo, andrei", english: "À ta place, j'irais" },
        { italian: "Ti consiglio di aspettare", english: "Je te conseille d'attendre" },
      ],
      note: "Dovresti (tu devrais) et potresti (tu pourrais) sont des formes conditionnelles — parfaites pour donner des conseils.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a wise friend giving advice. Reply in French. Correct gently.",
  },
  {
    id: 45, title: "Réel et Hypothétique", subtitle: "Reale e Ipotetico", free: false,
    keywords: [
      { italian: "Se ho i soldi, vado", english: "Si j'ai l'argent, j'y vais (possibilité réelle)" },
      { italian: "Se avessi i soldi, andrei", english: "Si j'avais l'argent, j'irais (hypothétique)" },
      { italian: "Magari potessi!", english: "Si seulement je pouvais !" },
      { italian: "Nel caso in cui", english: "Dans le cas où" },
      { italian: "Dipende da", english: "Ça dépend de" },
      { italian: "Chissà", english: "Qui sait / peut-être un jour" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa fai a luglio?", translation: "Qu'est-ce que tu fais en juillet ?" },
      { speaker: "B", line: "Se ho i soldi, vado in Sicilia.", translation: "Si j'ai l'argent, je vais en Sicile." },
      { speaker: "A", line: "Io sogno in grande — se avessi i soldi, andrei in Giappone!", translation: "Moi je rêve en grand — si j'avais l'argent, j'irais au Japon !" },
      { speaker: "B", line: "Magari potessi anch'io! Chissà, un giorno.", translation: "Si seulement je pouvais aussi ! Qui sait, un jour." },
      { speaker: "A", line: "Se vincessi alla lotteria, ci andremmo insieme!", translation: "Si je gagnais à la loterie, on irait ensemble !" },
    ],
    grammar: {
      title: "Conditionnels — Réel vs Hypothétique",
      points: [
        { italian: "Se ho tempo, vengo", english: "Si j'ai le temps, je viens (réel)" },
        { italian: "Se avessi tempo, verrei", english: "Si j'avais le temps, je viendrais (hypothétique)" },
        { italian: "Se fosse possibile", english: "Si c'était possible" },
        { italian: "Chissà", english: "Qui sait (exprime l'incertitude sur l'avenir)" },
      ],
      note: "Réel : se + présent. Hypothétique : se + subjonctif imparfait + conditionnel = quelque chose d'improbable ou imaginaire.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor exploring real and hypothetical situations. Reply in French. Correct gently.",
  },
];
