// lessons/pt.js — Portuguese (Brazilian) translations for all 45 lessons
// Italian lines (line, italian) are IDENTICAL to en.js — do not change them.
// Only: keywords[].english, dialogue[].translation, grammar.title/points/note differ.

export const LESSONS = [
  {
    id: 1, title: "Cumprimentos", subtitle: "Il Saluto", free: true,
    keywords: [
      { italian: "Ciao", english: "Oi / Tchau (informal)" },
      { italian: "Salve", english: "Olá (neutro/formal)" },
      { italian: "Buongiorno", english: "Bom dia / Boa tarde" },
      { italian: "Buonasera", english: "Boa noite" },
      { italian: "Arrivederci", english: "Adeus (formal)" },
      { italian: "Tutto bene", english: "Tudo bem / Está tudo bem" },
    ],
    dialogue: [
      { speaker: "A", line: "Buongiorno! Salve.", translation: "Bom dia! Olá." },
      { speaker: "B", line: "Ciao! Come stai?", translation: "Oi! Como você está?" },
      { speaker: "A", line: "Tutto bene, grazie. E tu?", translation: "Tudo bem, obrigado/a. E você?" },
      { speaker: "B", line: "Bene, grazie!", translation: "Bem, obrigado/a!" },
    ],
    grammar: {
      title: "Come — Como / O quê",
      points: [
        { italian: "Come stai?", english: "Como você está? (informal)" },
        { italian: "Come sta?", english: "Como o senhor/a senhora está? (formal)" },
        { italian: "Come va?", english: "Como vai?" },
        { italian: "Come?", english: "O quê? / Com licença?" },
      ],
      note: "\"Come\" significa literalmente \"como\" — é sua palavra-chave para perguntar sobre estados e situações.",
    },
    aiPrompt: "STRICT RULES: Only discuss vocabulary and grammar from this specific lesson. If asked about anything unrelated reply only: 'Let us stick to this lesson!' Never break character. Always reply in Portuguese, but use Italian words and phrases from the lesson. Correct the student gently. You are an Italian language tutor. The student just learned Lesson 1: Greetings. Help them practice: Ciao, Salve, Buongiorno, Buonasera, Arrivederci, Tutto bene, Come stai, Come va. Keep responses short and warm.",
  },
  {
    id: 2, title: "Se Apresentar", subtitle: "Presentarsi", free: false,
    keywords: [
      { italian: "Mi chiamo…", english: "Meu nome é…" },
      { italian: "Sono…", english: "Eu sou…" },
      { italian: "Piacere", english: "Prazer em conhecer" },
      { italian: "Di dove sei?", english: "De onde você é?" },
      { italian: "Sono di…", english: "Sou de…" },
      { italian: "Quanti anni hai?", english: "Quantos anos você tem?" },
    ],
    dialogue: [
      { speaker: "A", line: "Ciao! Sono Paolo.", translation: "Oi! Sou o Paolo." },
      { speaker: "B", line: "Ciao, Paolo. Sono Monica. Piacere!", translation: "Oi, Paolo. Sou a Monica. Prazer!" },
      { speaker: "A", line: "Piacere mio. Di dove sei?", translation: "O prazer é meu. De onde você é?" },
      { speaker: "B", line: "Sono di Firenze. E tu?", translation: "Sou de Florença. E você?" },
      { speaker: "A", line: "Sono di Milano.", translation: "Sou de Milão." },
    ],
    grammar: {
      title: "Essere — O verbo «Ser/Estar»",
      points: [
        { italian: "Io sono", english: "Eu sou" },
        { italian: "Tu sei", english: "Você é (informal)" },
        { italian: "Lei è", english: "O senhor/a senhora é (formal) / Ela é" },
        { italian: "Lui è", english: "Ele é" },
        { italian: "Noi siamo", english: "Nós somos" },
        { italian: "Voi siete", english: "Vocês são" },
        { italian: "Loro sono", english: "Eles são" },
      ],
      note: "Em italiano, raramente é necessário dizer \"io\" (eu) — a terminação do verbo indica quem está falando.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor. Reply in Portuguese. Practice introductions: Mi chiamo, Sono, Piacere, Di dove sei, Sono di. Correct gently.",
  },
  {
    id: 3, title: "No Café", subtitle: "Al Bar", free: false,
    keywords: [
      { italian: "Un caffè, per favore", english: "Um café, por favor" },
      { italian: "Vorrei…", english: "Eu gostaria…" },
      { italian: "Quanto costa?", english: "Quanto custa?" },
      { italian: "Il conto", english: "A conta" },
      { italian: "Un cornetto", english: "Um croissant" },
      { italian: "Grazie mille", english: "Muito obrigado/a" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Un caffè, per favore.", translation: "Bom dia! Um café, por favor." },
      { speaker: "Barista", line: "Subito! Vuole anche un cornetto?", translation: "Já! Quer também um croissant?" },
      { speaker: "Cliente", line: "Sì, grazie. Quanto costa?", translation: "Sim, obrigado/a. Quanto é?" },
      { speaker: "Barista", line: "Un euro e cinquanta, prego.", translation: "Um euro e cinquenta, por favor." },
      { speaker: "Cliente", line: "Ecco. Grazie mille!", translation: "Aqui está. Muito obrigado/a!" },
    ],
    grammar: {
      title: "Vorrei — Pedidos educados",
      points: [
        { italian: "Vorrei un caffè", english: "Eu gostaria de um café" },
        { italian: "Vorrei il conto", english: "Eu gostaria da conta" },
        { italian: "Vorrei prenotare", english: "Eu gostaria de reservar" },
        { italian: "Vorrei un tavolo", english: "Eu gostaria de uma mesa" },
      ],
      note: "\"Vorrei\" é o condicional de \"volere\" (querer). Mais educado que \"voglio\" — use-o sempre em lojas e restaurantes.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a barista. Reply in Portuguese. Use lesson 3 vocabulary. Correct gently.",
  },
  {
    id: 4, title: "Na Sorveteria", subtitle: "In Gelateria", free: false,
    keywords: [
      { italian: "Un gelato", english: "Um sorvete" },
      { italian: "Che gusti?", english: "Quais sabores?" },
      { italian: "Cono o coppetta?", english: "Casquinha ou copinho?" },
      { italian: "Piccolo / medio / grande", english: "Pequeno / médio / grande" },
      { italian: "Che buono!", english: "Que delícia!" },
      { italian: "Posso assaggiare?", english: "Posso experimentar?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buonasera! Vorrei un gelato.", translation: "Boa noite! Eu gostaria de um sorvete." },
      { speaker: "Gelataio", line: "Certo! Cono o coppetta?", translation: "Claro! Casquinha ou copinho?" },
      { speaker: "Cliente", line: "Cono, grazie. Posso assaggiare il pistacchio?", translation: "Casquinha, obrigado/a. Posso experimentar o pistache?" },
      { speaker: "Gelataio", line: "Certo, ecco a lei.", translation: "Claro, aqui está." },
      { speaker: "Cliente", line: "Mmm, che buono! Pistacchio e cioccolato, per favore.", translation: "Mmm, que delícia! Pistache e chocolate, por favor." },
      { speaker: "Gelataio", line: "Piccolo, medio o grande?", translation: "Pequeno, médio ou grande?" },
      { speaker: "Cliente", line: "Medio. Quanto costa?", translation: "Médio. Quanto é?" },
      { speaker: "Gelataio", line: "Due euro e cinquanta.", translation: "Dois euros e cinquenta." },
    ],
    grammar: {
      title: "questo / quello — Este / Aquele",
      points: [
        { italian: "Questo gelato", english: "Este sorvete (por perto)" },
        { italian: "Quello lì", english: "Aquele ali (mais longe)" },
        { italian: "Questo è buono", english: "Este é bom" },
        { italian: "Qual è il migliore?", english: "Qual é o melhor?" },
      ],
      note: "Use \"questo\" para coisas próximas e \"quello\" para coisas mais distantes — a mesma lógica que este/aquele em português.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a gelateria worker. Reply in Portuguese. Use lesson 4 vocabulary. Correct gently.",
  },
  {
    id: 5, title: "Pedir Direções", subtitle: "Chiedere la Strada", free: false,
    keywords: [
      { italian: "Dov'è…?", english: "Onde fica…?" },
      { italian: "A destra", english: "À direita" },
      { italian: "A sinistra", english: "À esquerda" },
      { italian: "Sempre dritto", english: "Em frente / reto" },
      { italian: "Vicino / lontano", english: "Perto / longe" },
      { italian: "Scusi!", english: "Com licença! (formal)" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Scusi! Dov'è il Colosseo?", translation: "Com licença! Onde fica o Coliseu?" },
      { speaker: "Passante", line: "Allora… vada sempre dritto, poi a destra.", translation: "Vá em frente e depois vire à direita." },
      { speaker: "Turista", line: "È lontano?", translation: "É longe?" },
      { speaker: "Passante", line: "No, è vicino. Cinque minuti a piedi.", translation: "Não, é perto. Cinco minutos a pé." },
      { speaker: "Turista", line: "Grazie mille!", translation: "Muito obrigado/a!" },
      { speaker: "Passante", line: "Prego! Buona visita!", translation: "De nada! Boa visita!" },
    ],
    grammar: {
      title: "C'è / Ci sono — Tem / Há",
      points: [
        { italian: "C'è un autobus?", english: "Tem um ônibus?" },
        { italian: "Ci sono taxi?", english: "Tem táxis?" },
        { italian: "C'è una fermata vicino?", english: "Tem uma parada perto?" },
        { italian: "Non c'è problema", english: "Não tem problema" },
      ],
      note: "\"C'è\" e \"ci sono\" são suas expressões-chave para perguntar se algo existe ou está disponível.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a local Roman. Reply in Portuguese. Use lesson 5 vocabulary. Correct gently.",
  },
  {
    id: 6, title: "No Aeroporto", subtitle: "All'Aeroporto", free: false,
    keywords: [
      { italian: "Il volo", english: "O voo" },
      { italian: "Il passaporto", english: "O passaporte" },
      { italian: "Il bagaglio", english: "A bagagem" },
      { italian: "Quanti bagagli hai?", english: "Quantas malas você tem?" },
      { italian: "Il gate", english: "O portão" },
      { italian: "In ritardo / in orario", english: "Atrasado / no horário" },
    ],
    dialogue: [
      { speaker: "Agente", line: "Buongiorno! Il passaporto, per favore.", translation: "Bom dia! Seu passaporte, por favor." },
      { speaker: "Passeggero", line: "Eccolo. Ho anche un bagaglio da imbarcare.", translation: "Aqui está. Também tenho uma mala para despachar." },
      { speaker: "Agente", line: "Quanti bagagli ha?", translation: "Quantas malas o senhor/a senhora tem?" },
      { speaker: "Passeggero", line: "Solo uno. Il volo è in orario?", translation: "Só uma. O voo está no horário?" },
      { speaker: "Agente", line: "Sì, parte alle undici. Gate B7.", translation: "Sim, parte às onze. Portão B7." },
      { speaker: "Passeggero", line: "Grazie mille!", translation: "Muito obrigado/a!" },
    ],
    grammar: {
      title: "Avere — O verbo «Ter»",
      points: [
        { italian: "Io ho", english: "Eu tenho" },
        { italian: "Tu hai", english: "Você tem (informal)" },
        { italian: "Lei ha", english: "O senhor/a senhora tem (formal) / Ela tem" },
        { italian: "Lui ha", english: "Ele tem" },
        { italian: "Noi abbiamo", english: "Nós temos" },
        { italian: "Voi avete", english: "Vocês têm" },
        { italian: "Loro hanno", english: "Eles têm" },
      ],
      note: "\"Avere\" é um dos dois verbos mais importantes do italiano. Também usado para idade: \"ho trent'anni\" = tenho trinta anos.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing an airport agent. Reply in Portuguese. Use lesson 6 vocabulary. Correct gently.",
  },
  {
    id: 7, title: "No Restaurante", subtitle: "Al Ristorante", free: false,
    keywords: [
      { italian: "Un tavolo per due", english: "Uma mesa para dois" },
      { italian: "Il menù", english: "O cardápio" },
      { italian: "Il primo / il secondo", english: "O primeiro / segundo prato" },
      { italian: "Sono vegetariano/a", english: "Sou vegetariano/a" },
      { italian: "È compreso?", english: "Está incluído?" },
      { italian: "Il coperto", english: "A taxa de couvert" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buonasera! Un tavolo per due, per favore.", translation: "Boa noite! Uma mesa para dois, por favor." },
      { speaker: "Cameriere", line: "Certo, prego. Ecco il menù.", translation: "Claro. Aqui está o cardápio." },
      { speaker: "Cliente", line: "Grazie. Sono vegetariana — cosa consiglia?", translation: "Obrigado/a. Sou vegetariana — o que você recomenda?" },
      { speaker: "Cameriere", line: "Ottime le tagliatelle ai funghi!", translation: "O tagliatelle com cogumelos está excelente!" },
      { speaker: "Cliente", line: "Perfetto. E il coperto è compreso?", translation: "Perfeito. A taxa de couvert está incluída?" },
      { speaker: "Cameriere", line: "Sì, è già incluso. Buon appetito!", translation: "Sim, já está incluída. Bom apetite!" },
    ],
    grammar: {
      title: "Mi piace / Mi piacciono — Eu gosto",
      points: [
        { italian: "Mi piace la pasta", english: "Eu gosto de massa" },
        { italian: "Mi piacciono i funghi", english: "Eu gosto de cogumelos (plural)" },
        { italian: "Non mi piace", english: "Não gosto disso" },
        { italian: "Mi piace molto", english: "Gosto muito disso" },
      ],
      note: "\"Piacere\" funciona ao contrário — você diz \"a mim agrada\". Use \"piace\" para uma coisa, \"piacciono\" para várias.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a restaurant waiter. Reply in Portuguese. Use lesson 7 vocabulary. Correct gently.",
  },
  {
    id: 8, title: "Fazer Compras", subtitle: "Fare Shopping", free: false,
    keywords: [
      { italian: "Posso provarlo?", english: "Posso experimentar?" },
      { italian: "Che taglia?", english: "Qual é o tamanho?" },
      { italian: "È troppo caro", english: "É muito caro" },
      { italian: "C'è lo sconto?", english: "Tem desconto?" },
      { italian: "Lo prendo", english: "Vou levar" },
      { italian: "Accettate carte di credito?", english: "Vocês aceitam cartão de crédito?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Posso provare questa giacca?", translation: "Bom dia! Posso experimentar essa jaqueta?" },
      { speaker: "Commessa", line: "Certo! Che taglia porta?", translation: "Claro! Qual é o seu tamanho?" },
      { speaker: "Cliente", line: "La media, grazie.", translation: "Médio, obrigado/a." },
      { speaker: "Cliente", line: "Hmm… quanto costa?", translation: "Hmm… quanto custa?" },
      { speaker: "Commessa", line: "Centoventi euro. C'è il 20% di sconto oggi!", translation: "Cento e vinte euros. Tem 20% de desconto hoje!" },
      { speaker: "Cliente", line: "Perfetto, lo prendo! Accettate carte?", translation: "Perfeito, vou levar! Vocês aceitam cartão?" },
      { speaker: "Commessa", line: "Sì, certo.", translation: "Sim, claro." },
    ],
    grammar: {
      title: "Potere — Poder",
      points: [
        { italian: "Posso provarlo?", english: "Posso experimentar?" },
        { italian: "Puoi aiutarmi?", english: "Você pode me ajudar?" },
        { italian: "Possiamo pagare con la carta?", english: "Podemos pagar com cartão?" },
      ],
      note: "\"Potere\" é um verbo modal — combina-se com o infinitivo para pedir permissão e expressar capacidade.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a shop assistant. Reply in Portuguese. Use lesson 8 vocabulary. Correct gently.",
  },
  {
    id: 9, title: "No Hotel", subtitle: "In Albergo", free: false,
    keywords: [
      { italian: "Ho una prenotazione", english: "Tenho uma reserva" },
      { italian: "La camera", english: "O quarto" },
      { italian: "A che ora è il check-out?", english: "A que horas é o check-out?" },
      { italian: "La colazione è inclusa?", english: "O café da manhã está incluído?" },
      { italian: "C'è il wifi?", english: "Tem wi-fi?" },
      { italian: "La chiave", english: "A chave" },
    ],
    dialogue: [
      { speaker: "Ospite", line: "Buonasera! Ho una prenotazione. Mi chiamo Rossi.", translation: "Boa noite! Tenho uma reserva. Meu nome é Rossi." },
      { speaker: "Receptionist", line: "Benvenuto! Sì, camera doppia per tre notti.", translation: "Bem-vindo/a! Sim, quarto duplo por três noites." },
      { speaker: "Ospite", line: "Perfetto. La colazione è inclusa?", translation: "Perfeito. O café da manhã está incluído?" },
      { speaker: "Receptionist", line: "Sì, dalle sette alle dieci. C'è anche il wifi gratuito.", translation: "Sim, das sete às dez. Tem wi-fi gratuito também." },
      { speaker: "Ospite", line: "Ottimo. A che ora è il check-out?", translation: "Ótimo. A que horas é o check-out?" },
      { speaker: "Receptionist", line: "Alle undici. Ecco la sua chiave. Buona permanenza!", translation: "Às onze. Aqui está a sua chave. Boa estadia!" },
    ],
    grammar: {
      title: "Preposições: a, di, da, in",
      points: [
        { italian: "Sono a Roma", english: "Estou em Roma (localização)" },
        { italian: "Vengo da Londra", english: "Venho de Londres (origem)" },
        { italian: "Vado in Italia", english: "Vou para a Itália (países)" },
        { italian: "La chiave di Maria", english: "A chave de Maria (posse)" },
      ],
      note: "As preposições italianas nem sempre coincidem com as portuguesas. \"In\" usa-se com países, \"a\" com cidades.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a hotel receptionist. Reply in Portuguese. Use lesson 9 vocabulary. Correct gently.",
  },
  {
    id: 10, title: "No Trem", subtitle: "Sul Treno", free: false,
    keywords: [
      { italian: "Un biglietto per…", english: "Uma passagem para…" },
      { italian: "Andata e ritorno", english: "Ida e volta" },
      { italian: "Il binario", english: "A plataforma" },
      { italian: "È occupato?", english: "Este assento está ocupado?" },
      { italian: "A che ora arriva?", english: "A que horas chega?" },
      { italian: "Il treno è in ritardo", english: "O trem está atrasado" },
    ],
    dialogue: [
      { speaker: "Viaggiatore", line: "Buongiorno! Un biglietto per Venezia, per favore.", translation: "Bom dia! Uma passagem para Veneza, por favor." },
      { speaker: "Bigliettaio", line: "Andata e ritorno?", translation: "Ida e volta?" },
      { speaker: "Viaggiatore", line: "Solo andata. A che ora arriva?", translation: "Só ida. A que horas chega?" },
      { speaker: "Bigliettaio", line: "Alle tredici e venti. Binario 4.", translation: "Às treze e vinte. Plataforma 4." },
      { speaker: "Viaggiatore", line: "Grazie. È occupato questo posto?", translation: "Obrigado/a. Este assento está ocupado?" },
      { speaker: "Passeggero", line: "No, si accomodi!", translation: "Não, por favor, sente-se!" },
    ],
    grammar: {
      title: "A hora",
      points: [
        { italian: "Sono le tre", english: "São três horas" },
        { italian: "È mezzogiorno", english: "É meio-dia" },
        { italian: "Alle otto e mezza", english: "Às oito e meia" },
        { italian: "A che ora?", english: "A que horas?" },
      ],
      note: "Os italianos usam o relógio de 24h para transporte. \"Sono le tredici\" = 13h. Use \"sono le\" exceto para 1h: \"è l'una\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a train station agent. Reply in Portuguese. Use lesson 10 vocabulary. Correct gently.",
  },
  {
    id: 11, title: "Na Feira", subtitle: "Al Mercato", free: false,
    keywords: [
      { italian: "Quanto pesa?", english: "Quanto pesa?" },
      { italian: "Un chilo di…", english: "Um quilo de…" },
      { italian: "Fresco / di stagione", english: "Fresco / da estação" },
      { italian: "Me ne dà mezzo chilo", english: "Me dê meio quilo" },
      { italian: "Basta così", english: "É só isso / já está" },
      { italian: "Il resto", english: "O troco" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Questi pomodori sono freschi?", translation: "Bom dia! Esses tomates são frescos?" },
      { speaker: "Venditore", line: "Freschissimi! Di stagione. Quanti ne vuole?", translation: "Fresquíssimos! Da estação. Quantos quer?" },
      { speaker: "Cliente", line: "Me ne dà un chilo, per favore.", translation: "Me dê um quilo, por favor." },
      { speaker: "Venditore", line: "Basta così?", translation: "É só isso?" },
      { speaker: "Cliente", line: "Sì, grazie. Ecco cinque euro.", translation: "Sim, obrigado/a. Aqui estão cinco euros." },
      { speaker: "Venditore", line: "Ecco il resto. Grazie, a presto!", translation: "Aqui está o troco. Obrigado/a, até logo!" },
    ],
    grammar: {
      title: "Ne — O pronome partitivo",
      points: [
        { italian: "Ne voglio un chilo", english: "Quero um quilo" },
        { italian: "Me ne dà due?", english: "Pode me dar dois?" },
        { italian: "Non ne ho", english: "Não tenho" },
        { italian: "Quanti ne vuole?", english: "Quantos quer?" },
      ],
      note: "\"Ne\" substitui um substantivo com uma quantidade — significa algo como \"dele/dela\". Os italianos o usam constantemente.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a market vendor. Reply in Portuguese. Use lesson 11 vocabulary. Correct gently.",
  },
  {
    id: 12, title: "Emergências e Saúde", subtitle: "Emergenze e Salute", free: false,
    keywords: [
      { italian: "Aiuto!", english: "Socorro!" },
      { italian: "Ho bisogno di un medico", english: "Preciso de um médico" },
      { italian: "Mi fa male…", english: "… está me doendo" },
      { italian: "Chiami un'ambulanza!", english: "Chame uma ambulância!" },
      { italian: "La farmacia", english: "A farmácia" },
      { italian: "Sono allergico/a a…", english: "Sou alérgico/a a…" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Scusi! Ho bisogno di aiuto.", translation: "Com licença! Preciso de ajuda." },
      { speaker: "Passante", line: "Cosa succede?", translation: "O que está acontecendo?" },
      { speaker: "Turista", line: "Mi fa molto male la testa. Ho la febbre.", translation: "Minha cabeça está doendo muito. Estou com febre." },
      { speaker: "Passante", line: "C'è una farmacia qui vicino.", translation: "Tem uma farmácia aqui perto." },
      { speaker: "Turista", line: "Sono allergico alla penicillina.", translation: "Sou alérgico à penicilina." },
      { speaker: "Passante", line: "Lo dica al farmacista. Venga, l'accompagno.", translation: "Diga ao farmacêutico. Venha, vou te acompanhar." },
    ],
    grammar: {
      title: "Mi fa male — Expressar dor",
      points: [
        { italian: "Mi fa male la testa", english: "Minha cabeça está doendo" },
        { italian: "Mi fa male lo stomaco", english: "Meu estômago está doendo" },
        { italian: "Mi fanno male i piedi", english: "Meus pés estão doendo (plural)" },
        { italian: "Ho la febbre", english: "Estou com febre" },
      ],
      note: "\"Mi fa male\" significa \"me faz mal\". Use \"fa male\" para uma parte do corpo, \"fanno male\" para várias.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor helping practice emergency vocabulary. Reply in Portuguese. Correct gently.",
  },
  {
    id: 13, title: "Na Farmácia", subtitle: "In Farmacia", free: false,
    keywords: [
      { italian: "Ho bisogno di…", english: "Preciso de…" },
      { italian: "Una ricetta", english: "Uma receita" },
      { italian: "Il mal di testa", english: "Dor de cabeça" },
      { italian: "La tosse", english: "Tosse" },
      { italian: "Qualcosa per…", english: "Algo para…" },
      { italian: "Quante volte al giorno?", english: "Quantas vezes por dia?" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno. Ho bisogno di qualcosa per il mal di testa.", translation: "Bom dia. Preciso de algo para dor de cabeça." },
      { speaker: "Farmacista", line: "Ha la ricetta?", translation: "Tem receita?" },
      { speaker: "Cliente", line: "No, è senza ricetta.", translation: "Não, é sem receita." },
      { speaker: "Farmacista", line: "Allora le do queste compresse. Due volte al giorno.", translation: "Então vou lhe dar estes comprimidos. Duas vezes por dia." },
      { speaker: "Cliente", line: "Grazie. Ho anche la tosse.", translation: "Obrigado/a. Também estou com tosse." },
      { speaker: "Farmacista", line: "Prenda questo sciroppo, tre volte al giorno dopo i pasti.", translation: "Tome este xarope, três vezes por dia após as refeições." },
    ],
    grammar: {
      title: "Imperativo — Dar instruções",
      points: [
        { italian: "Prenda queste pillole", english: "Tome estes comprimidos (ordem formal)" },
        { italian: "Beva molta acqua", english: "Beba bastante água" },
        { italian: "Riposi a casa", english: "Descanse em casa" },
        { italian: "Torni domani", english: "Volte amanhã" },
      ],
      note: "O imperativo formal (forma Lei) é usado por profissionais. Soa como a terceira pessoa do singular — uma ordem educada.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a pharmacist. Reply in Portuguese. Use lesson 13 vocabulary. Correct gently.",
  },
  {
    id: 14, title: "Falar ao Telefone", subtitle: "Al Telefono", free: false,
    keywords: [
      { italian: "Pronto!", english: "Alô! (ao atender)" },
      { italian: "Con chi parlo?", english: "Com quem estou falando?" },
      { italian: "Posso parlare con…?", english: "Posso falar com…?" },
      { italian: "Un momento", english: "Um momento" },
      { italian: "Richiamare", english: "Ligar de volta" },
      { italian: "È occupato", english: "A linha está ocupada" },
    ],
    dialogue: [
      { speaker: "A", line: "Pronto?", translation: "Alô?" },
      { speaker: "B", line: "Buongiorno! Posso parlare con la signora Bianchi?", translation: "Bom dia! Posso falar com a senhora Bianchi?" },
      { speaker: "A", line: "Sono io. Con chi parlo?", translation: "Sou eu mesma. Com quem estou falando?" },
      { speaker: "B", line: "Sono Marco Rossi, chiamo per la prenotazione.", translation: "Sou Marco Rossi, ligo pela reserva." },
      { speaker: "A", line: "Mi dispiace, la linea è occupata. Può richiamare?", translation: "Sinto muito, a linha está ocupada. Pode ligar de volta?" },
      { speaker: "B", line: "Certo, richiamo più tardi. Grazie!", translation: "Claro, ligo mais tarde. Obrigado/a!" },
    ],
    grammar: {
      title: "Potere + Infinitivo — Pedir permissão",
      points: [
        { italian: "Posso richiamare?", english: "Posso ligar de volta?" },
        { italian: "Può aspettare?", english: "Pode esperar? (formal)" },
        { italian: "Non posso sentire", english: "Não consigo ouvir" },
      ],
      note: "Ao telefone, os italianos sempre dizem \"Pronto!\" ao atender — significa literalmente \"pronto\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing phone calls. Reply in Portuguese. Use lesson 14 vocabulary. Correct gently.",
  },
  {
    id: 15, title: "No Correio", subtitle: "All'Ufficio Postale", free: false,
    keywords: [
      { italian: "Spedire un pacco", english: "Enviar um pacote" },
      { italian: "Una lettera / una busta", english: "Uma carta / um envelope" },
      { italian: "Per via aerea", english: "Por via aérea" },
      { italian: "Quanto ci vuole?", english: "Quanto tempo leva?" },
      { italian: "Il francobollo", english: "O selo" },
      { italian: "Raccomandata", english: "Carta registrada" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Vorrei spedire questo pacco in Inghilterra.", translation: "Bom dia! Gostaria de enviar este pacote para a Inglaterra." },
      { speaker: "Impiegato", line: "Per via aerea o normale?", translation: "Por via aérea ou normal?" },
      { speaker: "Cliente", line: "Aerea. Quanto ci vuole?", translation: "Aérea. Quanto tempo leva?" },
      { speaker: "Impiegato", line: "Circa cinque giorni lavorativi.", translation: "Cerca de cinco dias úteis." },
      { speaker: "Cliente", line: "Va bene. E vorrei anche tre francobolli.", translation: "Tudo bem. E também gostaria de três selos." },
    ],
    grammar: {
      title: "Ci vuole / Ci vogliono — Leva / É preciso",
      points: [
        { italian: "Ci vuole un'ora", english: "Leva uma hora" },
        { italian: "Ci vogliono tre giorni", english: "Leva três dias" },
        { italian: "Quanto ci vuole?", english: "Quanto tempo leva?" },
        { italian: "Ci vuole pazienza!", english: "É preciso ter paciência!" },
      ],
      note: "\"Ci vuole\" é perfeitamente prático — use-o sempre que quiser dizer quanto tempo algo leva.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a post office clerk. Reply in Portuguese. Use lesson 15 vocabulary. Correct gently.",
  },
  {
    id: 16, title: "Alugar um Carro", subtitle: "Noleggiare un'Auto", free: false,
    keywords: [
      { italian: "Noleggiare un'auto", english: "Alugar um carro" },
      { italian: "La patente", english: "A carteira de motorista" },
      { italian: "Il pieno", english: "Tanque cheio" },
      { italian: "L'assicurazione", english: "O seguro" },
      { italian: "Quanti chilometri?", english: "Quantos quilômetros?" },
      { italian: "Riconsegnare", english: "Devolver (o carro)" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno! Vorrei noleggiare un'auto per tre giorni.", translation: "Bom dia! Gostaria de alugar um carro por três dias." },
      { speaker: "Agente", line: "Certo. Ha la patente con sé?", translation: "Claro. O senhor/a senhora está com a carteira?" },
      { speaker: "Cliente", line: "Sì, eccola. L'assicurazione è inclusa?", translation: "Sim, aqui está. O seguro está incluído?" },
      { speaker: "Agente", line: "Sì, quella base è inclusa. Vuole quella completa?", translation: "Sim, o básico está incluído. Quer o completo?" },
      { speaker: "Cliente", line: "Sì, meglio. I chilometri sono illimitati?", translation: "Sim, é melhor. Os quilômetros são ilimitados?" },
      { speaker: "Agente", line: "Sì, nessun limite.", translation: "Sim, sem limite." },
    ],
    grammar: {
      title: "Dovere — Dever / Ter que",
      points: [
        { italian: "Devo riconsegnare l'auto", english: "Devo devolver o carro" },
        { italian: "Deve avere la patente", english: "O senhor/a senhora deve ter carteira (formal)" },
        { italian: "Dobbiamo fare il pieno", english: "Temos que encher o tanque" },
      ],
      note: "\"Dovere\" expressa obrigação — combine-o com um infinitivo. Um dos três verbos modais principais: potere, volere, dovere.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a car rental agent. Reply in Portuguese. Use lesson 16 vocabulary. Correct gently.",
  },
  {
    id: 17, title: "Na Praia", subtitle: "In Spiaggia", free: false,
    keywords: [
      { italian: "Un ombrellone", english: "Um guarda-sol de praia" },
      { italian: "Una sdraio", english: "Uma espreguiçadeira" },
      { italian: "La crema solare", english: "O protetor solar" },
      { italian: "Il mare è mosso", english: "O mar está agitado" },
      { italian: "Fare il bagno", english: "Tomar banho / entrar no mar" },
      { italian: "Che caldo!", english: "Que calor!" },
    ],
    dialogue: [
      { speaker: "Turista", line: "Buongiorno! Vorrei un ombrellone e due sdraio.", translation: "Bom dia! Gostaria de um guarda-sol e duas espreguiçadeiras." },
      { speaker: "Bagnino", line: "Certo! Prima fila o seconda?", translation: "Claro! Primeira fileira ou segunda?" },
      { speaker: "Turista", line: "Seconda va bene. Si può fare il bagno?", translation: "A segunda está bem. Pode-se tomar banho?" },
      { speaker: "Bagnino", line: "Sì, il mare è calmo oggi. Che caldo!", translation: "Sim, o mar está calmo hoje. Que calor!" },
    ],
    grammar: {
      title: "Fare — O verbo «Fazer»",
      points: [
        { italian: "Faccio una passeggiata", english: "Dou uma caminhada" },
        { italian: "Fa caldo / fa freddo", english: "Está calor / está frio (tempo)" },
        { italian: "Fai il bagno?", english: "Você está tomando banho?" },
        { italian: "Fanno un castello di sabbia", english: "Eles fazem um castelo de areia" },
      ],
      note: "\"Fare\" é um dos verbos italianos mais versáteis — aparece em dezenas de expressões fixas.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a beach attendant. Reply in Portuguese. Use lesson 17 vocabulary. Correct gently.",
  },
  {
    id: 18, title: "Falar sobre a Família", subtitle: "La Famiglia", free: false,
    keywords: [
      { italian: "Il marito / la moglie", english: "Marido / esposa" },
      { italian: "I figli", english: "Os filhos" },
      { italian: "Il fratello / la sorella", english: "Irmão / irmã" },
      { italian: "I genitori", english: "Os pais" },
      { italian: "Sei sposato/a?", english: "Você é casado/a?" },
      { italian: "Hai figli?", english: "Você tem filhos?" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei sposato?", translation: "Você é casado?" },
      { speaker: "B", line: "Sì, ho una moglie e due figli. E tu?", translation: "Sim, tenho uma esposa e dois filhos. E você?" },
      { speaker: "A", line: "Sono fidanzata. Ci sposiamo l'anno prossimo!", translation: "Estou noiva. Vamos nos casar no ano que vem!" },
      { speaker: "B", line: "Congratulazioni! Hai fratelli o sorelle?", translation: "Parabéns! Você tem irmãos ou irmãs?" },
      { speaker: "A", line: "Ho una sorella. I miei genitori vivono a Napoli.", translation: "Tenho uma irmã. Meus pais moram em Nápoles." },
    ],
    grammar: {
      title: "Possessivos — Meu, teu, seu",
      points: [
        { italian: "Il mio gatto", english: "Meu gato" },
        { italian: "Il tuo gelato", english: "Seu sorvete" },
        { italian: "La sua mamma", english: "A mãe dele/dela" },
        { italian: "I nostri vicini", english: "Nossos vizinhos" },
      ],
      note: "Os possessivos italianos concordam em gênero e número com o substantivo, não com o possuidor.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a conversation about family. Reply in Portuguese. Use lesson 18 vocabulary. Correct gently.",
  },
  {
    id: 19, title: "No Médico", subtitle: "Dal Medico", free: false,
    keywords: [
      { italian: "Ho un appuntamento", english: "Tenho uma consulta" },
      { italian: "Da quanto tempo?", english: "Desde quando / há quanto tempo?" },
      { italian: "Ho la nausea", english: "Estou com náusea" },
      { italian: "La pressione", english: "A pressão arterial" },
      { italian: "Fare una visita", english: "Fazer uma consulta" },
      { italian: "La diagnosi", english: "O diagnóstico" },
    ],
    dialogue: [
      { speaker: "Paziente", line: "Buongiorno, ho un appuntamento con il dottor Marini.", translation: "Bom dia, tenho uma consulta com o doutor Marini." },
      { speaker: "Dottore", line: "Da quanto tempo ha questi sintomi?", translation: "Há quanto tempo o senhor/a senhora tem esses sintomas?" },
      { speaker: "Paziente", line: "Da due giorni. Ho anche un po' di febbre.", translation: "Há dois dias. Também estou com um pouco de febre." },
      { speaker: "Dottore", line: "Le misuro la pressione. Respiri profondamente.", translation: "Vou medir sua pressão. Respire fundo." },
      { speaker: "Dottore", line: "Non è grave. Le scrivo una ricetta.", translation: "Não é grave. Vou lhe prescrever algo." },
    ],
    grammar: {
      title: "Da — Desde / Há (tempo)",
      points: [
        { italian: "Da due giorni", english: "Há dois dias (em curso)" },
        { italian: "Vivo qui da un anno", english: "Moro aqui há um ano" },
        { italian: "Da stamattina", english: "Desde esta manhã" },
        { italian: "Da quanto tempo?", english: "Há quanto tempo?" },
      ],
      note: "Em italiano, \"da\" + presente descreve algo que está acontecendo desde o passado. Em português usamos \"há\" + tempo ou \"desde\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a doctor. Reply in Portuguese. Use lesson 19 vocabulary. Correct gently.",
  },
  {
    id: 20, title: "Sair à Noite", subtitle: "Uscire la Sera", free: false,
    keywords: [
      { italian: "Andiamo a ballare?", english: "Vamos dançar?" },
      { italian: "Un locale", english: "Um local / uma balada / um bar" },
      { italian: "C'è la fila", english: "Tem fila" },
      { italian: "Offro io", english: "Eu pago / estou pagando" },
      { italian: "Fare tardi", english: "Ficar até tarde" },
      { italian: "Che serata!", english: "Que noite!" },
    ],
    dialogue: [
      { speaker: "A", line: "Allora, andiamo a ballare stasera?", translation: "Então, vamos dançar esta noite?" },
      { speaker: "B", line: "Sì! Conosco un bel locale in centro.", translation: "Sim! Conheço um bom lugar no centro." },
      { speaker: "A", line: "C'è la fila di solito?", translation: "Costuma ter fila?" },
      { speaker: "B", line: "A volte sì, ma entriamo con la lista.", translation: "Às vezes sim, mas entramos pela lista." },
      { speaker: "B", line: "Un aperitivo — offro io!", translation: "Um aperitivo — eu pago!" },
    ],
    grammar: {
      title: "Andare — Ir (+ lugares)",
      points: [
        { italian: "Vado al bar", english: "Vou ao bar" },
        { italian: "Va bene!", english: "Tudo bem! / Ok!" },
        { italian: "Andiamo a ballare", english: "Vamos dançar" },
        { italian: "Vai a casa?", english: "Você vai para casa?" },
      ],
      note: "\"Andiamo\" (vamos) é uma das palavras mais úteis da vida social italiana. \"Va bene\" é usado constantemente.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend planning a night out. Reply in Portuguese. Use lesson 20 vocabulary. Correct gently.",
  },
  {
    id: 21, title: "Comida e Culinária", subtitle: "Cibo e Cucina", free: false,
    keywords: [
      { italian: "La ricetta", english: "A receita" },
      { italian: "Gli ingredienti", english: "Os ingredientes" },
      { italian: "Cuocere / cucinare", english: "Cozinhar" },
      { italian: "Aggiungere", english: "Adicionar" },
      { italian: "Mescolare", english: "Mexer / misturar" },
      { italian: "È pronto!", english: "Está pronto!" },
    ],
    dialogue: [
      { speaker: "A", line: "Stai cucinando? Che profumo!", translation: "Você está cozinhando? Que cheiro gostoso!" },
      { speaker: "B", line: "Sto facendo la pasta al pomodoro. Vuoi la ricetta?", translation: "Estou fazendo macarrão ao tomate. Quer a receita?" },
      { speaker: "A", line: "Sì! Quali ingredienti usi?", translation: "Sim! Quais ingredientes você usa?" },
      { speaker: "B", line: "Pomodori freschi, aglio, basilico e olio d'oliva.", translation: "Tomates frescos, alho, manjericão e azeite." },
      { speaker: "A", line: "Aggiungi il sale, mescola e aspetta.", translation: "Adiciona o sal, mexe e espera." },
    ],
    grammar: {
      title: "Stare + Gerúndio — Presente contínuo",
      points: [
        { italian: "Sto cucinando", english: "Estou cozinhando (agora mesmo)" },
        { italian: "Sta mangiando", english: "Ele/Ela está comendo" },
        { italian: "Stiamo aspettando", english: "Estamos esperando" },
        { italian: "Cosa state facendo?", english: "O que vocês estão fazendo?" },
      ],
      note: "O italiano tem um presente contínuo formado com \"stare\" + gerúndio (-ando/-endo).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend cooking. Reply in Portuguese. Use lesson 21 vocabulary. Correct gently.",
  },
  {
    id: 22, title: "No Banco", subtitle: "In Banca", free: false,
    keywords: [
      { italian: "Aprire un conto", english: "Abrir uma conta" },
      { italian: "Il bancomat", english: "O caixa eletrônico / o cartão de débito" },
      { italian: "Prelevare", english: "Sacar dinheiro" },
      { italian: "Il tasso di cambio", english: "A taxa de câmbio" },
      { italian: "Fare un bonifico", english: "Fazer uma transferência" },
      { italian: "Lo sportello", english: "O guichê" },
    ],
    dialogue: [
      { speaker: "Cliente", line: "Buongiorno. Vorrei prelevare dei contanti.", translation: "Bom dia. Gostaria de sacar dinheiro." },
      { speaker: "Impiegato", line: "Si accomodi allo sportello tre.", translation: "Por favor, vá ao guichê três." },
      { speaker: "Cliente", line: "Qual è il tasso di cambio oggi?", translation: "Qual é a taxa de câmbio hoje?" },
      { speaker: "Cliente", line: "Posso anche fare un bonifico?", translation: "Posso também fazer uma transferência?" },
      { speaker: "Impiegato", line: "Certo. Ha il codice IBAN del destinatario?", translation: "Claro. O senhor/a senhora tem o código IBAN do destinatário?" },
    ],
    grammar: {
      title: "Os números",
      points: [
        { italian: "Uno…dieci", english: "1–10" },
        { italian: "Undici…venti", english: "11–20" },
        { italian: "Cento / mille / un milione", english: "100 / 1.000 / 1.000.000" },
        { italian: "Virgola", english: "Ponto decimal (vírgula em italiano)" },
      ],
      note: "Em italiano, os decimais usam vírgula: \"1,17\" = uno virgola diciassette. Os milhares usam ponto. O oposto do inglês!",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a bank teller. Reply in Portuguese. Use lesson 22 vocabulary. Correct gently.",
  },
  {
    id: 23, title: "Fazer Planos", subtitle: "Fare Programmi", free: false,
    keywords: [
      { italian: "Sei libero/a?", english: "Você está livre?" },
      { italian: "Che ne dici di…?", english: "O que você acha de…?" },
      { italian: "Mi va!", english: "Estou dentro! / Que ótimo!" },
      { italian: "Ci vediamo", english: "A gente se vê" },
      { italian: "Rimandare", english: "Adiar" },
      { italian: "Non vedo l'ora!", english: "Estou ansioso/a!" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei libera sabato?", translation: "Você está livre no sábado?" },
      { speaker: "B", line: "Sì! Che ne dici di andare al museo?", translation: "Sim! O que você acha de ir ao museu?" },
      { speaker: "A", line: "Mi va! A che ora ci vediamo?", translation: "Ótimo! A que horas a gente se encontra?" },
      { speaker: "B", line: "Alle dieci davanti all'ingresso?", translation: "Às dez na frente da entrada?" },
      { speaker: "A", line: "Perfetto. Non vedo l'ora!", translation: "Perfeito. Estou muito ansioso/a!" },
    ],
    grammar: {
      title: "Futuro — Rápido e fácil",
      points: [
        { italian: "Andrò al museo", english: "Vou ao museu" },
        { italian: "Sarà divertente", english: "Vai ser divertido" },
        { italian: "Cosa farai?", english: "O que você vai fazer?" },
        { italian: "Ci vediamo domani", english: "A gente se vê amanhã (presente para futuro próximo)" },
      ],
      note: "Os italianos costumam usar o presente para planos próximos. \"Domani vado al cinema\" é mais natural no dia a dia.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friend making plans. Reply in Portuguese. Use lesson 23 vocabulary. Correct gently.",
  },
  {
    id: 24, title: "Falar sobre o Tempo", subtitle: "Il Tempo", free: false,
    keywords: [
      { italian: "Che tempo fa?", english: "Como está o tempo?" },
      { italian: "Piove / nevica", english: "Está chovendo / nevando" },
      { italian: "C'è il sole", english: "Está ensolarado" },
      { italian: "Afoso", english: "Úmido / abafado" },
      { italian: "Le previsioni", english: "A previsão" },
      { italian: "Portare un ombrello", english: "Levar um guarda-chuva" },
    ],
    dialogue: [
      { speaker: "A", line: "Che tempo fa oggi?", translation: "Como está o tempo hoje?" },
      { speaker: "B", line: "È nuvoloso stamattina, ma nel pomeriggio c'è il sole.", translation: "Esta manhã está nublado, mas à tarde tem sol." },
      { speaker: "A", line: "E domani? Hai visto le previsioni?", translation: "E amanhã? Você viu a previsão?" },
      { speaker: "B", line: "Sì, piove di mattina. Porta l'ombrello!", translation: "Sim, vai chover de manhã. Leve um guarda-chuva!" },
    ],
    grammar: {
      title: "Imperfeito — O passado (hábitos e descrições)",
      points: [
        { italian: "Volevo andare al mare", english: "Eu queria ir à praia" },
        { italian: "Faceva caldo", english: "Estava calor (descrição no passado)" },
        { italian: "Quando ero piccolo…", english: "Quando eu era jovem…" },
        { italian: "Di solito prendevo…", english: "Eu costumava pegar…" },
      ],
      note: "O imperfeito é usado para hábitos passados, descrições e estados prolongados.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor talking about the weather. Reply in Portuguese. Use lesson 24 vocabulary. Correct gently.",
  },
  {
    id: 25, title: "No Parque", subtitle: "Al Parco", free: false,
    keywords: [
      { italian: "Il fiore", english: "A flor" },
      { italian: "L'albero", english: "A árvore" },
      { italian: "Il cane", english: "O cachorro" },
      { italian: "La panchina", english: "O banco" },
      { italian: "Bello / bella", english: "Bonito/a" },
      { italian: "Guarda!", english: "Olha!" },
    ],
    dialogue: [
      { speaker: "A", line: "Guarda quel cane!", translation: "Olha aquele cachorro!" },
      { speaker: "B", line: "Che bello! È tuo?", translation: "Que lindo! É seu?" },
      { speaker: "A", line: "No, ma vorrei averne uno.", translation: "Não, mas eu adoraria ter um." },
      { speaker: "B", line: "Mi piace quel fiore rosso là.", translation: "Gosto daquela flor vermelha ali." },
      { speaker: "A", line: "Sediamoci sulla panchina?", translation: "A gente se senta no banco?" },
    ],
    grammar: {
      title: "I Colori — As cores",
      points: [
        { italian: "Rosso / rossa", english: "Vermelho / vermelha (m/f)" },
        { italian: "Verde", english: "Verde" },
        { italian: "Blu", english: "Azul (invariável)" },
        { italian: "Giallo / gialla", english: "Amarelo / amarela (m/f)" },
        { italian: "Un fiore rosso", english: "Uma flor vermelha (o adjetivo vem depois do substantivo)" },
      ],
      note: "Em italiano, as cores são adjetivos e concordam com o substantivo. Blu e rosa nunca mudam.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor taking a walk in an Italian park. Reply in Portuguese. Correct gently.",
  },
  {
    id: 26, title: "Descrever Pessoas", subtitle: "Parlare delle Persone", free: false,
    keywords: [
      { italian: "Alto / basso", english: "Alto / baixo" },
      { italian: "Magro / robusto", english: "Magro / robusto" },
      { italian: "Simpatico / antipatico", english: "Simpático / antipático" },
      { italian: "Timido / estroverso", english: "Tímido / extrovertido" },
      { italian: "I capelli", english: "O cabelo" },
      { italian: "Gli occhi", english: "Os olhos" },
    ],
    dialogue: [
      { speaker: "A", line: "Conosci Marco?", translation: "Você conhece o Marco?" },
      { speaker: "B", line: "Sì! È alto e molto simpatico.", translation: "Sim! Ele é alto e muito simpático." },
      { speaker: "A", line: "Ha i capelli scuri, vero?", translation: "Ele tem cabelo escuro, né?" },
      { speaker: "B", line: "Sì, e gli occhi verdi.", translation: "Sim, e olhos verdes." },
    ],
    grammar: {
      title: "Essere + Adjetivos para descrições",
      points: [
        { italian: "È alto e magro", english: "Ele é alto e magro" },
        { italian: "È simpatica", english: "Ela é simpática" },
        { italian: "Ha i capelli biondi", english: "Ele/Ela tem cabelo loiro" },
        { italian: "Ha gli occhi azzurri", english: "Ele/Ela tem olhos azuis" },
      ],
      note: "As descrições físicas usam essere para qualidades e avere para características como cabelo e olhos.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor helping describe people. Reply in Portuguese. Use lesson 26 vocabulary. Correct gently.",
  },
  {
    id: 27, title: "Com os Vizinhos", subtitle: "Con i Vicini", free: false,
    keywords: [
      { italian: "Come va?", english: "Como vai?" },
      { italian: "Stanco / stanca", english: "Cansado/a" },
      { italian: "Come mai?", english: "Como assim? / Por quê?" },
      { italian: "Ho dormito poco", english: "Dormi pouco" },
      { italian: "Tutto bene?", english: "Tudo bem?" },
      { italian: "La settimana", english: "A semana" },
    ],
    dialogue: [
      { speaker: "A", line: "Buongiorno! Come va?", translation: "Bom dia! Como vai?" },
      { speaker: "B", line: "Un po' stanca oggi.", translation: "Um pouco cansada hoje." },
      { speaker: "A", line: "Come mai?", translation: "Como assim?" },
      { speaker: "B", line: "Ho dormito poco stanotte.", translation: "Dormi pouco essa noite." },
      { speaker: "A", line: "Meno male! Buona giornata!", translation: "Ainda bem! Tenha um bom dia!" },
    ],
    grammar: {
      title: "Expressões de conversa cotidiana",
      points: [
        { italian: "Come mai?", english: "Como assim? / Por que isso?" },
        { italian: "Meno male!", english: "Ainda bem! / Que alívio!" },
        { italian: "Abbastanza", english: "Bastante / razoavelmente / suficiente" },
        { italian: "Mi dispiace", english: "Sinto muito" },
      ],
      note: "Come mai é mais suave que perché — exprime leve surpresa. Meno male significa literalmente \"menos ruim\".",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a friendly neighbour. Reply in Portuguese. Correct gently.",
  },
  {
    id: 28, title: "Falar sobre o Dia", subtitle: "Parlare della Giornata", free: false,
    keywords: [
      { italian: "Ieri / oggi / domani", english: "Ontem / hoje / amanhã" },
      { italian: "Stamattina / stasera", english: "Esta manhã / esta noite" },
      { italian: "Ho lavorato", english: "Trabalhei (passado)" },
      { italian: "Sono partito/a", english: "Saí / parti (passado)" },
      { italian: "Cosa hai fatto?", english: "O que você fez?" },
      { italian: "Tutto il giorno", english: "O dia todo" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa hai fatto ieri?", translation: "O que você fez ontem?" },
      { speaker: "B", line: "Ho lavorato tutto il giorno.", translation: "Trabalhei o dia todo." },
      { speaker: "B", line: "Sono andato al cinema con Marco.", translation: "Fui ao cinema com o Marco." },
      { speaker: "A", line: "Bello! E domani?", translation: "Que legal! E amanhã?" },
      { speaker: "B", line: "Domani partiamo per Roma.", translation: "Amanhã a gente vai para Roma." },
    ],
    grammar: {
      title: "Passato Prossimo — O passado recente",
      points: [
        { italian: "Ho lavorato", english: "Trabalhei (avere + particípio passado)" },
        { italian: "Sono andato/a", english: "Fui (essere + particípio passado)" },
        { italian: "Abbiamo fatto", english: "Nós fizemos" },
        { italian: "Sei partito/a?", english: "Você foi embora?" },
      ],
      note: "O passato prossimo usa avere ou essere + particípio passado. Verbos de movimento levam essere.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about the student's recent day. Reply in Portuguese. Correct gently.",
  },
  {
    id: 29, title: "Pedir Explicações", subtitle: "Chiedere Spiegazioni", free: false,
    keywords: [
      { italian: "Perché?", english: "Por quê?" },
      { italian: "Come mai?", english: "Como assim?" },
      { italian: "Allora", english: "Então / portanto / bem" },
      { italian: "Quindi", english: "Portanto / então" },
      { italian: "Non capisco", english: "Não entendo" },
      { italian: "Uno sciopero", english: "Uma greve" },
    ],
    dialogue: [
      { speaker: "A", line: "Perché il treno è in ritardo?", translation: "Por que o trem está atrasado?" },
      { speaker: "B", line: "Perché c'è uno sciopero.", translation: "Porque tem uma greve." },
      { speaker: "A", line: "Non capisco — c'è un altro treno?", translation: "Não entendo — tem outro trem?" },
      { speaker: "B", line: "Allora, provi l'autobus.", translation: "Bem, então tente o ônibus." },
    ],
    grammar: {
      title: "Perché — Por que e Porque",
      points: [
        { italian: "Perché sei in ritardo?", english: "Por que você está atrasado? (pergunta)" },
        { italian: "Perché c'è traffico", english: "Porque tem trânsito (resposta)" },
        { italian: "Non lo so", english: "Não sei" },
        { italian: "Forse", english: "Talvez" },
      ],
      note: "Perché significa tanto \"por que\" quanto \"porque\" em italiano. Allora é ouvido constantemente nas conversas italianas.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing situations where things go wrong. Reply in Portuguese. Correct gently.",
  },
  {
    id: 30, title: "Sonhos e Desejos", subtitle: "Sogni e Desideri", free: false,
    keywords: [
      { italian: "Vorrei...", english: "Eu gostaria… / Eu adoraria…" },
      { italian: "Mi piacerebbe", english: "Eu adoraria (lit. me agradaria)" },
      { italian: "Magari", english: "Quem sabe / tomara / eu adoraria" },
      { italian: "Forse", english: "Talvez" },
      { italian: "Un giorno", english: "Um dia" },
      { italian: "Davvero?", english: "De verdade?" },
    ],
    dialogue: [
      { speaker: "A", line: "Vorrei vivere in Italia.", translation: "Eu adoraria morar na Itália." },
      { speaker: "B", line: "Davvero? In quale città?", translation: "De verdade? Em qual cidade?" },
      { speaker: "A", line: "Firenze. Mi piacerebbe molto.", translation: "Florença. Eu adoraria muito." },
      { speaker: "B", line: "Magari vengo anch'io!", translation: "Quem sabe eu vá também!" },
      { speaker: "A", line: "Forse un giorno si può.", translation: "Talvez um dia seja possível." },
    ],
    grammar: {
      title: "Condicional — Vorrei e Mi piacerebbe",
      points: [
        { italian: "Vorrei andare a Roma", english: "Eu gostaria de ir a Roma" },
        { italian: "Mi piacerebbe molto", english: "Eu adoraria muito" },
        { italian: "Magari!", english: "Tomara! / Eu adoraria tanto!" },
        { italian: "Sarebbe bello", english: "Seria lindo" },
      ],
      note: "Magari pode significar talvez, tomara ou eu adoraria, dependendo do tom. Os italianos amam essa palavra!",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a conversation about wishes. Reply in Portuguese. Use lesson 30 vocabulary. Correct gently.",
  },
  {
    id: 31, title: "Em Casa", subtitle: "A Casa", free: false,
    keywords: [
      { italian: "Il soggiorno", english: "A sala de estar" },
      { italian: "La cucina", english: "A cozinha" },
      { italian: "Il divano", english: "O sofá" },
      { italian: "Cucinare", english: "Cozinhar" },
      { italian: "Pulire", english: "Limpar" },
      { italian: "Rilassarsi", english: "Relaxar" },
    ],
    dialogue: [
      { speaker: "A", line: "Sei a casa?", translation: "Você está em casa?" },
      { speaker: "B", line: "Sì, sto cucinando in cucina.", translation: "Sim, estou cozinhando na cozinha." },
      { speaker: "A", line: "Dopo ti rilassi un po'?", translation: "Vai relaxar um pouco depois?" },
      { speaker: "B", line: "Spero! Mi butto sul divano.", translation: "Espero que sim! Vou me jogar no sofá." },
    ],
    grammar: {
      title: "Verbos reflexivos — Verbi Riflessivi",
      points: [
        { italian: "Mi rilasso", english: "Eu me relaxo" },
        { italian: "Ti svegli?", english: "Você acorda?" },
        { italian: "Si chiama", english: "Ele/Ela se chama" },
        { italian: "Mi butto sul divano", english: "Me jogo no sofá" },
      ],
      note: "Os verbos reflexivos usam um pronome (mi, ti, si, ci, vi, si) para ações feitas sobre si mesmo.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a cosy conversation about home. Reply in Portuguese. Use lesson 31 vocabulary. Correct gently.",
  },
  {
    id: 32, title: "Rotina Diária", subtitle: "La Routine Quotidiana", free: false,
    keywords: [
      { italian: "Mi sveglio", english: "Eu acordo" },
      { italian: "Faccio colazione", english: "Tomo café da manhã" },
      { italian: "Mi vesto", english: "Me visto" },
      { italian: "Torno a casa", english: "Volto para casa" },
      { italian: "Di solito", english: "Geralmente" },
      { italian: "Mi addormento", english: "Adormeço" },
    ],
    dialogue: [
      { speaker: "A", line: "A che ora ti svegli di solito?", translation: "A que horas você geralmente acorda?" },
      { speaker: "B", line: "Mi sveglio alle sette. Faccio colazione e poi mi vesto.", translation: "Acordo às sete. Tomo café da manhã e depois me visto." },
      { speaker: "A", line: "E vai a letto tardi?", translation: "E você vai dormir tarde?" },
      { speaker: "B", line: "No, mi addormento verso le undici.", translation: "Não, adormeço por volta das onze." },
    ],
    grammar: {
      title: "Verbos reflexivos — A vida cotidiana",
      points: [
        { italian: "Mi sveglio alle 7", english: "Acordo às 7h" },
        { italian: "Mi lavo", english: "Me lavo" },
        { italian: "Mi vesto", english: "Me visto" },
        { italian: "Mi addormento", english: "Adormeço" },
      ],
      note: "A rotina diária em italiano é cheia de verbos reflexivos. O pronome sempre vem antes do verbo conjugado.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about the student's daily routine. Reply in Portuguese. Correct gently.",
  },
  {
    id: 33, title: "No Supermercado", subtitle: "Al Supermercato", free: false,
    keywords: [
      { italian: "Il carrello", english: "O carrinho" },
      { italian: "Il reparto", english: "O corredor / seção" },
      { italian: "La cassa", english: "O caixa" },
      { italian: "Mezzo chilo", english: "Meio quilo" },
      { italian: "In offerta", english: "Em promoção" },
      { italian: "Dov'è il reparto...?", english: "Onde fica o corredor…?" },
    ],
    dialogue: [
      { speaker: "A", line: "Scusi, dov'è il reparto latticini?", translation: "Com licença, onde fica a seção de laticínios?" },
      { speaker: "B", line: "È in fondo a destra.", translation: "Fica lá no fundo à direita." },
      { speaker: "A", line: "Questo formaggio è in offerta?", translation: "Este queijo está em promoção?" },
      { speaker: "B", line: "Sì, prenda due e risparmia il 20%.", translation: "Sim, leve dois e economize 20%." },
    ],
    grammar: {
      title: "Partitivos — Expressar «um pouco de»",
      points: [
        { italian: "Del pane", english: "Um pouco de pão (partitivo)" },
        { italian: "Delle mele", english: "Umas maçãs (partitivo)" },
        { italian: "Un chilo di pasta", english: "Um quilo de macarrão" },
        { italian: "Mezzo litro di latte", english: "Meio litro de leite" },
      ],
      note: "O italiano usa del/della/dei/delle para dizer \"um pouco de\". Vorrei del pane = Gostaria de um pãozinho.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a supermarket assistant. Reply in Portuguese. Use lesson 33 vocabulary. Correct gently.",
  },
  {
    id: 34, title: "No Ônibus", subtitle: "Sull'Autobus", free: false,
    keywords: [
      { italian: "Il biglietto", english: "A passagem" },
      { italian: "La fermata", english: "A parada" },
      { italian: "Scendere", english: "Descer" },
      { italian: "Salire", english: "Subir" },
      { italian: "Quante fermate?", english: "Quantas paradas?" },
      { italian: "Devo cambiare?", english: "Preciso fazer baldeação?" },
    ],
    dialogue: [
      { speaker: "A", line: "Scusi, questo autobus va al centro?", translation: "Com licença, esse ônibus vai ao centro?" },
      { speaker: "B", line: "Sì, ma deve cambiare alla fermata San Marco.", translation: "Sim, mas o senhor/a senhora precisa fazer baldeação na parada San Marco." },
      { speaker: "A", line: "Quante fermate sono?", translation: "Quantas paradas são?" },
      { speaker: "B", line: "Quattro fermate. Poi scende e aspetta il 14.", translation: "Quatro paradas. Depois desça e espere o 14." },
    ],
    grammar: {
      title: "Dovere + Infinitivo no transporte público",
      points: [
        { italian: "Devo scendere qui", english: "Preciso descer aqui" },
        { italian: "Deve cambiare", english: "O senhor/a senhora precisa fazer baldeação (formal)" },
        { italian: "Devi comprare il biglietto", english: "Você precisa comprar a passagem" },
      ],
      note: "No transporte público, dovere (dever) e potere (poder) são essenciais. Sempre combinados com um infinitivo.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a fellow passenger on an Italian bus. Reply in Portuguese. Correct gently.",
  },
  {
    id: 35, title: "Tempo Livre", subtitle: "Il Tempo Libero", free: false,
    keywords: [
      { italian: "Leggere", english: "Ler" },
      { italian: "Guardare un film", english: "Assistir a um filme" },
      { italian: "Passeggiare", english: "Passear" },
      { italian: "Ascoltare musica", english: "Ouvir música" },
      { italian: "Nel tempo libero", english: "No meu tempo livre" },
      { italian: "Mi annoio", english: "Estou entediado/a" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa fai nel tempo libero?", translation: "O que você faz no seu tempo livre?" },
      { speaker: "B", line: "Mi piace leggere e ascoltare musica.", translation: "Gosto de ler e ouvir música." },
      { speaker: "A", line: "Guardi film italiani?", translation: "Você assiste a filmes italianos?" },
      { speaker: "B", line: "Sì! È il modo migliore per imparare.", translation: "Sim! É a melhor forma de aprender." },
    ],
    grammar: {
      title: "Infinitivos como substantivos",
      points: [
        { italian: "Mi piace leggere", english: "Gosto de ler" },
        { italian: "Adoro cucinare", english: "Adoro cozinhar" },
        { italian: "Odio aspettare", english: "Odeio esperar" },
        { italian: "Ho voglia di uscire", english: "Estou com vontade de sair" },
      ],
      note: "Quando fala de atividades que gosta ou não, use o infinitivo diretamente depois de mi piace, preferisco, adoro etc.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a relaxed chat about hobbies. Reply in Portuguese. Correct gently.",
  },
  {
    id: 36, title: "Convites e Recusas", subtitle: "Inviti e Rifiuti", free: false,
    keywords: [
      { italian: "Ti va di...?", english: "Você quer…? / Quer fazer…?" },
      { italian: "Volentieri!", english: "Com prazer!" },
      { italian: "Non posso", english: "Não posso" },
      { italian: "Peccato", english: "Que pena" },
      { italian: "Un'altra volta", english: "Outra vez" },
      { italian: "Magari la prossima", english: "Quem sabe na próxima" },
    ],
    dialogue: [
      { speaker: "A", line: "Ti va di venire a cena stasera?", translation: "Você quer vir jantar esta noite?" },
      { speaker: "B", line: "Volentieri! A che ora?", translation: "Com prazer! A que horas?" },
      { speaker: "A", line: "Alle otto.", translation: "Às oito." },
      { speaker: "B", line: "Se non può, peccato — un'altra volta.", translation: "Se ele não puder, que pena — outra vez." },
    ],
    grammar: {
      title: "Verbos modais — Convites e recusas",
      points: [
        { italian: "Non posso venire", english: "Não posso vir" },
        { italian: "Dovrei restare", english: "Eu devia ficar" },
        { italian: "Potremmo andare", english: "Poderíamos ir" },
        { italian: "Ti va di...?", english: "Você quer…? (expressão fixa)" },
      ],
      note: "Ti va di...? é uma das expressões de convite italianas mais úteis — informal e calorosa. Peccato suaviza uma recusa lindamente.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing invitations. Reply in Portuguese. Use lesson 36 vocabulary. Correct gently.",
  },
  {
    id: 37, title: "Minha Cidade", subtitle: "La Mia Città", free: false,
    keywords: [
      { italian: "Ciò che mi piace di più", english: "O que mais gosto" },
      { italian: "La cosa più interessante", english: "A coisa mais interessante" },
      { italian: "Quello che non mi piace tanto", english: "O que não gosto muito" },
      { italian: "Il quartiere", english: "O bairro" },
      { italian: "Vivace / tranquillo", english: "Animado / tranquilo" },
      { italian: "Mi manca", english: "Tenho saudade" },
    ],
    dialogue: [
      { speaker: "A", line: "Di dove sei?", translation: "De onde você é?" },
      { speaker: "B", line: "Sono di Napoli.", translation: "Sou de Nápoles." },
      { speaker: "A", line: "Cosa ti piace di più?", translation: "O que você mais gosta de lá?" },
      { speaker: "B", line: "Ciò che mi piace di più è il mare e il cibo.", translation: "O que mais gosto é do mar e da comida." },
      { speaker: "B", line: "Quello che non sopporto è il caos del traffico.", translation: "O que não suporto é o caos do trânsito." },
    ],
    grammar: {
      title: "Orações relativas — Ciò che / Quello che",
      points: [
        { italian: "Ciò che mi piace", english: "O que eu gosto (o que me agrada)" },
        { italian: "Quello che voglio", english: "O que eu quero" },
        { italian: "Non è quello che pensavo", english: "Não é o que eu pensava" },
        { italian: "Tutto ciò che sai", english: "Tudo o que você sabe" },
      ],
      note: "Ciò che e quello che significam ambos \"o que\" no sentido de \"a coisa que\". São intercambiáveis.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor talking about Italian cities. Reply in Portuguese. Correct gently.",
  },
  {
    id: 38, title: "Com Pressa!", subtitle: "Di Fretta", free: false,
    keywords: [
      { italian: "Siamo in ritardo!", english: "Estamos atrasados!" },
      { italian: "Aspettami!", english: "Me espera!" },
      { italian: "Forza!", english: "Vai! / Vamos!" },
      { italian: "Sbrigati!", english: "Se apresse!" },
      { italian: "Prendo la valigia", english: "Pego a mala" },
      { italian: "Corri!", english: "Corre!" },
    ],
    dialogue: [
      { speaker: "A", line: "Sbrigati! Siamo in ritardo!", translation: "Se apresse! Estamos atrasados!" },
      { speaker: "B", line: "Aspettami, prendo la valigia.", translation: "Me espera, pego a mala." },
      { speaker: "A", line: "Prendila e vieni, forza!", translation: "Pega ela e vem, vai!" },
      { speaker: "A", line: "Dai, corri! Il treno parte tra cinque minuti.", translation: "Vai, corre! O trem parte em cinco minutos." },
    ],
    grammar: {
      title: "Imperativo informal — Ordens com pronomes",
      points: [
        { italian: "Aspetta! / Aspettami!", english: "Espera! / Me espera!" },
        { italian: "Sbrigati!", english: "Se apresse! (imperativo reflexivo)" },
        { italian: "Prendila!", english: "Pega! (pronome ligado ao verbo)" },
        { italian: "Aiutami!", english: "Me ajuda!" },
      ],
      note: "Nas ordens informais, os pronomes se ligam ao final do verbo: prendila (pega), aspettami (me espera).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing a rushed situation. Reply in Portuguese. Correct gently.",
  },
  {
    id: 39, title: "Domingo com Amigos", subtitle: "Domenica con gli Amici", free: false,
    keywords: [
      { italian: "Vi va di...?", english: "Vocês querem…?" },
      { italian: "Preferirei", english: "Eu preferiria" },
      { italian: "L'agriturismo", english: "Restaurante rural / agroturismo" },
      { italian: "È affollato", english: "Está cheio" },
      { italian: "Non si trova parcheggio", english: "Não se encontra vaga" },
      { italian: "Che ne dite?", english: "O que vocês acham?" },
    ],
    dialogue: [
      { speaker: "A", line: "Vi va di andare al mare domenica?", translation: "Vocês querem ir à praia no domingo?" },
      { speaker: "B", line: "Preferirei andare a mangiare in un agriturismo.", translation: "Eu preferiria ir comer em um agroturismo." },
      { speaker: "C", line: "Anch'io — la spiaggia è sempre affollata.", translation: "Eu também — a praia está sempre cheia." },
      { speaker: "B", line: "Conosco un posto bellissimo in collina. Che ne dite?", translation: "Conheço um lugar lindo nas colinas. O que vocês acham?" },
    ],
    grammar: {
      title: "Si Impersonale — O si impessoal",
      points: [
        { italian: "Non si trova parcheggio", english: "Não se encontra vaga" },
        { italian: "Si mangia bene qui", english: "Come-se bem aqui" },
        { italian: "Come si dice?", english: "Como se diz?" },
        { italian: "Non si sa mai", english: "Nunca se sabe" },
      ],
      note: "O si impessoal não tem sujeito específico — como \"se\" em português. Come si dice? é essencial para os aprendizes!",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor role-playing friends planning a Sunday outing. Reply in Portuguese. Correct gently.",
  },
  {
    id: 40, title: "Parece e Eu Me Lembro", subtitle: "Mi Sembra e Mi Ricordo", free: false,
    keywords: [
      { italian: "Mi sembra che", english: "Me parece que" },
      { italian: "Mi pare", english: "Me parece / parece-me" },
      { italian: "Ti ricordi?", english: "Você se lembra?" },
      { italian: "Mi ricordo", english: "Eu me lembro" },
      { italian: "Non mi ricordo", english: "Não me lembro" },
      { italian: "Mi sembra ieri", english: "Parece que foi ontem" },
    ],
    dialogue: [
      { speaker: "A", line: "Ti ricordi di quella vacanza a Capri?", translation: "Você se lembra das férias em Capri?" },
      { speaker: "B", line: "Certo! Mi sembra ieri.", translation: "Claro! Parece que foi ontem." },
      { speaker: "A", line: "Ti ricordi quel ristorante sul mare?", translation: "Você se lembra daquele restaurante à beira-mar?" },
      { speaker: "B", line: "Mi pare di sì, ma non mi ricordo il nome.", translation: "Acho que sim, mas não me lembro do nome." },
    ],
    grammar: {
      title: "Verbos reflexivos — Memória e percepção",
      points: [
        { italian: "Mi ricordo", english: "Eu me lembro" },
        { italian: "Ti ricordi?", english: "Você se lembra?" },
        { italian: "Si ricorda", english: "Ele/Ela se lembra (também o senhor/a senhora)" },
        { italian: "Mi sembra / mi pare", english: "Me parece (intercambiável)" },
      ],
      note: "Ricordarsi é reflexivo: mi ricordo, ti ricordi, si ricorda etc. Mi sembra e mi pare são intercambiáveis.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a nostalgic conversation about shared memories. Reply in Portuguese. Correct gently.",
  },
  {
    id: 41, title: "Falar sobre o Passado", subtitle: "Parlare del Passato", free: false,
    keywords: [
      { italian: "Ho fatto", english: "Eu fiz" },
      { italian: "Ho mangiato", english: "Eu comi" },
      { italian: "Sono andato/a", english: "Eu fui" },
      { italian: "Siamo arrivati", english: "Nós chegamos" },
      { italian: "L'anno scorso", english: "No ano passado" },
      { italian: "La settimana scorsa", english: "Na semana passada" },
    ],
    dialogue: [
      { speaker: "A", line: "Come hai passato il weekend?", translation: "Como você passou o fim de semana?" },
      { speaker: "B", line: "Sono andato a Venezia con mia moglie.", translation: "Fui a Veneza com minha esposa." },
      { speaker: "A", line: "Avete mangiato bene?", translation: "Vocês comeram bem?" },
      { speaker: "B", line: "Benissimo! Ho mangiato il miglior risotto della mia vita.", translation: "Muito bem! Comi o melhor risoto da minha vida." },
    ],
    grammar: {
      title: "Passato Prossimo — Avere vs Essere",
      points: [
        { italian: "Ho mangiato (avere)", english: "Comi — a maioria dos verbos usa avere" },
        { italian: "Sono andato/a (essere)", english: "Fui — verbos de movimento usam essere" },
        { italian: "Siamo arrivati (essere)", english: "Chegamos — o particípio concorda com o sujeito" },
        { italian: "Non ho capito", english: "Não entendi" },
      ],
      note: "Verbos de movimento e reflexivos usam essere. Todos os outros usam avere. Com essere, o particípio concorda.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor asking about recent activities. Reply in Portuguese. Correct gently.",
  },
  {
    id: 42, title: "Memórias de Infância", subtitle: "Ricordi d'Infanzia", free: false,
    keywords: [
      { italian: "Quando ero piccolo/a", english: "Quando eu era jovem" },
      { italian: "Giocavo", english: "Eu brincava" },
      { italian: "La scuola", english: "A escola" },
      { italian: "D'estate", english: "No verão" },
      { italian: "Ogni giorno", english: "Todos os dias" },
      { italian: "Mi piaceva", english: "Eu gostava" },
    ],
    dialogue: [
      { speaker: "A", line: "Com'era la tua infanzia?", translation: "Como era sua infância?" },
      { speaker: "B", line: "Bellissima! D'estate giocavo sempre fuori.", translation: "Maravilhosa! No verão, eu sempre brincava lá fora." },
      { speaker: "A", line: "E la scuola? Ti piaceva?", translation: "E a escola? Você gostava?" },
      { speaker: "B", line: "Mi piaceva la matematica.", translation: "Eu gostava de matemática." },
      { speaker: "A", line: "Quando ero piccola, volevo fare la ballerina.", translation: "Quando eu era pequena, queria ser bailarina." },
    ],
    grammar: {
      title: "Imperfeito — Hábitos e estados no passado",
      points: [
        { italian: "Giocavo ogni giorno", english: "Eu brincava todos os dias" },
        { italian: "Quando ero piccolo...", english: "Quando eu era jovem..." },
        { italian: "Mi piaceva la scuola", english: "Eu gostava da escola" },
        { italian: "Era bellissimo", english: "Era maravilhoso" },
      ],
      note: "O imperfeito descreve estados, hábitos e emoções passados. Ho mangiato la pizza (uma vez) vs Mangiavo la pizza ogni venerdì (toda sexta).",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a nostalgic conversation about childhood. Reply in Portuguese. Correct gently.",
  },
  {
    id: 43, title: "Expressar Opiniões", subtitle: "Esprimere Opinioni", free: false,
    keywords: [
      { italian: "Secondo me", english: "Na minha opinião" },
      { italian: "Penso che", english: "Acho que" },
      { italian: "Mi sembra", english: "Me parece" },
      { italian: "Mi pare", english: "Me parece (igual a mi sembra)" },
      { italian: "Sono d'accordo", english: "Concordo" },
      { italian: "Hai ragione", english: "Você tem razão" },
    ],
    dialogue: [
      { speaker: "A", line: "Secondo te, qual è la città più bella d'Italia?", translation: "Na sua opinião, qual é a cidade mais bonita da Itália?" },
      { speaker: "B", line: "Secondo me, Firenze. Mi sembra unica.", translation: "Na minha opinião, Florença. Me parece única." },
      { speaker: "A", line: "Penso che Roma sia più interessante.", translation: "Acho que Roma é mais interessante." },
      { speaker: "B", line: "Hai ragione, Roma è straordinaria.", translation: "Você tem razão, Roma é extraordinária." },
    ],
    grammar: {
      title: "Estruturas para dar opiniões",
      points: [
        { italian: "Secondo me...", english: "Na minha opinião… (lit. segundo eu)" },
        { italian: "Mi sembra che", english: "Me parece que" },
        { italian: "Sono / non sono d'accordo", english: "Concordo / não concordo" },
        { italian: "Hai ragione", english: "Você tem razão" },
      ],
      note: "Secondo me é a forma mais fácil de dar uma opinião. Mi sembra e mi pare são intercambiáveis e muito comuns.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor having a discussion about Italian cities. Reply in Portuguese. Correct gently.",
  },
  {
    id: 44, title: "Dar Conselhos", subtitle: "Dare Consigli", free: false,
    keywords: [
      { italian: "Dovresti", english: "Você deveria" },
      { italian: "Ti consiglio di", english: "Eu te aconselho a" },
      { italian: "È meglio che", english: "É melhor que" },
      { italian: "Al posto tuo", english: "No seu lugar" },
      { italian: "Perché non...?", english: "Por que você não…?" },
      { italian: "Prova a", english: "Tente" },
    ],
    dialogue: [
      { speaker: "A", line: "Non riesco a dormire bene.", translation: "Não consigo dormir bem." },
      { speaker: "B", line: "Dovresti andare a letto prima.", translation: "Você deveria ir dormir mais cedo." },
      { speaker: "B", line: "Ti consiglio di evitare il caffè la sera.", translation: "Eu te aconselho a evitar o café à noite." },
      { speaker: "A", line: "Al posto tuo, cosa faresti?", translation: "Se fosse você, o que faria?" },
      { speaker: "B", line: "Perché non provi una camomilla prima di dormire?", translation: "Por que você não tenta uma camomila antes de dormir?" },
    ],
    grammar: {
      title: "Condicional para dar conselhos",
      points: [
        { italian: "Dovresti riposare", english: "Você deveria descansar" },
        { italian: "Potresti provare", english: "Você poderia tentar" },
        { italian: "Al posto tuo, andrei", english: "No seu lugar, eu iria" },
        { italian: "Ti consiglio di aspettare", english: "Eu te aconselho a esperar" },
      ],
      note: "Dovresti (você deveria) e potresti (você poderia) são formas condicionais — perfeitas para dar conselhos.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor playing a wise friend giving advice. Reply in Portuguese. Correct gently.",
  },
  {
    id: 45, title: "Real e Hipotético", subtitle: "Reale e Ipotetico", free: false,
    keywords: [
      { italian: "Se ho i soldi, vado", english: "Se eu tiver dinheiro, vou (possibilidade real)" },
      { italian: "Se avessi i soldi, andrei", english: "Se eu tivesse dinheiro, iria (hipotético)" },
      { italian: "Magari potessi!", english: "Se eu pelo menos pudesse!" },
      { italian: "Nel caso in cui", english: "No caso em que" },
      { italian: "Dipende da", english: "Depende de" },
      { italian: "Chissà", english: "Quem sabe / talvez um dia" },
    ],
    dialogue: [
      { speaker: "A", line: "Cosa fai a luglio?", translation: "O que você vai fazer em julho?" },
      { speaker: "B", line: "Se ho i soldi, vado in Sicilia.", translation: "Se eu tiver dinheiro, vou à Sicília." },
      { speaker: "A", line: "Io sogno in grande — se avessi i soldi, andrei in Giappone!", translation: "Eu sonho alto — se eu tivesse dinheiro, iria ao Japão!" },
      { speaker: "B", line: "Magari potessi anch'io! Chissà, un giorno.", translation: "Quem dera eu também pudesse! Quem sabe, um dia." },
      { speaker: "A", line: "Se vincessi alla lotteria, ci andremmo insieme!", translation: "Se eu ganhasse na loteria, iríamos juntos!" },
    ],
    grammar: {
      title: "Condicionais — Real vs Hipotético",
      points: [
        { italian: "Se ho tempo, vengo", english: "Se eu tiver tempo, venho (real)" },
        { italian: "Se avessi tempo, verrei", english: "Se eu tivesse tempo, viria (hipotético)" },
        { italian: "Se fosse possibile", english: "Se fosse possível" },
        { italian: "Chissà", english: "Quem sabe (expressa incerteza sobre o futuro)" },
      ],
      note: "Real: se + presente. Hipotético: se + imperfeito do subjuntivo + condicional = algo improvável ou imaginário.",
    },
    aiPrompt: "STRICT RULES: Only discuss this lesson. You are an Italian tutor exploring real and hypothetical situations. Reply in Portuguese. Correct gently.",
  },
];

